### PR TITLE
Implement 'bypass_data_preservation' enhancement (Issue #824)

### PR DESCRIPTION
**Pull request by abraunegg**
* On some Linux distributions, the file system search tool locally modifies certain files after indexing. Even though the file contents has not changed, the file itself has, as the local modified timestamp has been updated. This then causes timestamp checks to be invalid. To ignore this in cases where this is occuring, configure 'bypass_data_preservation' to 'true' in the config file and local data protection rules will be ignored.

### CODE REVIEW

**Comment by abraunegg** [comment]
**background:**
Based on all the application & file tracing for #824, the following was occurring on the users systems:
* Dolphin File Indexer constantly accessing files and updating the modified timestamp. The process at fault was `baloo_file_extractor`. Every time this process ran, this created the issue.
* `x_thumbnailer` also appeared to touch and access every file
* `kdeinit5` which is part of Okular appears to also touch and modify every file

As such, this issue is 100% not an issue with this application as, if a file is modified locally - either by process, or manually, the local file will be out-of-sync with OneDrive, and will be renamed to preserve existing file to prevent data loss IF there is also a modified & newer file listed as a change on OneDrive to download.

**Comment by norbusan** [comment]
Hi @abraunegg 
this PR is marked as WIP, but you want a review?
I am a bit surprised, I am running KDE/Plasma but don't see this behavior, maybe it is something from an old version of KDE?
The changes look fine, though, only one item: it looks like it ships out warnings for each and every file, that might be a bit noisy even for vlog?

**Comment by abraunegg** [comment]
@norbusan 
Yes - wanted your view on this PR.

Regarding the notification - that should only occur if the option is enabled, and we get into a situation where OneDrive has an updated file, but so does the local file system based on modified time.

The current workflow is we, rename the local file (we dont know if the local file is modified by user or background process) thus the rename is for keeping the file to ensure data integrity.

This option changes that - does not rename, allows the file to be overwritten - thus may introduce data loss - if the local modify was user actioned. This is why, for every file where we are not renaming, log a warning that this might be leading to data loss - I think that is prudent, even if noisy - as it might prompt the user to look deeper: 'well what is modifying my files behind my back?'

It really is an odd corner case - based on all the logs / user data provided via email, it is external processes that are misbehaving - this client is acting correctly in these situations.

I am hesitant to implement this, but - it may be beneficial for those absolute edge cases.

**Comment by abraunegg** [comment]
@norbusan 
What are your thoughts re this PR .. OK to merge ?

**Comment by norbusan** [comment]
As I said, I am surprised that such a strange behavior exists, I don't see it with dolphin/baloo whatever. But if it helps someone, so be it.

**Comment by theeggdev** [comment]
**I had the same issue as #824. I am using a raspberry pi 3 with raspbian 4.19.118-v7+**

**I am totally aware of the fact that** 

> My current thoughts here is - this 'feels' like one of the original 'skilion' bugs where the 'hostname' of the linux system is added to the file name when there is a conflict. This I KNOW was fixed. 

Because in last year, I had the same issue (saved multiple files) in my machine with ubuntu. 
Then it was resolved with pulling the latest version of your code lol
Afterwards, I experienced the issue #585;
and then followed by #593.
And with your help all issues were resolved! 
(There has been some occasion of syncing issue after that, hence resulted in multiple files being created. But that happened so randomly, I don't think there's any fault in your code)

**Anyway, back to my problematic raspberry pi -** 

I got the following message in my log 
`Jun 22 13:05:08 egg-pie onedrive[2181]: Trying to delete item project management/[...].xlsx`
`Jun 22 13:05:08 egg-pie onedrive[2181]: Skipped due to id difference!
`

and multiple files were created like how #824 described. 

Now I set `bypass_data_preservation` to true, and the issue got resolved.

Because the issue got resolved, I have not raised any issue on that. But in case you would like to investigate deeper into this issue (perhaps?) please let me know and I can send you my debug log to you.

Once again thank you for all the fixes and enhancement you guys have made!

**Comment by abraunegg** [comment]
@theeggdev 
Glad this 'work around' is useful for you.

Can you please provide some details on the following:

Based on original issue, all the application & file tracing, the following was occurring on the users systems:
* Dolphin File Indexer constantly accessing files and updating the modified timestamp. The process at fault was `baloo_file_extractor`. Every time this process ran, this created the issue.
* `x_thumbnailer` also appeared to touch and access every file
* `kdeinit5` which is part of Okular appears to also touch and modify every file

Do you have **any** of these running *when* you experience the issue? If yes, then an issue needs to be raised with the respective application, as, verbose debug logging of this application shows the files are being modified locally, but without any user interaction .. so it is something local, on your system that is causing the issue.

**Pull request merged**
