### PR TITLE
Prevent monitoring files inside .folders when using skip_dotfiles in monitor mode

### PR DESCRIPTION
**Pull request by TheOnlyTrueJonathanHeard**
Currently the onedrive client monitors all files inside dotfolders when using the skip_dotfile option. I wouldn't call this a bug but it is not optimal as this lead to unnecessary usage of resources and it makes the log file more difficult to read. Furthermore this behavior is inconsistent as files inside a folder listed in the skip_dir option are not monitored.

For me personally this Fix is important because I am using the onedrive client to synchronize most parts of my home folder with the cloud. As many program files are saved in hidden folders inside the home directory (such as .cache and .config) my log file is currently spammed with irrelevant information and the cpu usage is increased noticeable.

## Example Use Case
1. Comment  out the line skip_dotfiles and change value to “true” in your config file
2. Start onedrive in monitor mode with the option resync: onedrive --monitor --resync --enable-logging
3. Create a Folder which starts with a dot file
4. Create a file inside the folder created in the previous step
5. Rename the file created in the previous step

Expected Behavior: 
The Renaming of the file is not logged as the file is inside a dot folder. 

Actual Behavior:
Two logs are created for the action. One for renaming the file and one for skipping the upload of the file. 

## Verbose Log Output without PR

```
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/johnny/OneDrive
Application version: v2.4.0-6-g2859ddc
Account Type: personal
Default Drive ID: dc457103bff8ccb6
Default Root ID: DC457103BFF8CCB6!101
Remaining Free Space: 5368709120
Fetching details for OneDrive Root
OneDrive Root does not exist in the database. We need to add it.
Added OneDrive Root to the local database
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Applying changes of Path ID: DC457103BFF8CCB6!101
Uploading differences of .
Processing root
The directory has not changed
Uploading new items of .
Applying changes of Path ID: DC457103BFF8CCB6!101
Initializing monitor ...
OneDrive monitor interval (seconds): 30
Monitor directory: .
Monitor directory: ./.hidden
[M] Directory created: ./.hidden
Uploading differences of ./.hidden
Uploading new items of ./.hidden
Skipping item - .file or .folder: ./.hidden
[M] File changed: .hidden/test
Uploading differences of .hidden/test
Uploading new items of .hidden/test
Skipping item - .file or .folder: .hidden/test
[M] Item moved: .hidden/test -> .hidden/renamed
Moving .hidden/test to .hidden/renamed
Skipping upload due to skip_dotfile = true
```

## Verbose Lout Output with PR

```
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/johnny/OneDrive
Application version: v2.4.0-7-g485d71d
Account Type: personal
Default Drive ID: dc457103bff8ccb6
Default Root ID: DC457103BFF8CCB6!101
Remaining Free Space: 5368709120
Fetching details for OneDrive Root
OneDrive Root does not exist in the database. We need to add it.
Added OneDrive Root to the local database
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Applying changes of Path ID: DC457103BFF8CCB6!101
Uploading differences of .
Processing root
The directory has not changed
Uploading new items of .
Applying changes of Path ID: DC457103BFF8CCB6!101
Initializing monitor ...
OneDrive monitor interval (seconds): 30
Monitor directory: .
```

## Code Explanation
As this PR contains more code than my previous PRs, I think it is useful to give a short description what I actually have done. 
The .Folder are currently monitored because they are not skipped in the addRecursive function inside the Monitor class. However it is not that easily to check if a folder starts with a dot as the function provided for this is in the sync.d file. I think it is neither good practice to implement another function for the same purpose in the Monitor class nor it is good to make the isDotFile function somehow available in the monitor class. Instead, it is better to move the isDotFile function inside the selective.d file and check in the already existing isDirNameExclude function additional if the passed directory name has to be excluded because of starting with a dot.  By Moving the isDotFile function to the selective.d file, also the functions which call the isDotFile functions have to be modified.  These are functions which make sure that dotfiles (and folders) are skipped during upload/download. However due to the change in the isDirNameExclude function in the selective.d file, it is already made sure that .folders are skipped during upload/download in future. In order to make this also working for files in future, I have also implemented a check for .Files in the isFileNameExcluded function.
Finally it should be mentioned that currently the functions isDirNameExcluded and isFileNameExcluded is called by removing the leading ./ with the help of the std.string.strip function. However for some reason this function doesn't lead to the desired result for dotfiles because this also removes the leading dot of the file, e.g: 

`    writeln(strip("./.test", "./"));  `

gives test instad of .test. Therefore I have now used the strip function of the std.alogrithm.mutation submodule.

For the sake of completeness it should be mention that by this PR unfortunately the logging for skip_dir files is worsened (e.g. if a user moves a file into a .folder the user is now only informed in the logging that the file has been deleted remotely but without a reason as before).  Due to the code change this is now more complicated to implement and I think this needs to be investigated in other PR if desired.

### CODE REVIEW

**Comment by abraunegg** [comment]
@TheOnlyTrueJonathanHeard 
Thanks for this PR, however I have the following comments with the code the way it is:
1. Changes the skip_file / skip_dir handling to now be either that or skip_dotfiles .. the intention here is that each skip is separate, not combined so it is clear as to why something was skipped
2. Agree with the approach of changing how ./ is removed from paths by using a new function
3. In selective.d - `private bool skipDotfiles = true;` should be false, and only true if set.
4. Rather than all the other changes, in monitor.d, under addRecursive (given you are setting a flag if skip dotfiles was enabled) in the skip filtered items add:
```
...
		// skip filtered items
		if (dirname != ".") {
			if (selectiveSync.isDirNameExcluded(dirname.strip('.').strip('/'))) {
				return;
			}
			if (selectiveSync.isFileNameExcluded(baseName(dirname))) {
				return;
			}
			if (selectiveSync.isPathExcludedViaSyncList(buildNormalizedPath(dirname))) {
				return;
			}

			if (selectiveSync.getSkipDotfiles()){
				// skip_dotfiles is enabled
				do something here to match
				return;
			}
...
```

This approach should have the same net effect of not monitoring a .folder at startup, or a .folder when created elsewhere .. and potentially negate all the other changes.

**Comment by abraunegg** [comment]
@TheOnlyTrueJonathanHeard 

Please can you review #848 in regards to your issue / this PR as an alternative. Feel free to expand on that as well

**Comment by TheOnlyTrueJonathanHeard** [comment]
Thanks for reviewing and improving the PR. I am happy with #848 :+1:

**Comment by abraunegg** [comment]
@TheOnlyTrueJonathanHeard 

No problem - can you test extensively #848  against all your use cases please

**Pull request closed without merging**
