### PR TITLE
Layout rework

### PR DESCRIPTION
**Pull request by abraunegg**
* Initial pull of these changes

### CODE REVIEW

**Comment by norbusan** [comment]
Looks fine to me, but what about moving the systemd.units directory *also* to the contrib directory? We have already several things there that are installed, so I don't see why systemd stuff should be in the toplevel.

**Comment by norbusan** [comment]
And yes, we could move the Dockerfiles to their own directory, and adjust the DOCKER.md to use `-f contrib/docker/Dockerfile` when describing how to build. But I am not sure how this would work with the integration fo @abraunegg in the docker cloud.

**Comment by abraunegg** [comment]
> Looks fine to me, but what about moving the systemd.units directory _also_ to the contrib directory? We have already several things there that are installed, so I don't see why systemd stuff should be in the toplevel.

Agree - systemd stuff could also be in the contrib directory

**Comment by abraunegg** [comment]
> And yes, we could move the Dockerfiles to their own directory, and adjust the DOCKER.md to use `-f contrib/docker/Dockerfile` when describing how to build. But I am not sure how this would work with the integration for in the docker cloud.

Unsure as well - can always move this around and see what works / breaks ..

**Comment by abraunegg** [comment]
@norbusan 
What about also adding relevant badges from https://shields.io/ to readme.md as well ?

**Comment by norbusan** [comment]
Moved the systemd stuff to `contrib/systemd`

**Comment by norbusan** [comment]
Concerning shields: fine with me .. which one?

**Comment by norbusan** [comment]
@abraunegg do you have the credential for the docker cloud driveone account?

**Comment by abraunegg** [comment]
Will add you to the docker ci stuff

**Comment by norbusan** [comment]
Moved the docker files to `contrib/docker`, fixed the alpine and stretch docker file, and updated INSTALL.md to also require `pkg-config`.

**Comment by norbusan** [comment]
I am fine with that ;-)

**Comment by abraunegg** [comment]
@norbusan 
Now to update Docker Hub so that things build automatically based on the new paths

**Comment by abraunegg** [comment]
@norbusan 
Despite changing things on Docker Hub - the auto builds are not working ...

**Comment by norbusan** [comment]
I'll take a look later tonight, out for meetings

**Pull request merged**
