### PR TITLE
Update Sharepoint Document Library modified file handling

### PR DESCRIPTION
**Pull request by abraunegg**
* Update Sharepoint Document Library handling for .txt & .csv files
* Use replace function for modified Sharepoint Document Library files rather than delete and upload as new

### CODE REVIEW

**Comment by abraunegg** [comment]
**with patch**
```
Using Config Dir: /home/alex/.config/onedrive-sharepoint
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDriveSharePoint
Initializing the Synchronization Engine ...
Application version: v2.3.7-13-g170198c
Account Type: documentLibrary
Default Drive ID: b!QMiiVyjynUC_UIBZ4WaV8UveUfEgF9BGseBAWSULEb7n4JeIvgOVR4zlieNatYHC
Default Root ID: 017YXNCTF6Y2GOVW7725BZO354PWSELRRZ
Remaining Free Space: 1099508406131
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from OneDrive ...
Applying changes of Path ID: 017YXNCTF6Y2GOVW7725BZO354PWSELRRZ
Uploading differences of .
Processing root
The directory has not changed
Processing newfile.docx
The file last modified time has changed
The file content has changed
Uploading modified file newfile.docx ... skipped.
Skip Reason: Microsoft Sharepoint 'enrichment' after upload issue
See: https://github.com/OneDrive/onedrive-api-docs/issues/935 for further details
Uploading new items of .
Requested file to upload exists on OneDrive - local database is out of sync for this file: ./newfile.docx
Requested file to upload is newer than existing file on OneDrive
Uploading modified file ./newfile.docx ... done.
Due to Microsoft Sharepoint 'enrichment' of files, downloading 'enriched' file to ensure local file is in-sync
See: https://github.com/OneDrive/onedrive-api-docs/issues/935 for further details
Remaining free space: 1099508395992
Applying changes of Path ID: 017YXNCTF6Y2GOVW7725BZO354PWSELRRZ
```

**Comment by abraunegg** [comment]
> Compiles and runs fine here, only that I cannot trigger these actions, in my case no "improvements" are happening.

Only can be triggered in this scenario:
* Using OneDrive / Office 365 Business +
* Using a Sharepoint site by setting `drive_id` in config

**Comment by theeggdev** [comment]
@abraunegg Thank you for your fast response!!

**Below are the result of my test** 

Tested on uploading modified .xlsx file:
```
Jul 16 11:13:29 egghkdev onedrive[2909]: Uploading modified file project management/List of All Apply-to-all Negatives.xlsx ...  skipped.
Jul 16 11:13:31 egghkdev onedrive[2909]: Uploading modified file project management/List of All Apply-to-all Negatives.xlsx ... done.
Jul 16 11:13:35 egghkdev onedrive[2909]: Uploading modified file project management/List of All Apply-to-all Negatives - A.xlsx ...  skipped.
Jul 16 11:13:36 egghkdev onedrive[2909]: Uploading modified file project management/List of All Apply-to-all Negatives - B.xlsx ... done.
```
```
Result on Onedrive: 
Admin deleted List of All Apply-to-all Negatives - B.xlsx
Admin created List of All Apply-to-all Negatives - B.xlsx
Admin deleted List of All Apply-to-all Negatives.xlsx
Admin created List of All Apply-to-all Negatives.xlsx
```
Tested on uploading modified .csv file:
```
Jul 16 11:24:33 egghkdev onedrive[2909]: Uploading modified file project management/F/automated reports/linkedin/New_Posts.csv ...  skipped.
Jul 16 11:24:34 egghkdev onedrive[2909]: Uploading modified file project management/F/automated reports/linkedin/New_Posts.csv ... done.
Jul 16 11:24:37 egghkdev onedrive[2909]: Uploading modified file project management/F/automated reports/tracker/ad report.csv ...  skipped
Jul 16 11:24:40 egghkdev onedrive[2909]: Uploading modified file project management/F/automated reports/tracker/ad report.csv ... done.
Jul 16 11:24:41 egghkdev onedrive[2909]: Uploading modified file project management/F/automated reports/tracker/last refresh time.csv ... 
Jul 16 11:24:42 egghkdev onedrive[2909]: Uploading modified file project management/F/automated reports/tracker/last refresh time.csv ... 
```
```
Result on Onedrive: 
Admin deleted last refresh time.csv
Admin created last refresh time.csv
Admin deleted ad report.csv
Admin created ad report.csv
... etc.
```

So it seems that the 2 items in the description are not reflected in the commit

**Below I recap what I have done in case I have done anything wrong** 
```
systemctl stop --user onedrive
systemctl disable --user onedrive
cd onedrive
git fetch
git checkout master
git pull
source ~/dlang/dmd-2.087.0/activate
make clean; ./configure; make;
deactivate
systemctl enable --user onedrive
systemctl start --user onedrive

```
Confirmed that I am at the latest commit in master 
```
~/onedrive$ git pull
Updating f39621c..b23390c
Fast-forward

```

Thank you once again!

**Comment by abraunegg** [comment]
@theeggdev 
```
systemctl stop --user onedrive
systemctl disable --user onedrive
cd onedrive
git fetch
git checkout master
git pull
source ~/dlang/dmd-2.087.0/activate
make clean; ./configure; make;
deactivate
systemctl enable --user onedrive
systemctl start --user onedrive
```

I am not seeing a `make install` ... your still running the older binary / code. You may be building the latest, but not installing it. Suggest you stop your services, compile & run directly from the git directory to validate the fix before performing `make install`

**Comment by theeggdev** [comment]
I apologise for my stupidity :(
I can now conclude that the 2 enhancements are working fine in my machine. 

Huge thanks to you @abraunegg !

**Pull request merged**
