### PR TITLE
OneDrive Client Version v2.5.0-alpha-4 + @JC-comp #2519: Replace polling monitor loop with blocking wait

### LINKED ISSUE #2518: Feature Request: Add support for local full scan separation and blocking loop in monitor mode
### Is your feature request related to a problem? Please describe.

The full scan issue for remote side is perfectly resolved in v2.5.x now, to further improve the system performance, I'm wondering if we can also not to perform a file system walk and database walk when receiving notification from hooks in monitor loop. So that we can save system resouces of repeatedly walk and polling.

### Describe the solution you'd like

The idea is
1. Use blocking inotify in seperate thread to replace a polling loop in main thread.
2. In main thread, wait exact interval until next loop or until a wakeup signal from threads
3. Seperate the behavior of event triggered and monitor loop triggered sync.
4. For event triggered sync, only to handle gathered remote (/delta) and local (inotify) changes without a full local consistent check.
5. For monitor loop triggered sync, full scan on both side. Or futher seperate flags for remote full scan and local full scan interval.

### Describe alternatives you've considered

Not at this point.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by abraunegg**
## Summary

This is an implementation that resolves #2518 

**Changes**
- Replace polling monitor loop with blocking wait
- Check inotify events in separate threads and send signals to main thread when changes are available
- Add blocking wait support for webhooks
- Only handle changes from /delta when webhook events are received
- Handle all inotify events and never discard them at any time to prevent missing local changes

**How Has This Been Tested?**
- build and run in monitor loop
- test local change handling trigger: create/delete/move local file/folder
- test remote sync trigger: wait for next monitor_interval
- test shutdown capability: monitor_max_loop set to 1 and 2
- test integration:
    - sync mode
    - local first
    - upload only
    - download only
- test stability: run 6 300-sec-interval monitor loop

**What is still missing?**
- Checking if the interrupt triggered at [src/monitor.d](https://github.com/JC-comp/onedrive/blob/223ae4d5a91d94f0f964a7aa432f17e787143228/src/monitor.d#L105) is mandatory (does not affect functionality)

**Effect**
Remove the following inotify polling and sync checking, sleep every second
```
clock_nanosleep(CLOCK_REALTIME, 0, {tv_sec=1, tv_nsec=0}, 0x7ffda2aa2490) = 0
poll([{fd=6, events=POLLIN}], 1, 0)     = 0 (Timeout)
clock_nanosleep(CLOCK_REALTIME, 0, {tv_sec=1, tv_nsec=0}, 0x7ffda2aa2490) = 0
poll([{fd=6, events=POLLIN}], 1, 0)     = 0 (Timeout)
clock_nanosleep(CLOCK_REALTIME, 0, {tv_sec=1, tv_nsec=0}, 0x7ffda2aa2490) = 0
poll([{fd=6, events=POLLIN}], 1, 0)     = 0 (Timeout)
clock_nanosleep(CLOCK_REALTIME, 0, {tv_sec=1, tv_nsec=0}, 0x7ffda2aa2490) = 0
poll([{fd=6, events=POLLIN}], 1, 0)     = 0 (Timeout)
....
```

### CODE REVIEW

**Comment by abraunegg** [comment]
@cholzer79 , @Lyncredible

Given the current maturity of 'alpha-4' - are you potentially able to test this specific PR which has changes specifically impacting the current 'WebHooks' feature?

It would be great if you are able to test this and provide some feedback based on using Webhooks with this PR.

**Comment by Lyncredible** [comment]
@abraunegg Sorry but I am quite busy in Jan. Will give it a try when I find some free time but no promises...

**Comment by abraunegg** [comment]
@Lyncredible 
> @abraunegg Sorry but I am quite busy in Jan. Will give it a try when I find some free time but no promises...

When you do get to review, please review 'alpha-5' as I am going to close off this PR.

The 'alpha-5' PR is: https://github.com/abraunegg/onedrive/pull/2582

**Comment by abraunegg** [comment]
Typo: The 'alpha-5' PR is: https://github.com/abraunegg/onedrive/pull/2584

**Comment by abraunegg** [comment]
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

**Pull request closed without merging**
