### PR TITLE
Add date tag on docker.hub

### PR DESCRIPTION
**Pull request by mnagaku**
By adding a script, you can register tags indicating the date and time of build.

Screenshot from 2019-07-11 17-42-19

### CODE REVIEW

**Comment by norbusan** [comment]
@abraunegg I guess the Travis CI breaks now due to a PR from a different fork, so secrets are not available, and onedrive hangs waiting for authentication.

Didn't that work before in a different way?
```
All operations will be performed in: /home/travis/OneDriveALT
Initializing the Synchronization Engine ...
OneDrive returned a 'HTTP 400 - Bad Request' - gracefully handling error
Invalid authentication response from OneDrive. Please check the response uri
Authorize this app visiting:
https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=22c49a0d-d21c-4792-aed1-8f163c982546&scope=files.readwrite%20files.readwrite.all%20offline_access&response_type=code&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient
Enter the response uri: 
```

**Comment by abraunegg** [comment]
> Didn't that work before in a different way?

External commits always do this due to the secrets in use. Our commit's don't fail as we are part of the right security groups.

**Comment by norbusan** [comment]
Then we should merge this by hand, I can do this later tonight (JST time).

**Comment by norbusan** [comment]
@abraunegg I tried to merge this manually after rebasing and approving, but github still rejects it. I think the requirements are too tight:
```
$ git push
X11 forwarding request failed on channel 0
Enumerating objects: 19, done.
Counting objects: 100% (19/19), done.
Delta compression using up to 8 threads
Compressing objects: 100% (13/13), done.
Writing objects: 100% (16/16), 1.71 KiB | 349.00 KiB/s, done.
Total 16 (delta 6), reused 0 (delta 0)
remote: Resolving deltas: 100% (6/6), completed with 3 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: 2 of 2 required status checks are expected. At least 1 approving review is required by reviewers with write access.
To github.com:abraunegg/onedrive.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:abraunegg/onedrive.git'
$
```

**Pull request merged**
