### PR TITLE
Added support for loading system configs if there's no user config.

### PR DESCRIPTION
**Pull request by lirannl**
Uses application defaults if corrupt. The idea is that someone creating their own distribution or just a community iso of an existing one could ship custom default configs that could then be overridden in user space.

Alternatively, a default config could be set on a multi user system, that could then still be overridden by supplying a user config file (usually by copying the system one and making changes to it). I basically copied the way fontconf and .desktop files do that.

### CODE REVIEW

**Comment by lirannl** [comment]
I've looked into the travis failutre and it seems to be completely unrelated. I didn't touch anything that had anything to do with the refresh token...

**Comment by abraunegg** [comment]
@lirannl 
The Travis CI failure is because the internal variable stored for the test account which is used to run the application in the CI tests, is not shareable.

**Comment by abraunegg** [comment]
@lirannl 
Currently reviewing this PR, yet to fully test due to #910 work.

The only thing I can think of at this stage is also updating the documentation to reflect where a 'config' file could come from, what order they will then be searched in, and in what order they will override the previous.

**Comment by abraunegg** [comment]
@lirannl
Can you please look at re-working this PR based on the changes to current 'master' as there are now conflicts.

**Comment by abraunegg** [comment]
@lirannl 
Any chance to update this before Friday to allow this to be included in v2.4.2 ?

**Comment by abraunegg** [comment]
@norbusan 
Can you review this - should the config load / check be:
* User -> System -> Defaults

or

* System -> User -> Defaults

Thoughts?

**Comment by norbusan** [comment]
> * User -> System -> Defaults
> or
> * System -> User -> Defaults

I think there is only one reasonable way, namely that the User preferences have the highest priority, then system preferences, and finally defaults. That is how *every* other system I know (besides probably vim which has messed up the whole config file loading) is doing it.

**Comment by abraunegg** [comment]
> > * User -> System -> Defaults
> >   or
> > * System -> User -> Defaults
> 
> I think there is only one reasonable way, namely that the User preferences have the highest priority, then system preferences, and finally defaults. That is how _every_ other system I know (besides probably vim which has messed up the whole config file loading) is doing it.

OK .. will leave the code as is then without any further changes

**Comment by abraunegg** [comment]
> That looks fine.
> 
> One idea for the future - we **could** move generated files that are not really configuration files (sqlite and token stuff) to `~/.cache/onedrive` ... that way syncing say the `.config/onedrive` directory between machines would be possible (without using exceptions).

Happy for a PR to be created for this

**Pull request merged**
