### PR TITLE
Add additional JSON object validation

### PR DESCRIPTION
**Pull request by abraunegg**
* Add additional JSON object validation for queries made against OneDrive where a JSON response is expected and where that response is to be used and expected to be valid

### CODE REVIEW

**Comment by abraunegg** [comment]
@norbusan 
Best to review this one with "Hide whitespace changes" enabled .. 

I am still going through to code to ensure that all `= onedrive.<function>` calls that expect a valid JSON to be returned, are validated upon return ...

**Comment by abraunegg** [comment]
**notes:** PR #625 needs to be committed to master first, then this fixed / rebased

**Comment by norbusan** [comment]
> Best to review this one with "Hide whitespace changes" enabled ..

Practically always doing that - I would love to see a setting to turn this on by default ;-)

**Comment by abraunegg** [comment]
@norbusan 
Rebased / fixed after #625 merge to master

**Pull request merged**
