### PR TITLE
Support blocking monitor loop and full scan separation

### PR DESCRIPTION
**Pull request by JC-comp**
## Summary

This is an implementation ~~for replacing polling monitor loop~~ that resolves ~~part of~~ #2518 

Changes
- Replace polling monitor loop with blocking wait
- Check inotify events in separate threads and send signals to main thread when changes are available

How Has This Been Tested?
- build and run in monitor loop
- test local change handling trigger: create/delete/move local file/folder
- test remote sync trigger: wait for next monitor_interval
- test shutdown capability: monitor_max_loop set to 1 and 2
- test integration:
    - sync mode
    - local first
    - upload only
    - download only
- test stability: run 6 300-sec-interval monitor loop

What is still missing?
- Error handling logs (out of scope)
- Checking if the interrupt triggered at [src/monitor.d](https://github.com/JC-comp/onedrive/blob/223ae4d5a91d94f0f964a7aa432f17e787143228/src/monitor.d#L105) is mandatory (does not affect functionality)

Effect
Remove the following inotify polling and sync checking, sleep every second
```
clock_nanosleep(CLOCK_REALTIME, 0, {tv_sec=1, tv_nsec=0}, 0x7ffda2aa2490) = 0
poll([{fd=6, events=POLLIN}], 1, 0)     = 0 (Timeout)
clock_nanosleep(CLOCK_REALTIME, 0, {tv_sec=1, tv_nsec=0}, 0x7ffda2aa2490) = 0
poll([{fd=6, events=POLLIN}], 1, 0)     = 0 (Timeout)
clock_nanosleep(CLOCK_REALTIME, 0, {tv_sec=1, tv_nsec=0}, 0x7ffda2aa2490) = 0
poll([{fd=6, events=POLLIN}], 1, 0)     = 0 (Timeout)
clock_nanosleep(CLOCK_REALTIME, 0, {tv_sec=1, tv_nsec=0}, 0x7ffda2aa2490) = 0
poll([{fd=6, events=POLLIN}], 1, 0)     = 0 (Timeout)
....
```

### CODE REVIEW

**Comment by abraunegg** [comment]
@JC-comp 
Many thanks for your efforts here, however I have just tried to clone this PR as it is, and compile to test locally and I am unable to do so:
```
Cloning into 'onedrive-pr2519'...
remote: Enumerating objects: 6907, done.
remote: Counting objects: 100% (1953/1953), done.
remote: Compressing objects: 100% (288/288), done.
remote: Total 6907 (delta 1754), reused 1802 (delta 1663), pack-reused 4954
Receiving objects: 100% (6907/6907), 4.63 MiB | 10.03 MiB/s, done.
Resolving deltas: 100% (4886/4886), done.
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Total 5 (delta 4), reused 5 (delta 4), pack-reused 0
Unpacking objects: 100% (5/5), 1.77 KiB | 908.00 KiB/s, done.
From https://github.com/abraunegg/onedrive
 * [new ref]         refs/pull/2519/head -> pr2519
Switched to branch 'pr2519'
checking for a BSD-compatible install... /usr/bin/install -c
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for dmd... ldc2
checking version of D compiler... 1.18.0
checking for curl... yes
checking for sqlite... yes
checking for notify... no
configure: creating ./config.status
config.status: creating Makefile
config.status: creating contrib/pacman/PKGBUILD
config.status: creating contrib/spec/onedrive.spec
config.status: creating onedrive.1
config.status: creating contrib/systemd/onedrive.service
config.status: creating contrib/systemd/onedrive@.service
rm -f onedrive onedrive.o version
rm -rf autom4te.cache
rm -f config.log config.status
if [ -f .git/HEAD ] ; then \
        git describe --tags > version ; \
else \
        echo v2.5.0-alpha-2 > version ; \
fi
ldc2  -w -g -O -J. -L-lcurl -L-lsqlite3  -L-ldl src/main.d src/config.d src/log.d src/util.d src/qxor.d src/curlEngine.d src/onedrive.d src/sync.d src/itemdb.d src/sqlite.d src/clientSideFiltering.d src/progress.d src/monitor.d -ofonedrive
src/monitor.d(139): Error: shared method monitor.MonitorBackgroundWorker.watch is not callable using a non-shared object
src/monitor.d(143): Error: shared method monitor.MonitorBackgroundWorker.shutdown is not callable using a non-shared object
src/monitor.d(191): Error: shared method monitor.MonitorBackgroundWorker.initialise is not callable using a non-shared object
src/monitor.d(207): Error: shared method monitor.MonitorBackgroundWorker.shutdown is not callable using a non-shared object
src/monitor.d(278): Error: shared method monitor.MonitorBackgroundWorker.add is not callable using a non-shared object
src/monitor.d(322): Error: shared method monitor.MonitorBackgroundWorker.remove is not callable using a non-shared object
src/monitor.d(333): Error: shared method monitor.MonitorBackgroundWorker.remove is not callable using a non-shared object
/home/alex/dlang/ldc-1.18.0/bin/../import/std/concurrency.d(461): Error: static assert:  "Aliases to mutable thread-local data not allowed."
src/monitor.d(498):        instantiated from here: spawn!(void function(MonitorBackgroundWorker, Tid), MonitorBackgroundWorker, Tid)
```

Please can you look into this so that this can be merged into 'alpha-3'

**Comment by JC-comp** [comment]
> I have just tried to clone this PR as it is, and compile to test locally and I am unable to do so

PR Updated.
Fixed for LDC compiler error.
```
checking for a BSD-compatible install... /usr/bin/install -c
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for dmd... ldc2
checking version of D compiler... 1.35.0
checking for curl... yes
checking for sqlite... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating contrib/pacman/PKGBUILD
config.status: creating contrib/spec/onedrive.spec
config.status: creating onedrive.1
config.status: creating contrib/systemd/onedrive.service
config.status: creating contrib/systemd/onedrive@.service
if [ -f .git/HEAD ] ; then \
        git describe --tags > version ; \
else \
        echo v2.5.0-alpha-2 > version ; \
fi
ldc2 -w -g -O -J. -L-lcurl -L-lsqlite3  -L-ldl src/main.d src/config.d src/log.d src/util.d src/qxor.d src/curlEngine.d src/onedrive.d src/sync.d src/itemdb.d src/sqlite.d src/clientSideFiltering.d src/progress.d src/monitor.d -ofonedrive
done.
```

**Comment by abraunegg** [comment]
@JC-comp 
Please can you rebase this PR against https://github.com/abraunegg/onedrive/tree/onedrive-v2.5.0-alpha-3 so that it can be merged into 'alpha-3' ?

Right now, there would be 10 conflicts to deal with.

**Comment by JC-comp** [comment]
Changes:
- Add blocking wait support for webhook
- Refine cleanup process when client exit or failure

**Comment by JC-comp** [comment]
Changes
- Only handle changes from /delta when webhook events are received
- Handle all inotify events and never discard them at any time to prevent missing local changes 

now it resolves all features requested in #2518

**Comment by abraunegg** [comment]
@JC-comp 
Could you please pull this commit from this PR and make this a separate PR: https://github.com/abraunegg/onedrive/pull/2519/commits/7d11a8d429855213274f027bb656f82b71d68b27

**Comment by abraunegg** [comment]
@JC-comp 
This commit: https://github.com/abraunegg/onedrive/pull/2519/commits/51163d5a3625a57fc72effb5fbd5506d8d58b32b

Whilst valid, is on my whiteboard for a wider 'fix'.

In developing '2.5.x' I put in a lot of extra code to help ensure when things were being re-written, the code would 'break', then I would update various functions.

safeRename | safeBackup was two of the main ones.

If you could pull this commit from this PR that would be greatly appreciated.

**Comment by JC-comp** [comment]
@abraunegg 
> @JC-comp This commit: [51163d5](https://github.com/abraunegg/onedrive/commit/51163d5a3625a57fc72effb5fbd5506d8d58b32b)
> 
> Whilst valid, is on my whiteboard for a wider 'fix'.
> 
> In developing '2.5.x' I put in a lot of extra code to help ensure when things were being re-written, the code would 'break', then I would update various functions.
> 
> safeRename | safeBackup was two of the main ones.
> 
> If you could pull this commit from this PR that would be greatly appreciated.

This commit is neccesary for 0d1b044 to work, we have to mark a local backup as _copy_  instead of _move_, so that new items to be downloaded are not moved to the backup location remotely before downloading.

**Comment by abraunegg** [comment]
@JC-comp 
This current PR (in it's existing state) is rather broken.

When this PR is used to upload files online, it constantly attempts to create the folder online. This was an issue identified in 'alpha-3' which is fixed in 'alpha-4':
```
No additional changes or items that can be applied were discovered while processing the data received from Microsoft OneDrive
Sync with Microsoft OneDrive is complete
Monitoring directory: random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe
[M] Local directory created: random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe
Scanning the local file system 'random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe' for new data to upload ...
OneDrive Client requested to create this directory online: random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe
OneDrive Client requested to create this directory online: random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe
OneDrive Client requested to create this directory online: random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe
OneDrive Client requested to create this directory online: random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe
OneDrive Client requested to create this directory online: random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe
OneDrive Client requested to create this directory online: random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe
OneDrive Client requested to create this directory online: random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe
OneDrive Client requested to create this directory online: random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe
OneDrive Client requested to create this directory online: random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe
OneDrive Client requested to create this directory online: random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe
OneDrive Client requested to create this directory online: random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe
OneDrive Client requested to create this directory online: random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe
OneDrive Client requested to create this directory online: random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe
OneDrive Client requested to create this directory online: random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe
OneDrive Client requested to create this directory online: random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe
OneDrive Client requested to create this directory online: random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe
OneDrive Client requested to create this directory online: random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe
OneDrive Client requested to create this directory online: random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe
OneDrive Client requested to create this directory online: random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe
OneDrive Client requested to create this directory online: random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe
OneDrive Client requested to create this directory online: random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe
OneDrive Client requested to create this directory online: random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe
OneDrive Client requested to create this directory online: random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe
OneDrive Client requested to create this directory online: random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe
OneDrive Client requested to create this directory online: random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe
OneDrive Client requested to create this directory online: random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe
OneDrive Client requested to create this directory online: random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe
OneDrive Client requested to create this directory online: random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe
OneDrive Client requested to create this directory online: random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe
OneDrive Client requested to create this directory online: random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe
OneDrive Client requested to create this directory online: random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe
OneDrive Client requested to create this directory online: random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe
OneDrive Client requested to create this directory online: random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe
OneDrive Client requested to create this directory online: random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe
OneDrive Client requested to create this directory online: random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe
OneDrive Client requested to create this directory online: random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe
OneDrive Client requested to create this directory online: random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe
OneDrive Client requested to create this directory online: random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe
OneDrive Client requested to create this directory online: random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe
OneDrive Client requested to create this directory online: random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe
OneDrive Client requested to create this directory online: random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe
OneDrive Client requested to create this directory online: random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe
OneDrive Client requested to create this directory online: random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe
OneDrive Client requested to create this directory online: random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe
OneDrive Client requested to create this directory online: random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe
OneDrive Client requested to create this directory online: random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe
^CGot termination signal, performing clean up
Shutting down DB connection and merging temporary data
```

Second point, your changes to 'sync.d' and 'util.d' are 100% irrelevant to the technical change you are suggesting with this PR.

When I take your PR (minus the changes to 'sync.d' and 'util.d') - this is what is PR https://github.com/abraunegg/onedrive/pull/2582 essentially is.

When this PR is used, and new files are added to be uploaded, there is an issue with something to do with the triggers of the inotify handler:
```
Uploading: random_large_files/98Mqt7NCX3O72jQePtxf9nZNmThAKA5G/file0.data ... 80%  |  ETA    00:00:07
Uploading: random_large_files/98Mqt7NCX3O72jQePtxf9nZNmThAKA5G/file0.data ... 100% | DONE in 00:00:28
Uploading new file random_large_files/98Mqt7NCX3O72jQePtxf9nZNmThAKA5G/file0.data ... done.
[M] Local file changed: random_large_files/98Mqt7NCX3O72jQePtxf9nZNmThAKA5G/file0.data
Cannot upload file changes/creation: Unexpected end of input when converting from type string to type ulong
[M] Local file changed: random_large_files/98Mqt7NCX3O72jQePtxf9nZNmThAKA5G/file1.data
Cannot upload file changes/creation: Unexpected end of input when converting from type string to type ulong
[M] Local file changed: random_large_files/98Mqt7NCX3O72jQePtxf9nZNmThAKA5G/file2.data
Cannot upload file changes/creation: Unexpected end of input when converting from type string to type ulong
[M] Local file changed: random_large_files/98Mqt7NCX3O72jQePtxf9nZNmThAKA5G/file3.data
New items to upload to OneDrive: 1
Total New Data to Upload:        158 MB
```

This **does not** occur with 'alpha-4' - so it is *something* introduced with #2519:
```
...
New items to upload to OneDrive: 5
Total New Data to Upload:        205 MB
Uploading: ./random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe/file1.data ... 0%   |  ETA    --:--:--
Uploading: ./random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe/file4.data ... 0%   |  ETA    --:--:--
Uploading: ./random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe/file2.data ... 0%   |  ETA    --:--:--
Uploading: ./random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe/file3.data ... 0%   |  ETA    --:--:--
Uploading: ./random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe/file0.data ... 0%   |  ETA    --:--:--
Uploading: ./random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe/file2.data ... 20%  |  ETA    00:00:40
Uploading: ./random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe/file0.data ... 20%  |  ETA    00:00:40
Uploading: ./random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe/file3.data ... 20%  |  ETA    00:00:44
Uploading: ./random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe/file4.data ... 20%  |  ETA    00:00:48
Uploading: ./random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe/file1.data ... 20%  |  ETA    00:01:04
Uploading: ./random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe/file2.data ... 40%  |  ETA    00:00:27
Uploading: ./random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe/file0.data ... 40%  |  ETA    00:00:32
Uploading: ./random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe/file1.data ... 40%  |  ETA    00:00:36
Uploading: ./random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe/file3.data ... 40%  |  ETA    00:00:38
Uploading: ./random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe/file4.data ... 40%  |  ETA    00:00:39
Uploading: ./random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe/file2.data ... 60%  |  ETA    00:00:20
Uploading: ./random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe/file0.data ... 60%  |  ETA    00:00:20
Uploading: ./random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe/file3.data ... 60%  |  ETA    00:00:24
Uploading: ./random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe/file1.data ... 60%  |  ETA    00:00:25
Uploading: ./random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe/file4.data ... 60%  |  ETA    00:00:26
Uploading: ./random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe/file0.data ... 80%  |  ETA    00:00:11
Uploading: ./random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe/file2.data ... 80%  |  ETA    00:00:11
Uploading: ./random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe/file0.data ... 100% | DONE in 00:00:42
Uploading new file ./random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe/file0.data ... done.
Uploading: ./random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe/file2.data ... 100% | DONE in 00:00:43
Uploading new file ./random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe/file2.data ... done.
Uploading: ./random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe/file1.data ... 80%  |  ETA    00:00:11
Uploading: ./random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe/file1.data ... 100% | DONE in 00:00:45
Uploading new file ./random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe/file1.data ... done.
Uploading: ./random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe/file3.data ... 80%  |  ETA    00:00:12
Uploading: ./random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe/file4.data ... 80%  |  ETA    00:00:12
Uploading: ./random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe/file3.data ... 100% | DONE in 00:00:47
Uploading new file ./random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe/file3.data ... done.
Uploading: ./random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe/file4.data ... 100% | DONE in 00:00:47
Uploading new file ./random_large_files/35CLWBm9Zc2hd0NRdn4m2jTBeHAwHyCe/file4.data ... done.
Performing a last examination of the most recent online data within Microsoft OneDrive to complete the reconciliation process
Fetching /delta response from the OneDrive API for Drive ID: 66d53be8a5056eca
Processing API Response Bundle: 1 - Quantity of 'changes|items' in this bundle to process: 9
Finished processing /delta JSON response from the OneDrive API
Processing 8 applicable changes and items received from Microsoft OneDrive 
Processing OneDrive JSON item batch [1/1] to ensure consistent local state
Syncing this OneDrive Personal Shared Folder: OneDrive - Constanze
...
```

Please either re-work this PR or re-work #2582

**Comment by abraunegg** [comment]
@JC-comp 
Closing this in favour of https://github.com/abraunegg/onedrive/pull/2582

**Comment by abraunegg** [comment]
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

**Pull request closed without merging**
