### PR TITLE
Add extra debugging & http protocol downgrade (Issue #314)

### PR DESCRIPTION
**Pull request by abraunegg**
* Add --force-http-1.1 flag to downgrade any HTTP/2 curl operations to HTTP 1.1 protocol
* Explicitly set all bool items to false at initialisation
* Update --display-config to display sync_list if configured
* Add debug handling to display when sync_list is loaded
* Add debug handling to output the handling of OneDrive changes

### CODE REVIEW

**Comment by abraunegg** [comment]
**Note:** `--force-http-1.1` flag resolves #314, potentially will solve #323 & #324 as well

**Comment by norbusan** [comment]
CI testing reveals a crash, @abraunegg can you please look into that?

**Comment by abraunegg** [comment]
@norbusan 
CI testing crash should be taken care of now

**Comment by abraunegg** [comment]
superseded by #328

**Pull request merged**
