### PR TITLE
Resolve file creation loop when working directly in the synced folder with libreoffice

### PR DESCRIPTION
**Pull request by abraunegg**
* Resolve file creation loop when working directly in the synced folder with libreoffice

### CODE REVIEW

**Comment by abraunegg** [comment]
**with patch:**

Open a .pptx file locally with LibreOffice, modify, save and close application

Validated that updated file is same on Sharepoint site + local despite Microsoft 'enrichment' 

Tested exact same process with Personal and Business accounts to ensure non-breakage as potential to do so given this is around file uploads for modified files.

```
(dmd-2.083.0)[alex@centos7full onedrive-pr442]$ ./onedrive --confdir '~/.config/onedrive-business' --monitor --verbose 
Loading config ...
Using Config Dir: /home/alex/.config/onedrive-business
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/Documents
Initializing the Synchronization Engine ...
Account Type: documentLibrary
Default Drive ID: b!6H_y8BWP8Uqg2X0QAy4XfxiTMFe_reZKrMZXLeBjL4g70-n16rIGQpOG_l7vVxU5
Default Root ID: 01LWWIJZN6Y2GOVW7725BZO354PWSELRRZ
Remaining Free Space: 27487775449286
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing monitor ...
OneDrive monitor interval (seconds): 45
Monitor directory: .
[M] File changed: ./asdf.pptx
Uploading differences of ./asdf.pptx
Processing asdf.pptx
The file last modified time has changed
Uploading new items of ./asdf.pptx
[M] File changed: ./asdf.pptx
Uploading differences of ./asdf.pptx
Processing asdf.pptx
The file last modified time has changed
Uploading new items of ./asdf.pptx
[M] File changed: ./asdf.pptx
Uploading differences of ./asdf.pptx
Processing asdf.pptx
The file last modified time has changed
The file content has changed
Uploading modified file asdf.pptx ...  skipped.
Skip Reason: Microsoft Sharepoint 'enrichment' after upload issue
See: https://github.com/OneDrive/onedrive-api-docs/issues/935 for further details
Uploading new items of ./asdf.pptx
Requested file to upload exists on OneDrive - local database is out of sync for this file: ./asdf.pptx
Requested file to upload is newer than existing file on OneDrive
Uploading modified file ./asdf.pptx ... done.
Due to Microsoft Sharepoint 'enrichment' of files, downloading 'enriched' file to ensure local file is in-sync
See: https://github.com/OneDrive/onedrive-api-docs/issues/935 for further details
Remaining free space: 27487775375926
[M] File changed: ./asdf.pptx
Uploading differences of ./asdf.pptx
Processing asdf.pptx
The file last modified time has changed
Uploading new items of ./asdf.pptx
[M] File changed: ./asdf.pptx
Uploading differences of ./asdf.pptx
Processing asdf.pptx
The file last modified time has changed
Uploading new items of ./asdf.pptx
[M] File changed: ./asdf.pptx
Uploading differences of ./asdf.pptx
Processing asdf.pptx
The file last modified time has changed
Uploading new items of ./asdf.pptx
Applying changes of Path ID: 01LWWIJZN6Y2GOVW7725BZO354PWSELRRZ
Uploading differences of .
Processing root
The directory has not changed
Processing asdf.pptx
The file last modified time has changed
Uploading new items of .
Applying changes of Path ID: 01LWWIJZN6Y2GOVW7725BZO354PWSELRRZ
```

**Comment by norbusan** [comment]
I'm on a family trip till sunday, I will try to review it immediately afterwards.
How would one reproduce the error here? Just open an xlsx file located in the onedrive folder with libreoffice and edit away?

**Comment by abraunegg** [comment]
@norbusan 
> I'm on a family trip till sunday, I will try to review it immediately afterwards.
> How would one reproduce the error here? Just open an xlsx file located in the onedrive folder with libreoffice and edit away?

No rush

There are a number of dependencies:
* Run in monitor mode
* OneDrive account is an Office 365 account or OneDrive Business Sharepoint Folder - so that `Account Type: documentLibrary` - it has to be that otherwise bug will not trigger
* Edit a file type that MS 'enrich' - refer to https://github.com/OneDrive/onedrive-api-docs/issues/935 for details

**Comment by abraunegg** [comment]
@norbusan 
User validated fix as well in #441

**Comment by abraunegg** [comment]
@norbusan 
Should be good to approve / go if you are OK with the changes

**Comment by norbusan** [comment]
I cannot trigger this problem, but at least it works on my side ;-)

**Pull request merged**
