### PR TITLE
Fix uploading data to shared business folders when using --upload-only

### PR DESCRIPTION
**Pull request by abraunegg**
* Handle uploading new data to a OneDrive Shared Business Folder when using --upload-only and if the shared folder has never been synced before

### CODE REVIEW

**Review by norbusan — DISMISSED** [review]
I cannot really test this change, but the code looks somehow reasonable ... not that I can vouch for it, though.

**Comment by abraunegg** [comment]
> I cannot really test this change, but the code looks somehow reasonable ... not that I can vouch for it, though.

I plan on adding validation in here later - fixing a further issue uncovered when using `--dry-run`

**Comment by abraunegg** [comment]
**Config:**
```
Configuration file successfully loaded
onedrive version                       = v2.4.6-17-gff25371
Config path                            = /home/alex/.config/onedrive-business/
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/alex/OneDriveBusiness
Config option 'skip_dir'               = 
Config option 'skip_file'              = ~*|.~*|*.tmp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 30
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = false
Business Shared Folders configured     = true
business_shared_folders contents:
# Top level Folder
Top Folder
# Sub Shared Folder
# Sub Folder 2
```

### Without PR:
**Dry-Run**
```
(dmd-2.093.1)[alex@centos7full onedrive]$ ./onedrive --confdir '~/.config/onedrive-business/' --synchronize --sync-shared-folders --upload-only --verbose --resync --dry-run
Using 'user' Config Dir: /home/alex/.config/onedrive-business/
Using 'system' Config Dir: 
Configuration file successfully loaded
DRY-RUN Configured. Output below shows what 'would' have occurred.
Deleting the saved status ...
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Opening the item database ...
All operations will be performed in: /home/alex/OneDriveBusiness
Application version: v2.4.6-17-gff25371
Account Type: business
Default Drive ID: b!bO8V7s9SSk6r7mWHpIjURotN33W1W2tEv3OXV_oFIdQimEdOHR-1So7CqeT1MfHA
Default Root ID: 01WIXGO5V6Y2GOVW7725BZO354PWSELRRZ
Remaining Free Space: 1088627723055
Fetching details for OneDrive Root
OneDrive Root does not exist in the database. We need to add it.
Added OneDrive Root to the local database
Initializing the Synchronization Engine ...
Syncing changes from local path only - NOT syncing data changes from OneDrive ...
Uploading differences of ~/OneDriveBusiness
Processing .
The directory has not changed
Uploading new items of ~/OneDriveBusiness
OneDrive Client requested to create remote path: ./random_files
The requested directory to create was found on OneDrive - skipping creating the directory: ./random_files
The parent for this path is in the local database - adding requested path (./random_files) to database
OneDrive Client requested to create remote path: ./random_images
The requested directory to create was found on OneDrive - skipping creating the directory: ./random_images
The parent for this path is in the local database - adding requested path (./random_images) to database
OneDrive Client requested to create remote path: ./random_videos
The requested directory to create was found on OneDrive - skipping creating the directory: ./random_videos
The parent for this path is in the local database - adding requested path (./random_videos) to database
OneDrive Client requested to create remote path: ./Top Folder
The requested directory to create was not found on OneDrive - creating remote directory: ./Top Folder     <-- Incorrect as folder does exist, but is a OneDrive Business Shared Folder on another driveId we do not yet know about
Successfully created the remote directory ./Top Folder on OneDrive
OneDrive Client requested to create remote path: ./Top Folder/asdfasdf
The requested directory to create was not found on OneDrive - creating remote directory: ./Top Folder/asdfasdf     <-- Incorrect as folder does exist, but is a OneDrive Business Shared Folder on another driveId we do not yet know about
Successfully created the remote directory ./Top Folder/asdfasdf on OneDrive
Uploading new file ./Top Folder/asdfasdf/qwerksdjfg.txt ... done.
Uploading new file ./Top Folder/asdfasdfs.txt ... done.
(dmd-2.093.1)[alex@centos7full onedrive]$ 
```
**Actual**
```
(dmd-2.093.1)[alex@centos7full onedrive]$ ./onedrive --confdir '~/.config/onedrive-business/' --synchronize --sync-shared-folders --upload-only --verbose --resync
Using 'user' Config Dir: /home/alex/.config/onedrive-business/
Using 'system' Config Dir: 
Configuration file successfully loaded
Deleting the saved status ...
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Opening the item database ...
All operations will be performed in: /home/alex/OneDriveBusiness
Application version: v2.4.6-17-gff25371
Account Type: business
Default Drive ID: b!bO8V7s9SSk6r7mWHpIjURotN33W1W2tEv3OXV_oFIdQimEdOHR-1So7CqeT1MfHA
Default Root ID: 01WIXGO5V6Y2GOVW7725BZO354PWSELRRZ
Remaining Free Space: 1088627723055
Fetching details for OneDrive Root
OneDrive Root does not exist in the database. We need to add it.
Added OneDrive Root to the local database
Initializing the Synchronization Engine ...
Syncing changes from local path only - NOT syncing data changes from OneDrive ...
Uploading differences of ~/OneDriveBusiness
Processing .
The directory has not changed
Uploading new items of ~/OneDriveBusiness
OneDrive Client requested to create remote path: ./random_files
The requested directory to create was found on OneDrive - skipping creating the directory: ./random_files
The parent for this path is in the local database - adding requested path (./random_files) to database
OneDrive Client requested to create remote path: ./random_images
The requested directory to create was found on OneDrive - skipping creating the directory: ./random_images
The parent for this path is in the local database - adding requested path (./random_images) to database
OneDrive Client requested to create remote path: ./random_videos
The requested directory to create was found on OneDrive - skipping creating the directory: ./random_videos
The parent for this path is in the local database - adding requested path (./random_videos) to database
OneDrive Client requested to create remote path: ./Top Folder
The requested directory to create was not found on OneDrive - creating remote directory: ./Top Folder
Successfully created the remote directory ./Top Folder on OneDrive
OneDrive Client requested to create remote path: ./Top Folder/asdfasdf
The requested directory to create was not found on OneDrive - creating remote directory: ./Top Folder/asdfasdf
Successfully created the remote directory ./Top Folder/asdfasdf on OneDrive
Uploading new file ./Top Folder/asdfasdf/qwerksdjfg.txt ... 
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:02                                                                                                                    
done.
Remaining free space on OneDrive: 1088627723035
Uploading new file ./Top Folder/asdfasdfs.txt ... 
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:00                                                                                                                    
done.
Remaining free space on OneDrive: 1088627723022
```

Upload created folder & files on account drive, not shared folder drive:

Incorrect Folder and File Placement


### With PR:
**Dry-Run**
```
(dmd-2.093.1)[alex@centos7full onedrive-pr1127]$ ./onedrive --confdir '~/.config/onedrive-business/' --synchronize --sync-shared-folders --upload-only --verbose --resync --dry-run
Using 'user' Config Dir: /home/alex/.config/onedrive-business/
Using 'system' Config Dir: 
Configuration file successfully loaded
DRY-RUN Configured. Output below shows what 'would' have occurred.
Deleting the saved status ...
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Opening the item database ...
All operations will be performed in: /home/alex/OneDriveBusiness
Application version: v2.4.6-21-ge666d53
Account Type: business
Default Drive ID: b!bO8V7s9SSk6r7mWHpIjURotN33W1W2tEv3OXV_oFIdQimEdOHR-1So7CqeT1MfHA
Default Root ID: 01WIXGO5V6Y2GOVW7725BZO354PWSELRRZ
Remaining Free Space: 1088627721331
Fetching details for OneDrive Root
OneDrive Root does not exist in the database. We need to add it.
Added OneDrive Root to the local database
Initializing the Synchronization Engine ...
Syncing changes from local path only - NOT syncing data changes from OneDrive ...
Uploading differences of ~/OneDriveBusiness
Processing .
The directory has not changed
Processing .
The directory has not changed
Processing Top Folder
The directory has not changed
Uploading new items of ~/OneDriveBusiness
OneDrive Client requested to create remote path: ./random_files
The requested directory to create was found on OneDrive - skipping creating the directory: ./random_files
The parent for this path is in the local database - adding requested path (./random_files) to database
OneDrive Client requested to create remote path: ./random_images
The requested directory to create was found on OneDrive - skipping creating the directory: ./random_images
The parent for this path is in the local database - adding requested path (./random_images) to database
OneDrive Client requested to create remote path: ./random_videos
The requested directory to create was found on OneDrive - skipping creating the directory: ./random_videos
The parent for this path is in the local database - adding requested path (./random_videos) to database
OneDrive Client requested to create remote path: ./Top Folder/asdfasdf
The requested directory to create was not found on OneDrive - creating remote directory: ./Top Folder/asdfasdf
Successfully created the remote directory ./Top Folder/asdfasdf on OneDrive
Uploading new file ./Top Folder/asdfasdf/qwerksdjfg.txt ... done.
Uploading new file ./Top Folder/asdfasdfs.txt ... done.
```

`/Top Folder/` not created, because it exists, and is a OneDrive Shared Business Folder

**Actual**
```
(dmd-2.093.1)[alex@centos7full onedrive-pr1127]$ ./onedrive --confdir '~/.config/onedrive-business/' --synchronize --sync-shared-folders --upload-only --verbose --resync
Using 'user' Config Dir: /home/alex/.config/onedrive-business/
Using 'system' Config Dir: 
Configuration file successfully loaded
Deleting the saved status ...
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Opening the item database ...
All operations will be performed in: /home/alex/OneDriveBusiness
Application version: v2.4.6-21-ge666d53
Account Type: business
Default Drive ID: b!bO8V7s9SSk6r7mWHpIjURotN33W1W2tEv3OXV_oFIdQimEdOHR-1So7CqeT1MfHA
Default Root ID: 01WIXGO5V6Y2GOVW7725BZO354PWSELRRZ
Remaining Free Space: 1088627721331
Fetching details for OneDrive Root
OneDrive Root does not exist in the database. We need to add it.
Added OneDrive Root to the local database
Initializing the Synchronization Engine ...
Syncing changes from local path only - NOT syncing data changes from OneDrive ...
Uploading differences of ~/OneDriveBusiness
Processing .
The directory has not changed
Processing .
The directory has not changed
Processing Top Folder
The directory has not changed
Uploading new items of ~/OneDriveBusiness
OneDrive Client requested to create remote path: ./random_files
The requested directory to create was found on OneDrive - skipping creating the directory: ./random_files
The parent for this path is in the local database - adding requested path (./random_files) to database
OneDrive Client requested to create remote path: ./random_images
The requested directory to create was found on OneDrive - skipping creating the directory: ./random_images
The parent for this path is in the local database - adding requested path (./random_images) to database
OneDrive Client requested to create remote path: ./random_videos
The requested directory to create was found on OneDrive - skipping creating the directory: ./random_videos
The parent for this path is in the local database - adding requested path (./random_videos) to database
OneDrive Client requested to create remote path: ./Top Folder/asdfasdf
The requested directory to create was not found on OneDrive - creating remote directory: ./Top Folder/asdfasdf
Successfully created the remote directory ./Top Folder/asdfasdf on OneDrive
Uploading new file ./Top Folder/asdfasdf/qwerksdjfg.txt ... 
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:01                                                                                                                    
done.
Uploading new file ./Top Folder/asdfasdfs.txt ... 
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:00                                                                                                                    
done.
```

All files / folders correctly uploaded to OneDrive Business Shared Folder location rather than account root:

Correct File Placement

**Review by norbusan — APPROVED** [review]
Thanks for validation, the additional changes look fine, too.

**Pull request merged**
