### PR TITLE
Refactor API implementation

### PR DESCRIPTION
**Pull request by JC-comp**
### Summary
Currently, the role of `OneDriveApi`, `OneDriveWebhook`, `CurlEngine` and `SyncEngine` lacks clean code design, including request handling, cleanup process and error management. This results in duplicate code that makes reading and future maintenance difficult. This PR aims to address this issue through a refactoring of the corresponding classes.
### Changes
1. Move all socket cleanup and request setup to `CurlEngine`: No need to manually clean up for every api call
2. Move all onedrive error handle (currently only 429 is implemented) to `OneDriveApi`: No need to manually handle retry/reauth... for every api call
3. Reuse of get/post/patch...: simple one-liner for each api call
4. Move `OneDriveWebhook` out of `OneDriveApi`: webhook does not belong to api instance
5. Interactive authorisation: Prompt to retry instead of a force quit to prevent loss of progress
6. Fix graceful shutdown and cleanup issue mentioned https://github.com/abraunegg/onedrive/discussions/2521#discussioncomment-7337864
7. Organize endpoints into dictionaries: improve scalability and make access easier.
8. Remove disabling SSL verification as an automated workaround: explicit user consent should be obtained as this is a sever security issue

### How Has This Been Tested?
- Authorisation flow
- Download/Upload/Move/Delete/Subscription related api calls
- Interrupt and normal exit

### What is still missing?
- Further cleanup of duplicate code in api callers
- Add support for disabling SSL verification as a configuration flag
- Add support for handling expired unauthorized response
- Thorough testing for each endpoints and functions

### CODE REVIEW

**Comment by abraunegg** [comment]
@JC-comp 
Thankyou for your effort and contribution here - however *please* can you hit pause on thus sort of major change.

Right now I am trying to focus on getting a current solid alpha --> beta sorted .. and this sort of change would have been beneficial ~6 months ago.

Post getting everything *solid* with the code as-it-is, potentially could look at this - so please hit pause on this work for the moment.

**Comment by JC-comp** [comment]
@abraunegg 
Sure, if now is not a suitable time, feel free to close these PRs, I will continue optimizing on my own fork. 
However, I still strongly recommend conducting this kind of refactoring as soon as possible. The current code design leaves the client susceptible to bugs and inconsistencies that increases maintenance challenges. And besides the local-first mode, which can take half a day for a full scan, there are several performance concerns that can be easily addressed. These solutions can reduce resource usage or help streamline the codebase at the same time.
In any case, thank you for your time, and I'll check back in a few months to see if there are any updates on this.

**Comment by abraunegg** [comment]
@JC-comp 
Regarding this whole PR, please can you:

> 4. Move OneDriveWebhook out of OneDriveApi: webhook does not belong to api instance

Pull this out of this PR and make this a separate PR. I agree this should not be in where it is today, and ideally should be in its own .d file given that it is it's own class.

> 5. Interactive authorisation: Prompt to retry instead of a force quit to prevent loss of progress

Remove this. I understand why, however the application should not re-try | reprompt. Please remove this.

> 6. Fix graceful shutdown and cleanup issue mentioned https://github.com/abraunegg/onedrive/discussions/2521#discussioncomment-7337864

Remove this.

> 8. Remove disabling SSL verification as an automated workaround: explicit user consent should be obtained as this is a sever security issue

Remove this as this was only implemented as a workaround to local testing. This has already been removed.

Once these items are done, please re-baseline your PR with that of the current 'alpha-5' branch, or submit a new PR that combines  points 1, 2, 3 only.

Please also split out 7 to a separate PR as I am not sure as to why that change is needed and needs to be handled separatly.

**Comment by JC-comp** [comment]
@abraunegg 
I believe it would be more appropriate to close this PR. I'll review the changes against the latest alpha-5 version to confirm their necessity and functionality, I'll create a new PR if needed.

Additionally, I'm curious if any of these changes align with your upcoming plans on the whiteboard. I would prefer to leave these adjustments to you for better code consistency while focusing on performance and bug-related issues..

**Comment by abraunegg** [comment]
@JC-comp 
> Additionally, I'm curious if any of these changes align with your upcoming plans on the whiteboard.

Refactoring for maintainability and better error handling is on the whiteboard

**Comment by JC-comp** [comment]
Closing as all items have corresponding new PRs.

**Comment by abraunegg** [comment]
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

**Pull request closed without merging**
