### PR TITLE
Update 'skip_dir' handling to check against OneDrive new downloads

### PR DESCRIPTION
**Pull request by abraunegg**
* Add check for directories to match skip_dir entries for OneDrive objects to download
* Update logging as to why a OneDrive object was skipped

### CODE REVIEW

**Comment by norbusan** [comment]
Hi
thanks, it is much better now, but not perfect. I guess the `|` construct seems to be not correctly treated. Furthermore, the logging is strange: every file/dir is mentioned for both skip_*:

First for the bug:
```
Skipping item - excluded by skip_dir config: Desktop
Skipping item - excluded by skip_file config: Desktop
Skipping item - excluded by skip_dir config: dokumente.txt
Skipping item - excluded by skip_file config: dokumente.txt
Skipping item - excluded by skip_dir config: RP_und_STN_Erklaerung.pdf
Skipping item - excluded by skip_file config: RP_und_STN_Erklaerung.pdf
Skipping item - excluded by skip_dir config: RP_und_STN_Erklaerung.doc
Skipping item - excluded by skip_file config: RP_und_STN_Erklaerung.doc
Skipping item - excluded by skip_dir config: RP_Erkl_ErziehBer.pdf
Skipping item - excluded by skip_file config: RP_Erkl_ErziehBer.pdf
Skipping item - excluded by skip_dir config: RP_Formular_MJ.doc
Skipping item - excluded by skip_file config: RP_Formular_MJ.doc
Skipping item - excluded by skip_dir config: RP_Formular_MJ.pdf
Skipping item - excluded by skip_file config: RP_Formular_MJ.pdf
```

The first is a directory, the rest are files there. So it seems that `Desktop` is correctly skipped.

But:
```
Creating directory: GpsMaps/Maps/SwissMap25
Creating directory: GpsMaps/Maps/SwissMap25/SM25 - 2 - Jura
Creating directory: GpsMaps/Maps/SwissMap25/SM25 - 3 - Bern
Creating directory: GpsMaps/Maps/SwissMap25/SM25 - 4 - Wallis
Creating directory: GpsMaps/Maps/SwissMap25/SM25 - 5 - Zentralschweiz
...
```
which is not good, shouldn't that be excluded with

```
$ ./onedrive --display-config
onedrive version                    = v2.2.5-44-g4c3b959
Config path                         = /home/norbert/.config/onedrive
Config file found in config path    = true
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /home/norbert/OneDrive
Config option 'skip_dir'            = GpsMaps/Maps|GpsMaps/MapPrograms|Desktop
Config option 'skip_file'           = desktop.ini|metadata.db-journal
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notif_changes'   = 5
Config option 'log_dir'             = /var/log/onedrive/
Selective sync configured           = false
```

(BTW, why does it still say 2.2.5?)

**Comment by abraunegg** [comment]
@norbusan 
OK - the logging is a problem - should get that fixed, and only check the file exclusion **IF** directory is not matched.

As for version - unsure - if your cleaning the PR directory before build. I use the following script to build a PR:
```
#!/bin/bash

PR=419

rm -rf ./onedrive-pr${PR}
git clone https://github.com/abraunegg/onedrive.git onedrive-pr${PR}
cd onedrive-pr${PR}
git fetch origin pull/${PR}/head:pr${PR}
git checkout pr${PR}
source ~/dlang/dmd-2.085.0/activate
make clean; make PKGCONFIG=0 NOTIFICATIONS=0;
deactivate
```

**Comment by norbusan** [comment]
converning version: aah `make clean` does not remove the `version` file, not good ... we should add version to the PHONY targets.

What remains is the problem that not all files are ignored although they should be...

**Comment by abraunegg** [comment]
> converning version: aah `make clean` does not remove the `version` file, not good ... we should add version to the PHONY targets.
> 
> What remains is the problem that not all files are ignored although they should be...

make clean should delete version .. something else to fix / add

**Comment by abraunegg** [comment]
@norbusan 
See if the logging now works better for the exclusions

**Comment by norbusan** [comment]
Ok, I see the problem: I have partial path like `GpsMaps/Maps`  in my config, which worked in the `skip_file` setting, but it stopped in the `skip_dir`.

Looking at the generated regexp, I see:
```
"^GpsMaps\\/Maps$|^GpsMaps\\/MapPrograms$|^Desktop$"
```
which makes me think that the `\\/` part in the directory separator is the *culprit* in my case. Removing the three lines doing this in `util.c:wild2regexp` makes the sync behave correctly.

What is your intention with this code?
```
               case '/':
                       str ~= "\\/";
                       break;
```
?

**Comment by norbusan** [comment]
First of all, logging is now ok, thanks.

Concerning the incorrect download, I see that it only happens with partial path like `a/b`, in my case `GpsMaps/Maps` etc.

Looking at the generated regexp (wild2regexp) I get in my case 
```
"^GpsMaps\\/Maps$|^GpsMaps\\/MapPrograms$|^Desktop$"
```
which then is checked with `name.matchFirst(dirmask)` in `isDirNameExcluded`. It **should** match, but I guess the `\\/` part is wrong - at lesat I thought so. But removing the quoting in utils.c still does the downloading part, so I am at loss why that does not match.

**Comment by norbusan** [comment]
Ahh, and that is interesting: I added to `bool isDirNameExcluded(string name)` the following code:
```
                writeln("DEBUG: checking whether name is excluded = ", name);
```
and what I get is:
```
DEBUG: checking whether name is excluded = isos0000ch0503_Attrib.vdb
DEBUG: checking whether name is excluded = pima0025ju0509.blb
Downloading file GpsMaps/Maps/SwissMap25/SM25 - 2 - Jura/data/map/pima0025ju0509/pima0025ju0509.blb ... 
```

So the basename only is checked, not the full path ... something is fishy here

**Comment by abraunegg** [comment]
@norbusan 
That most likely is due to the fact that the 'name' part being checked comes from the JSON being sent from OneDrive as the name of item, it does not have the full path at all. That is contained elsewhere in the item's JSON from OneDrive.

**Comment by norbusan** [comment]
Then I wonder how directory exclusion works at all :-D I try to look into it, but boarding my plane in 15min ...

**Comment by norbusan** [comment]
I moved my issue to a separate PR.

**Pull request merged**
