### PR TITLE
Remove duplicate code for error output functions and enhance error logging output

### PR DESCRIPTION
**Pull request by abraunegg**
* Remove duplicate code for the following functions:
  - displayOneDriveErrorMessage
  - displayFileSystemErrorMessage

### CODE REVIEW

**Comment by abraunegg** [comment]
@norbusan 
Would be great if you can test / run this PR in your environment to see if there are any further negative impacts based on the logging function consolidation. I don't foresee any issue .. but .. without some extensive testing, I cannot be 100% sure.

Any feedback you can give on this one would be greatly appreciated.

**Comment by abraunegg** [comment]
When a timeout occurs now:
```
Processing 204 OneDrive items to ensure consistent local state
Processing 204 OneDrive items to ensure consistent local state
ERROR: OneDrive returned an error with the following message:
  Error Message: Timeout was reached on handle 2A2B770
  Calling Function: perform()
ERROR: OneDrive returned an error with the following message:
  Error Message: There was a timeout in accessing the Microsoft OneDrive service - Internet connectivity issue?
  Error Message: There was a timeout in accessing the Microsoft OneDrive service - Internet connectivity issue?
```

**Comment by norbusan** [comment]
@abraunegg will try to look into it over the weekend!

**Comment by abraunegg** [comment]
@norbusan 
Also I am in two minds re this:
```
	// Where in the code was this error generated
	log.error("  Calling Function: ", callingFunction);
```

In this state, when an error is generated, and logs provided, we know where the issue occurred regardless of if `--verbose` is being used or not

If we change this to:
```
	// Where in the code was this error generated
	log.vlog("  Calling Function: ", callingFunction);
```

This will only get displayed when `--verbose` or `--verbose --verbose` is used.

I am inclined that if an error message is generated, provide as much detail as possible, even if to the end user one line may not make too much sense.

Thoughts?

**Comment by abraunegg** [comment]
@norbusan 
Logs from long running overnight, non verbose mode:
```
Sync with OneDrive is complete
Starting a sync with OneDrive
Syncing changes from OneDrive ...
Sync with OneDrive is complete
ERROR: OneDrive returned an error with the following message:
  Error Message: Timeout was reached on handle 17C3770
  Calling Function: perform()
ERROR: OneDrive returned an error with the following message:
  Error Message: Timeout was reached on handle 17C3770
  Calling Function: perform()
ERROR: OneDrive returned an error with the following message:
  Error Message: Timeout was reached on handle 17C3770
  Calling Function: perform()
ERROR: OneDrive returned an error with the following message:
  Error Message: Timeout was reached on handle 17C3770
  Calling Function: perform()
ERROR: OneDrive returned an error with the following message:
  Error Message: Timeout was reached on handle 17C3770
  Calling Function: perform()
ERROR: OneDrive returned an error with the following message:
  Error Message: Timeout was reached on handle 17C3770
  Calling Function: perform()
ERROR: OneDrive returned an error with the following message:
  Error Message: Timeout was reached on handle 17C3770
  Calling Function: perform()
ERROR: OneDrive returned an error with the following message:
  Error Message: Timeout was reached on handle 17C3770
  Calling Function: perform()
ERROR: OneDrive returned an error with the following message:
  Error Message: Timeout was reached on handle 17C3770
  Calling Function: perform()
ERROR: OneDrive returned an error with the following message:
  Error Message: Timeout was reached on handle 17C3770
  Calling Function: perform()
ERROR: OneDrive returned an error with the following message:
  Error Message: Timeout was reached on handle 17C3770
  Calling Function: perform()
ERROR: OneDrive returned an error with the following message:
  Error Message: Timeout was reached on handle 17C3770
  Calling Function: perform()
ERROR: OneDrive returned an error with the following message:
  Error Message: Timeout was reached on handle 17C3770
  Calling Function: perform()
ERROR: OneDrive returned an error with the following message:
  Error Message: Timeout was reached on handle 17C3770
  Calling Function: perform()
ERROR: OneDrive returned an error with the following message:
  Error Message: Timeout was reached on handle 17C3770
  Calling Function: perform()
ERROR: OneDrive returned an error with the following message:
  Error Message: Timeout was reached on handle 17C3770
  Calling Function: perform()
ERROR: OneDrive returned an error with the following message:
  Error Message: Timeout was reached on handle 17C3770
  Calling Function: perform()
ERROR: OneDrive returned an error with the following message:
  Error Message: Timeout was reached on handle 17C3770
  Calling Function: perform()
ERROR: OneDrive returned an error with the following message:
  Error Message: Timeout was reached on handle 17C3770
  Calling Function: perform()
ERROR: OneDrive returned an error with the following message:
  Error Message: Timeout was reached on handle 17C3770
  Calling Function: perform()
ERROR: OneDrive returned an error with the following message:
  Error Message: Timeout was reached on handle 17C3770
  Calling Function: perform()
ERROR: OneDrive returned an error with the following message:
  Error Message: There was a timeout in accessing the Microsoft OneDrive service - Internet connectivity issue?
  Error Message: There was a timeout in accessing the Microsoft OneDrive service - Internet connectivity issue?
  Error Message: There was a timeout in accessing the Microsoft OneDrive service - Internet connectivity issue?
Internet connectivity to Microsoft OneDrive service has been restored

ERROR: OneDrive returned an error with the following message:
  Error Message: HTTP request returned status code 401 (Unauthorized)
  Calling Function: applyDifferences()
Starting a sync with OneDrive
Syncing changes from OneDrive ...
Sync with OneDrive is complete
Starting a sync with OneDrive
Syncing changes from OneDrive ...
```

**Comment by norbusan** [comment]
Code looks absolute reasonable, compiles and runs. I am giving it a night from now and see what I see in my logs.

**Comment by norbusan** [comment]
Concerning vlog versus error, I don't think it makes a huge difference in the huge bunch of output that is anyway generated, so guess both ways is fine.

**Comment by norbusan** [comment]
Last for today: concerning duplication, I would really like to see (and I will take a look at it) a simplification of the http return code handling. These infinite switches in various places really shouldn't be there mor ethan once.

**Comment by abraunegg** [comment]
@norbusan 
Updated this PR to handle `Timeout was reached on handle` in the same way as other timeouts - makes for a cleaner experience:
```
Configuration file successfully loaded
Notification (dbus) server not available, disabling
Configuring Global Azure AD Endpoints
Initializing the Synchronization Engine ...
Initializing monitor ...
OneDrive monitor interval (seconds): 300
ERROR: OneDrive returned an error with the following message:
  Error Message: There was a timeout in accessing the Microsoft OneDrive service - Internet connectivity issue?
  Error Message: There was a timeout in accessing the Microsoft OneDrive service - Internet connectivity issue?
  Error Message: There was a timeout in accessing the Microsoft OneDrive service - Internet connectivity issue?
  Error Message: There was a timeout in accessing the Microsoft OneDrive service - Internet connectivity issue?
  Error Message: There was a timeout in accessing the Microsoft OneDrive service - Internet connectivity issue?
  Error Message: There was a timeout in accessing the Microsoft OneDrive service - Internet connectivity issue?
  Error Message: There was a timeout in accessing the Microsoft OneDrive service - Internet connectivity issue?
  Error Message: There was a timeout in accessing the Microsoft OneDrive service - Internet connectivity issue?
  Error Message: There was a timeout in accessing the Microsoft OneDrive service - Internet connectivity issue?
  Error Message: There was a timeout in accessing the Microsoft OneDrive service - Internet connectivity issue?
  Error Message: There was a timeout in accessing the Microsoft OneDrive service - Internet connectivity issue?
  Error Message: There was a timeout in accessing the Microsoft OneDrive service - Internet connectivity issue?
  Error Message: There was a timeout in accessing the Microsoft OneDrive service - Internet connectivity issue?
Internet connectivity to Microsoft OneDrive service has been restored
```

**Comment by norbusan** [comment]
So seems to run fine, I get lots of
```
Dec 08 09:31:40 bulldog onedrive[2403153]: Syncing changes from OneDrive ...
Dec 08 09:31:40 bulldog onedrive[2403153]: ERROR: OneDrive returned an error with the following message:
Dec 08 09:31:40 bulldog onedrive[2403153]:   Error Message: HTTP request returned status code 400 (Bad Request)
Dec 08 09:31:40 bulldog onedrive[2403153]:   Error Reason:  Invalid API or resource
Dec 08 09:31:40 bulldog onedrive[2403153]:   Calling Function: applyDifferences()
Dec 08 09:31:41 bulldog onedrive[2403153]: ERROR: OneDrive returned an error with the following message:
Dec 08 09:31:41 bulldog onedrive[2403153]:   Error Message: HTTP request returned status code 400 (Bad Request)
Dec 08 09:31:41 bulldog onedrive[2403153]:   Error Reason:  Invalid API or resource
Dec 08 09:31:41 bulldog onedrive[2403153]:   Calling Function: applyDifferences()
Dec 08 09:31:46 bulldog onedrive[2403153]: ERROR: OneDrive returned an error with the following message:
Dec 08 09:31:46 bulldog onedrive[2403153]:   Error Message: HTTP request returned status code 400 (Bad Request)
Dec 08 09:31:46 bulldog onedrive[2403153]:   Error Reason:  Invalid API or resource
Dec 08 09:31:46 bulldog onedrive[2403153]:   Calling Function: applyDifferences()
Dec 08 09:31:46 bulldog onedrive[2403153]: ERROR: OneDrive returned an error with the following message:
Dec 08 09:31:46 bulldog onedrive[2403153]:   Error Message: HTTP request returned status code 400 (Bad Request)
Dec 08 09:31:46 bulldog onedrive[2403153]:   Error Reason:  Invalid API or resource
Dec 08 09:31:46 bulldog onedrive[2403153]:   Calling Function: applyDifferences()
Dec 08 09:31:46 bulldog onedrive[2403153]: Sync with OneDrive is complete
```
like stuff, but no other error messages over night. Guess I can approve ;-)

**Review by norbusan — APPROVED** [review]

**Review by norbusan — COMMENTED** [review]
Hmmm, running from the command line I now get:
```
[~] onedrive --synchronize
Configuration file successfully loaded
Configuring Global Azure AD Endpoints
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...

ERROR: OneDrive returned an error with the following message:
  Error Message: HTTP request returned status code 400 (Bad Request)
  Error Reason:  Invalid API or resource
  Calling Function: applyDifferences()
Syncing this OneDrive Personal Shared Folder: カメラ ロール

ERROR: OneDrive returned an error with the following message:
  Error Message: HTTP request returned status code 400 (Bad Request)
  Error Reason:  Invalid API or resource
  Calling Function: applyDifferences()
Uploading differences of ~/OneDrive
Uploading new items of ~/OneDrive

ERROR: OneDrive returned an error with the following message:
  Error Message: HTTP request returned status code 400 (Bad Request)
  Error Reason:  Invalid API or resource
  Calling Function: applyDifferences()
Syncing this OneDrive Personal Shared Folder: カメラ ロール

ERROR: OneDrive returned an error with the following message:
  Error Message: HTTP request returned status code 400 (Bad Request)
  Error Reason:  Invalid API or resource
  Calling Function: applyDifferences()
```

**Comment by abraunegg** [comment]
> Hmmm, running from the command line I now get:
> 
> ```
> [~] onedrive --synchronize
> Configuration file successfully loaded
> Configuring Global Azure AD Endpoints
> Initializing the Synchronization Engine ...
> Syncing changes from OneDrive ...
> 
> ERROR: OneDrive returned an error with the following message:
>   Error Message: HTTP request returned status code 400 (Bad Request)
>   Error Reason:  Invalid API or resource
>   Calling Function: applyDifferences()
> Syncing this OneDrive Personal Shared Folder: カメラ ロール
> 
> ERROR: OneDrive returned an error with the following message:
>   Error Message: HTTP request returned status code 400 (Bad Request)
>   Error Reason:  Invalid API or resource
>   Calling Function: applyDifferences()
> Uploading differences of ~/OneDrive
> Uploading new items of ~/OneDrive
> 
> ERROR: OneDrive returned an error with the following message:
>   Error Message: HTTP request returned status code 400 (Bad Request)
>   Error Reason:  Invalid API or resource
>   Calling Function: applyDifferences()
> Syncing this OneDrive Personal Shared Folder: カメラ ロール
> 
> ERROR: OneDrive returned an error with the following message:
>   Error Message: HTTP request returned status code 400 (Bad Request)
>   Error Reason:  Invalid API or resource
>   Calling Function: applyDifferences()
> ```

Interesting ... can you email me a verbose debug https (`--verbose --verbose --debug-https`) log of this ... 

`HTTP request returned status code 400 (Bad Request)` means that something in the input path to the API call is failing .. nothing was changed in what was being called ... so wonder what is tripping that up.

**Comment by abraunegg** [comment]
@norbusan 
OK .. I get the same issue - in 'master', using a personal account:
```
(dmd-2.093.1)[alex@centos7full onedrive]$ ./onedrive --confdir '~/.config/onedrive-personal/' --synchronize 
Configuration file successfully loaded
Configuring Global Azure AD Endpoints
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...

ERROR: OneDrive returned an error with the following message:
  Error Message: HTTP request returned status code 400 (Bad Request)
  Error Reason:  Invalid API or resource
Uploading differences of ~/OneDrivePersonal
Uploading new items of ~/OneDrivePersonal

ERROR: OneDrive returned an error with the following message:
  Error Message: HTTP request returned status code 400 (Bad Request)
  Error Reason:  Invalid API or resource
(dmd-2.093.1)[alex@centos7full onedrive]$ 
```

Looks like we have a OneDrive API change

**Comment by norbusan** [comment]
> Looks like we have a OneDrive API change

Ohh great!!! I thought it was only me ;-) It worked through the night and started failing in the morning.

**Comment by abraunegg** [comment]
> > Looks like we have a OneDrive API change
> 
> Ohh great!!! I thought it was only me ;-) It worked through the night and started failing in the morning.

It looks to be coming from 'deltaLink' ... MS broke something:
```
[DEBUG] deltaLink: https://graph.microsoft.com/v1.0/drives('66d53be8a5056eca')/items('66D53BE8A5056ECA!101')/microsoft.graph.delta(token='aTE09NjM3NDI5NzI5OTIxODA7SUQ9NjZE...
```

**Comment by abraunegg** [comment]
@norbusan 
Opened a case here: https://github.com/OneDrive/onedrive-api-docs/issues/1408

**Comment by abraunegg** [comment]
@norbusan 
Updated the error output as well to now include other details which are needed when reporting an API issue:
```
ERROR: OneDrive returned an error with the following message:
  Error Message:    HTTP request returned status code 400 (Bad Request)
  Error Reason:     Invalid API or resource
  Error Date:       2020-12-08T04:22:30
  Error Request ID: 1c2fa442-dd14-4302-8197-9bc3439b86db
  Calling Function: applyDifferences()
```

**Review by norbusan — APPROVED** [review]

**Pull request merged**
