### PR TITLE
Fix: skip_file configuration doesn't handle spaces or specified directory paths (Issue #52)

### PR DESCRIPTION
**Pull request by abraunegg**
Pull request to resolve skip_file configuration doesn't handle spaces or specified directory paths (Issue #52)

### CODE REVIEW

**Comment by robertjf** [comment]
You will want to pull in the changes to selective.d as well to fix it fully

**Comment by abraunegg** [comment]
Yep .. have not finished the cherry pick .. have some other things here to do work wise

**Comment by robertjf** [comment]
I'm thinking we may want to refactor this at some stage - the method naming is a little confusing - thoughts

**Comment by abraunegg** [comment]
There are a lot of things in the codebase that are confusing .. future work

**Comment by abraunegg** [comment]
Tested this PR for resolving the original issue #52:

```
OneDrive Client requested to create remote path: ./Documents
The requested directory to create was not found on OneDrive - creating remote directory: ./Documents
Successfully created the remote directory ./Documents on OneDrive
Skipping item - path excluded: ./Documents/OneNote Notebooks
Applying changes of Path ID: <redacted>
```

Can you confirm when testing this PR ?

```
git clone https://github.com/abraunegg/onedrive.git; 
cd onedrive; 
git fetch origin pull/57/head:pr57; 
git checkout pr57
make
make install
```

**Comment by robertjf** [comment]
yep, confirmed with testing

**Pull request merged**
