### PR TITLE
Add --no-remote-delete flag to docker entrypoint

### PR DESCRIPTION
**Pull request by thegoncalomartins**
I think it would be a great improvement if the official base docker image for `onedrive` provided the possibility of having the `--no-remote-delete` flag.

### CODE REVIEW

**Comment by abraunegg** [comment]
@thegoncalomartins 
Thanks for the PR - however enabling a feature - that is only meant to be active if the user enables it - by default is 100% not a good idea.

Please can you update this PR so that this is *not* active by default

**Review by abraunegg — CHANGES_REQUESTED** [review]
Please do not make this active by default - that is a very bad idea

**Comment by thegoncalomartins** [comment]
> @thegoncalomartins Thanks for the PR - however enabling a feature - that is only meant to be active if the user enables it - by default is 100% not a good idea.
> 
> Please can you update this PR so that this is _not_ active by default

Thanks for the quick feedback.
PR Updated.

**Comment by abraunegg** [comment]
@thegoncalomartins 
If you could add this to Podman.md as well from a documentation perspective that would be great

**Comment by abraunegg** [comment]
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

**Pull request merged**
