### PR TITLE
Add --display-sync-status to Docker entrypoint

### PR DESCRIPTION
**Pull request by lulor**

### CODE REVIEW

**Comment by abraunegg** [comment]
@lulor 
Adding `--display-sync-status` to a Docker is not a wise idea.

It is a command that runs then exits the application - 100% unwise in a Docker scenario.

As such I am rejecting this PR, as all this will do is keep bouncing your Docker container if enabled.

**Comment by lulor** [comment]
@abraunegg
Sorry about that, I'm only using the client in Docker and the container actually keeps running..
I didn't realize it was a one-shot command though, I agree it's not really suitable for Docker in this case

**Comment by abraunegg** [comment]
@lulor 
In v2.4 if you are using `--monitor` (which Docker uses) and add `--display-sync-status` - yes it will continue (I have tested it) - however v2.4 is also now frozen (no changes) due to v2.5 development. I consider this to be a bug in v2.4 to allow that.

In v2.5 when using `--monitor` and `--display-sync-status` together, the sync status is ignored. When you use `--display-sync-status` it will display and exit.

**Comment by abraunegg** [comment]
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

**Pull request closed without merging**
