### PR TITLE
onedrive client version v2.5.0-alpha-3

### PR DESCRIPTION
**Pull request by abraunegg**
* Development tree for onedrive client version v2.5.0-alpha-3

### CODE REVIEW

**Comment by abraunegg** [comment]
@Lyncredible

Please can you test this 'alpha-3' version?

This is an uplift of your original code (as per v2.4.25) and does not include any of your changes as per #2516

If you can confirm that this current uplift works, could you then please uplift this PR with your changes from #2516 ?

That would be greatly appreciated.

**Comment by Lyncredible** [comment]
@abraunegg Resync is done. Webhook is working, but it seems something is wrong with the resync detection logic. It asks me to do a resync again when I restarted it without `--resync`.
<details>
  <summary>Log for successful resync</summary>

```
Base Args: --monitor
# Launching onedrive
Reading configuration file: /onedrive/conf/config
Configuration file successfully loaded

The usage of --resync will delete your local 'onedrive' client state, thus no record of your current 'sync status' will exist.
This has the potential to overwrite local versions of files with perhaps older versions of documents downloaded from OneDrive, resulting in local data loss.
If in doubt, backup your local data before using --resync

Are you sure you wish to proceed with --resync? [Y/N] y

The item database is incompatible, re-creating database table structures
Deleting the saved application sync status ...
Configuring Global Azure AD Endpoints
Sync Engine Initialised with new Onedrive API instance
OneDrive synchronisation interval (seconds): 86400
Initialising filesystem inotify monitoring ...
Performing initial syncronisation to ensure consistent local state ...
Initializing subscription for updates ...
Webhook: handled validation request
Created new subscription <REDACTED> with expiration: <REDACTED>
Starting a sync with Microsoft OneDrive
Fetching items from the OneDrive API for Drive ID: <REDACTED> ..........................................................................................................................................................................................................................................................
Processing <REDACTED> applicable changes and items received from Microsoft OneDrive ...........................................................................................................
Performing a database consistency and integrity check on locally stored data ...
Scanning the local file system '/onedrive/data' for new data to upload ...
Performing a last examination of the most recent online data within Microsoft OneDrive to complete the reconciliation process
Fetching items from the OneDrive API for Drive ID: <REDACTED> ..
No additional changes or items that can be applied were discovered while processing the data received from Microsoft OneDrive
Sync with Microsoft OneDrive is complete
Initializing subscription for updates ...
Webhook: handled validation request
Created new subscription <REDACTED> with expiration: <REDACTED>
^CGot termination signal, performing clean up
Shutting down DB connection and merging temporary data
```
</details>

<details>
<summary>Log for a subsequent run without `--resync`</summary>

```
usermod: no changes
Base Args: --monitor
# Launching onedrive
Reading configuration file: /onedrive/conf/config
Configuration file successfully loaded

An application configuration change has been detected where a --resync is required
```
</details>

**Comment by abraunegg** [comment]
@Lyncredible 
> Log for a subsequent run without `--resync`

Can you run the application in `--verbose` mode ??

Need to understand what is triggering the `--resync` here post reading in the configuration file .. something is changing ... need to understand what it is and why the application thinks it has changed.

Also all this logic is 100% different to v2.4.x series - so if you ran v2.4.x inbetween ... could be an indicator as to where the issue is occurring from.

**Comment by Lyncredible** [comment]
@abraunegg 
Resync was deemed necessary because it detected `sync_dir` override from CLI:
```
# The log statement was changed to also log the two different values
[DEBUG] sync_dir: CLI override of config file option, --resync needed, config = ~/OneDrive, CLI = /onedrive/data
```

The configured value is hard-coded since I never specified `sync_dir` in my own config file:
https://github.com/abraunegg/onedrive/blob/77c294ba0c29f445d082b4e6d50ce361ead16fed/src/config.d#L29

The CLI override comes from the `entrypoint.sh` in the default docker image:
https://github.com/abraunegg/onedrive/blob/77c294ba0c29f445d082b4e6d50ce361ead16fed/contrib/docker/entrypoint.sh#L27

I now have specified `sync_dir` in my own config file to match the CLI override as a workaround, but this requires another resync since the config file has changed...

**Comment by Lyncredible** [comment]
@abraunegg 
I hit a new issue where access token renewal fails:
```
AADSTS9000410: Malformed JSON.
ERROR: You will need to issue a --reauth and re-authorise this client to obtain a fresh auth token.
```

This is because the request to renew token is sent with the `Content-Type: application/json` header, but the token endpoint requires `Content-Type: application/x-www-form-urlencoded`. The wrong header is sent because `http.clearRequestHeaders()` is no longer called in `scope(exit) {}` in `OneDriveApi.post()` (or other methods like `OneDriveApi.patch()`.

For example, I see `http.clearRequestHeaders()` being called in master branch:
https://github.com/abraunegg/onedrive/blob/4a60654e3f2c21f4822b9a00aa1d1e23375e7303/src/onedrive.d#L1392-L1401

But it is not found in `onedrive-v2.5.0-alpha-3`:
https://github.com/abraunegg/onedrive/blob/77c294ba0c29f445d082b4e6d50ce361ead16fed/src/onedrive.d#L1427-L1434

Why was the line removed?

**Comment by abraunegg** [comment]
@Lyncredible 
> For example, I see http.clearRequestHeaders() being called in master branch

OK - thats a gap & bug in 'alpha-3' that needs to be corrected. Will look at that shortly.

Also - just to keep comments / feedback in the same place, could you provide feedback here: https://github.com/abraunegg/onedrive/discussions/2521 rather than in this PR that would be great.

**Comment by abraunegg** [comment]
@Lyncredible 
> Resync was deemed necessary because it detected sync_dir override from CLI:

OK .. thanks for this feedback .. essentially as 'sync_dir' is now being correctly being picked up as a change, this is what is happening. I am going to have to look at this a little closer on how to work around this for containerised environments.

**Comment by abraunegg** [comment]
@Lyncredible 
>For example, I see http.clearRequestHeaders() being called in master branch:
> ...
> Why was the line removed?

Should be fixed by: https://github.com/abraunegg/onedrive/pull/2520/commits/5fddd7457069383d9f3587ddf59595441de1e4da

**Comment by abraunegg** [comment]
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

**Pull request closed without merging**
