### PR TITLE
Detect the need for --resync when config changes

### PR DESCRIPTION
**Pull request by abraunegg**
* Add config & sync_list hash checks to assist in determining if a resync is required

### CODE REVIEW

**Comment by abraunegg** [comment]
**Progress**
- [x] Detect config file change
- [x] Detect sync_list file change
- [ ] Detect actual config file option change rather than file has changed
- [ ] Detect config change when passed in as argument (--skip-file, --syncdir)

**Comment by abraunegg** [comment]
@norbusan 
Needs to be extensively tested / regression tested. What I have tested is:
* app defaults - OK
* update config file - sync_dir - OK - says needs --resync
* update config file - skip_file - OK - says needs --resync
* update config file - skip_dir - OK - says needs --resync
* update via CLI - sync_dir - OK - says needs --resync
* update via CLI - skip-file - OK - says needs --resync
* update via CLI - skip-dir - OK - says needs --resync

I have a feeling tho, when NO config file is used and a user is using --sync-dir or --skip-file or --skip-dir to override application defaults, then this should be allowed with no --resync ... as .. my feeling is that they are doing a manual sync with that specific config for a specific reason. Should this 'block' or be allowed .. or have "another" switch that is basically "bypass safeguards" eg --force ???

**Comment by norbusan** [comment]
I agree that if the user passes in cli options then no warning should be necessary. And, in addition, as you mentioned, a `--force` is probably necessary, because even the change in config file can be on purpose.

**Comment by abraunegg** [comment]
> I agree that if the user passes in cli options then no warning should be necessary. And, in addition, as you mentioned, a `--force` is probably necessary, because even the change in config file can be on purpose.

Removed the application default vs CLI input checks

**Comment by norbusan** [comment]
Thanks!
What is your opinion concerning `--force`?

**Comment by abraunegg** [comment]
@norbusan 
working on an update that negates that - by checking specifically the 4 config options that if they change necessitate --resync ... thus --force not needed if just updating a config option where --resync is not needed

**Comment by abraunegg** [comment]
@norbusan 
Code should be good to go for review, needs extensive regression testing & test case validation

**Comment by abraunegg** [comment]
Test Cases Performed
[PR_617_test_cases.xlsx](https://github.com/abraunegg/onedrive/files/3489299/PR_617_test_cases.xlsx)

**Comment by norbusan** [comment]
@abraunegg I am still travelling with my kid, so I am having a hard time testing this before say end of the week (around 18 August). I can look at the code and see if I realize something strange, but detailed testing I can't manage now.

**Comment by abraunegg** [comment]
@norbusan 
No problem :) when you can get to it is fine. I have a few ideas for #458 I am going to investigate in the meantime.

**Comment by abraunegg** [comment]
@norbusan 
Any update in looking at this PR? Thoughts?

**Comment by norbusan** [comment]
@abraunegg I looked through the code and it seems fine. I could approve now but I normally do my own testing, but that would need to wait till beginning of next week when I am back in Japan.
Other than the personal testing (which you have done, too) I am fine with it.

**Comment by abraunegg** [comment]
**notes:** PR #625 needs to be committed to master first, then this fixed / rebased

**Comment by norbusan** [comment]
@abraunegg I agree, we can postpone this for a version 2.4 maybe

**Comment by abraunegg** [comment]
@norbusan 
Was thinking this was OK for v2.3.9 but the big delete one (where the sync stops - #621) - leave that for v2.4.0 as it is a breaking change vs config checking

**Comment by norbusan** [comment]
Yes, sorry, mixed that up ... you are right (jet lag still shows its signs, in particular after a bad night)

**Pull request merged**
