### PR TITLE
Fix for extra encoded quotation marks surrounding Docker environment variables

### PR DESCRIPTION
**Pull request by NigelVanHattum**
… variables

### CODE REVIEW

**Comment by NigelVanHattum** [comment]
Fix for #2318

**Comment by abraunegg** [comment]
@NigelVanHattum 
Thanks for proposing this fix. I will need to test locally to ensure that nothing else breaks in regards to this change - it shouldnt however need to validate.

**Comment by NigelVanHattum** [comment]
@abraunegg Yes, please do so

**Comment by abraunegg** [comment]
@NigelVanHattum 
Please can you test this updated PR in your environment

**Comment by NigelVanHattum** [comment]
@abraunegg 
I still see some issues. So please don't merge yet. I agree your solution is a lot nicer than mine. 

I will investigate this issue a bit further. I will keep you updated during the week.

**Comment by NigelVanHattum** [comment]
It seems to be ignoring the config section for the single dir. I added some logging surrounding the specific folder. (Added the logging at monitor.d#71 (before the addRecursive function). The quotes are still present here.

**Comment by NigelVanHattum** [comment]
If I'm correctly, your change rewrites the value received from the config file. The single-dir is a commandline arg, so I think that's why it has no effect.

**Comment by abraunegg** [comment]
@NigelVanHattum 
Please can you test the updated PR - `onedrive v2.4.23-17-ge746bfb`

**Comment by NigelVanHattum** [comment]
@abraunegg Just tested it, this works! 

Could it be that the original value gets stored inside an array? And that it tries to extract it, hence adding the quotes in case there are multiple values in it?

**Comment by abraunegg** [comment]
> @abraunegg Just tested it, this works!
> 
> Could it be that the original value gets stored inside an array? And that it tries to extract it, hence adding the quotes in case there are multiple values in it?

The values are stored in separate value items.

**Comment by abraunegg** [comment]
@NigelVanHattum 
Just confirming - that this PR in its current state resolves your issue?

**Comment by NigelVanHattum** [comment]
Correct, with your latest change the single-dir sync in docker works as expected.

**Comment by abraunegg** [comment]
@NigelVanHattum 
Thanks - will merge this into 'master'

**Comment by abraunegg** [comment]
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

**Pull request merged**
