### PR TITLE
config options for command line arguments

### PR DESCRIPTION
**Pull request by norbusan**
This PR gives most command line arguments a respective config file option. It also moves the command line parsing of most arguments but the `confdir` into the config.d module. All values are saved into the `config` module and `main` only uses `getValueXXX` instead of separate variables.

Future work (not implemented by now):
- allow for categorization of config variable: default value, default value but explicitly set in the config file, changed from default value
- show config would only show actually set variables, and report if one is different form the default

### CODE REVIEW

**Comment by norbusan** [comment]
This is marked as WIP since it needs thorough testing of functionality.

**Comment by abraunegg** [comment]
verbose was not verbose ...
```
[alex@centos7full onedrive-pr389]$ ./onedrive --confdir '~/.config/onedrive-personal' --display-config
onedrive version                    = v2.2.5-43-g8b7d772
Config path                         = ~/.config/onedrive-personal
Config file found in config path    = false
Config option 'sync_dir'            = /home/alex/OneDrivePersonal
Config option 'skip_file'           = ~*
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 30
Config option 'min_notif_changes'   = 5
Config option 'log_dir'             = /var/log/onedrive/
Selective sync configured           = false
[alex@centos7full onedrive-pr389]$ ./onedrive --confdir '~/.config/onedrive-personal' --synchronize --verbose
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Uploading file ./Test/.fubar ... done.
Uploading file ./.abcde/hello ... done.
Processing 5 changes
[alex@centos7full onedrive-pr389]$ 
```

**Comment by norbusan** [comment]
Thanks, fixed with latest commit

**Comment by norbusan** [comment]
@abraunegg Just a comment about the current status: the recent big changes, in particular dry-run, and added config options have thrown this PR completely off the brink for now, I need to redo it.

I still would be interested in hearing from you reading through the current set of changes whether you think this is a good idea to redo in this way.

The basic structure is that we in `main` only use getop to check for `confdir` and `version`, move the whole initialization stuff into `cfg` from `main`, and convert all the command line options and conf dir options to `cfg.getValueBool` and `cfg.getValueString` and `cfg.getValueLong` calls. This reduces the long list of variables in `main`. Furthermore, most command line args can be also set in the config file, and if both are present, the command line argument wins over config file.

**Comment by abraunegg** [comment]
@norbusan 
Totally agree with the direction of this PR

**Comment by norbusan** [comment]
Hi @abraunegg 
I have now merged and fixed most obvious errors. I think we can start testing this PR more seriously to iron out the surely remaining bugs in conversion to config file support settings.

**Comment by abraunegg** [comment]
@norbusan 
Is it worth updating the current 'default' config file with all the 'defaults as well?

**Comment by abraunegg** [comment]
@norbusan 
The current build is also failing:
```
echo v2.3.0-17-g8997b08 > version
dmd -w -g -ofonedrive -O  -L-lcurl -L-lsqlite3 -L-ldl -J. src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d src/progress.d
src/main.d(240): Error: undefined identifier `synchronize`
src/main.d(240): Error: `monitor` is not an expression
make: *** [onedrive] Error 1
The command "bash -ex .travis-ci.sh" exited with 2.
```

**Comment by norbusan** [comment]
Somehow currently the builders are broken
```
Err:72 http://dl.bintray.com/apache/cassandra 39x/main amd64 Packages
  502  Bad Gateway [IP: 52.89.158.216 80]
Get:119 http://ppa.launchpad.net/pollinate/ppa/ubuntu trusty/main i386 Packages [430 B]
Err:76 http://dl.bintray.com/apache/cassandra 39x/main i386 Packages
  502  Bad Gateway [IP: 52.89.158.216 80]
```

**Comment by abraunegg** [comment]
Yep ... my .travis update should fix it

**Comment by abraunegg** [comment]
@norbusan 
Works well & functions as required.

Probably will need to be updated depending on #433 & #442 being merged into 'master'

**Comment by norbusan** [comment]
@abraunegg I have merged this, and updated the two PR #433 and #442

**Pull request merged**
