### PR TITLE
Release files for 2.4.8

### PR DESCRIPTION
**Pull request by abraunegg**
* Release files for 2.4.8

### CODE REVIEW

**Comment by abraunegg** [comment]
@norbusan 
If you are able to review the doc changes here for flow / applicability that would be greatly appreciated. I may make some further changes, so this PR is still a WIP for the moment.

**Review by norbusan — APPROVED** [review]
Changes and docs look fine, but I am not sure whether the part of sharing between Windows and Linux is actually sufficient to be like that... never tried it.

**Comment by abraunegg** [comment]
@norbusan 

> Changes and docs look fine, but I am not sure whether the part of sharing between Windows and Linux is actually sufficient to be like that... never tried it.


The Windows side of things is OK - I have validated that. It assumes a dual-boot, and you are also mounting the data from your Windows partition or storing your Windows OneDrive folder on another drive / folder / partition that is easily accessible / non-encrypted (via BitLocker). The information is enough - so that if you see zero byte files, thats how it can be fixed.

Updated the PR, I think this is good now for final review, will push out the release later on today when I get time.

**Review by norbusan — APPROVED** [review]

**Comment by norbusan** [comment]
> The Windows side of things is OK - I have validated that. It assumes a dual-boot, and you are also mounting the data from your Windows partition or storing your Windows OneDrive folder on another drive / folder / partition that is easily accessible / non-encrypted (via BitLocker). The information is enough - so that if you see zero byte files, thats how it can be fixed.

Cool, guess I have to try that myself instead of keeping long exception lists to separate the two onedrives.

**Pull request merged**
