### PR TITLE
fix broken autoconf code for --enable-XXX options

### PR DESCRIPTION
**Pull request by norbusan**
Currently, using --disable-XXX is not working, because the
arguments of AC_ARG_ENABLE are only for presence versus absence,
not for positive versus negative. Fix this by properly using
AS_IF on the value set.

### CODE REVIEW

**Comment by norbusan** [comment]
Hi Alex @abraunegg 
Sorry for this stupid oversight. Currently, doing 
```
./configure --disable-completions
```
does still activate them. Ok, by default they are disabled, so when **nothing** is passed in it works as disabled. But as soon as something is passed in (--disable-XXX, --enable-XXX, --enable-XXX=foobar) it is always considered enabled.

Not sure whether we should make a release specifically for this fix (and maybe the other PR).

**Comment by abraunegg** [comment]
@norbusan 
Best to fix it fully in on PR

**Comment by norbusan** [comment]
@abraunegg what do you mean with "fully"? Adding docs to `INSTALL.md` or anything else? The current PR already fixes all `--enable-XXX` instances.

**Comment by abraunegg** [comment]
@norbusan 
Ahh ok .. misread then as you mention --disable still acts if --enable ..

**Comment by norbusan** [comment]
Ah, sorry, the quote meant the status *before* the PR ;-) The PR fixes all issues I have found.

**Pull request merged**
