### PR TITLE
Update handling of 'remote' folder designation as 'root' items (Issue #323, #324, #331)

### PR DESCRIPTION
**Pull request by abraunegg**
Issue #323 extreme debugging

### CODE REVIEW

**Comment by abraunegg** [comment]
Prior to (potentially a OneDrive API change being rolled out), a 'change' record for the 'remote' folder consisted of the following:
```
        "id": "BC7D88EC1F539DCF!107",
        "name": "3A",
        "parentReference": {
		"driveId": "bc7d88ec1f539dcf",
		"driveType": "personal"
	},
```
**Note:** Only 'driveId' & 'driveType' present.

In issues #323 & #324 however, all of these same reference items contained an 'id':
```
	"id": "7EF2789E900D35F3!105",
	"name": "DESIGN _ BRASIL",
	"parentReference": {
		"driveId": "7ef2789e900d35f3",
		"driveType": "personal",
		"id": "7EF2789E900D35F3!101"
	},
```
As such, because of the presence of 'id' the 'change' was being flagged as an actual item to sync. rather than being the database 'glue' to tie the local OneDrive entry to the remotely shared item.

The real fix for this is https://github.com/abraunegg/onedrive/pull/328/commits/37b3c76b6eea93f3c11242beda43ee024975ff8d however this PR incoporates all of the work in #327 as well, plus adding in a whole lot of extra debugging that helped get to the bottom of this

**Comment by norbusan** [comment]
Hi @abraunegg 
can we please go step by step ... this PR is based on top of `extra-debugging-and-http-downgrade` with some changes. I think the code is fine, but I would like to go one by one, if you don't mind...

**Comment by abraunegg** [comment]
@norbusan 
Agree - this PR needs cleanup which I will be doing shortly

**Comment by norbusan** [comment]
Hi @abraunegg 
so for now I wait with review and testing ...

**Comment by abraunegg** [comment]
@norbusan 
Cleanup of code / changes all done - testing & review should be OK to proceed with this PR

**Pull request merged**
