### PR TITLE
Performance improvement

### PR DESCRIPTION
**Pull request by JC-comp**
Changes
* Replace `skippedItems` with an efficient search ds
* Fix resync required check for skip_file
* Exclude generated systemd files from codebase
* Fix item path computation 
_https://github.com/abraunegg/onedrive/discussions/2506#discussioncomment-7293603_

### CODE REVIEW

**Comment by abraunegg** [comment]
@JC-comp 
* Change [d04914e](https://github.com/abraunegg/onedrive/pull/2515/commits/d04914e26e9a506699a58f05f02445b02159801d) looks OK to me, however it only looks at 'skippedItems' .. there are potentially a number of other string arrays throughout the code that might gain a performance boost from this as well.
  * Do you have any evidence to compare the performance boost from this change?
* Change [1367a53](https://github.com/abraunegg/onedrive/pull/2515/commits/1367a53d4ad562b70df9161f128f665d59240426) fairly standard
* Change [5e96c87](https://github.com/abraunegg/onedrive/pull/2515/commits/5e96c87bc9a34891307ace1ae0237cd0ea33de78) I do not think is correct here .. as, if this was the case, *ALL* of the other check where a configuration change has taken place would be broken as well .. so I do not think this is correct - sorry.
* Changes [ee31561](https://github.com/abraunegg/onedrive/pull/2515/commits/ee31561ea047e749fecbfdfae9223e98dc8e8b1c) and [47311af](https://github.com/abraunegg/onedrive/pull/2515/commits/47311af76f74d79a87beeaf8500baa8095b0caa7) again I am not too sure why this change is needed for things to work for you
  * Do you have some *explicit* evidence here before the change & post these changes as to what was broken, and now fixed
  * Changing from a double quotation mark to single is also *highly* odd - as double quotes are being used everywhere .... and nothing appears broken .. so evidence please.

**Comment by JC-comp** [comment]
> Change [d04914e](https://github.com/abraunegg/onedrive/pull/2515/commits/d04914e26e9a506699a58f05f02445b02159801d) looks OK to me, however it only looks at 'skippedItems' .. there are potentially a number of other string arrays throughout the code that might gain a performance boost from this as well.
> Do you have any evidence to compare the performance boost from this change?

This is an improvement for _https://github.com/abraunegg/onedrive/discussions/2506#discussioncomment-7269462_.
If we have many items to skip, the entire growing list must be traversed for each item. And I haven't encountered any other performance issues similar to this so far.

> Change [5e96c87](https://github.com/abraunegg/onedrive/pull/2515/commits/5e96c87bc9a34891307ace1ae0237cd0ea33de78) I do not think is correct here .. as, if this was the case, ALL of the other check where a configuration change has taken place would be broken as well .. so I do not think this is correct - sorry.

This is the only case that requires additional handling so far, as there is a predefined `defaultSkipFile` that will be concatanate with the user defined `skip_file`. if we don't do the same thing to backup lines, check will _always_ fail.

https://github.com/abraunegg/onedrive/blob/6db484cdad332e9b351e1fef7d59080637c195f9/src/config.d#L757


> Changes [ee31561](https://github.com/abraunegg/onedrive/pull/2515/commits/ee31561ea047e749fecbfdfae9223e98dc8e8b1c) and [47311af](https://github.com/abraunegg/onedrive/pull/2515/commits/47311af76f74d79a87beeaf8500baa8095b0caa7) again I am not too sure why this change is needed for things to work for you

* Please check _https://github.com/abraunegg/onedrive/discussions/2506#discussioncomment-7296627_

> Changing from a double quotation mark to single is also highly odd - as double quotes are being used everywhere .... and nothing appears broken .. so evidence please.

As we are comparing char not string here.
```
src/sync.d(3280): Error: incompatible types for `(newItemPath[0]) == ("/")`: `immutable(char)` and `string`
```

**Comment by abraunegg** [comment]
> if we don't do the same thing to backup lines, check will always fail.

Not exactly .. the *whole* point here is code is checking:

* config file (actual) as it has been loaded, the *actual* 'skip_file' entry in that config file
* config backup (what is now the prior config file), the *actual* 'skip_file' entry in that backup config file

The aim of the test is to determine if the actual entry of that item is different. If you start adding then the 'default' entry to the comparison, then this will be throwing things out.

This was tested and validated many many many times and the existing code as far as it has been tested & triggering the right application response (to perform a --resync) when this is changed, works.

If you do not believe so - please provide application log evidence.

**Comment by abraunegg** [comment]
> As we are comparing char not string here.

Are you trying yo 'fix' the code to fix your 'broken' sync_list configuration file ??

**Comment by JC-comp** [comment]
> The aim of the test is to determine if the actual entry of that item is different. If you start adding then the 'default' entry to the comparison, then this will be throwing things out.

```
$ onedrive --version
v2.5.0-alpha-2 GitHub version: v2.4.25-29-g6db484c

$ cat config 
skip_file = "test"
monitor_interval = "399"

$ onedrive --sync
...

Sync with Microsoft OneDrive is complete

$ cat config 
skip_file = "test"
monitor_interval = "599" // changed, should not trigger a resync

$ onedrive --sync -vv
...
Application configuration file has been updated, checking if --resync needed
...
[DEBUG] Backup Config Key: skip_file
[DEBUG] skip_file was modified since the last time the application was successfully run, --resync required
[DEBUG] Backup Config Line: skip_file = "test"
...
```

A change in `monitor_interval` should not trigger a resync, and the reason is just what I've stated.

**Comment by JC-comp** [comment]
> Are you trying yo 'fix' the code to fix your 'broken' sync_list configuration file ??

It used to work in pervious version, and if I understand correctly from the doc, the config used in _https://github.com/abraunegg/onedrive/discussions/2506#discussioncomment-7293603_ should also work as well. 

https://github.com/abraunegg/onedrive/blob/4a60654e3f2c21f4822b9a00aa1d1e23375e7303/docs/USAGE.md?plain=1#L279-L280

And the reason why v2.4 works is that the computed path from db does not have the leading slash, while currently the computed path from ondrive json have a leading slash. So it fails the prefix check.

https://github.com/abraunegg/onedrive/blob/6db484cdad332e9b351e1fef7d59080637c195f9/src/clientSideFiltering.d#L258-L263

Is the design logic to force a wildcard matching and disable all prefix checking started from root?

**Comment by JC-comp** [comment]
Closing as there is better solution for the main request. If other bugs and changes require new PR/Issue, please let me know.

**Comment by abraunegg** [comment]
@JC-comp 
Please keep this open as I am cherry picking | merging these items already in, as this merges cleanly online - its not merging cleanly locally as I am probably 20-30 changes ahead of where 'alpha-2' is.

Reason is - I develop locally, run tests, validate, retest, repeat - *only* then push to the PR

**Comment by abraunegg** [comment]
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

**Pull request closed without merging**
