### PR TITLE
Catch database assertion when item path cannot be calculated

### PR DESCRIPTION
**Pull request by abraunegg**
* Catch database assertion when item path cannot be calculated

### CODE REVIEW

**Comment by abraunegg** [comment]
**Without PR:**
```
Configuration file successfully loaded
Configuring Global Azure AD Endpoints
Initializing the Synchronization Engine ...
Initializing monitor ...
OneDrive monitor interval (seconds): 300
core.exception.AssertError@src/itemdb.d(391): Assertion failure
----------------
??:? _d_assertp [0x5581f21c1cf5]
??:? immutable(char)[] itemdb.ItemDatabase.computePath(const(char)[], const(char)[]) [0x5581f2173805]
??:? void sync.SyncEngine.uploadDifferences(ref const(itemdb.Item)) [0x5581f219f700]
??:? void sync.SyncEngine.uploadDirDifferences(ref const(itemdb.Item), const(immutable(char)[])) [0x5581f219fb2a]
??:? void sync.SyncEngine.uploadDifferences(ref const(itemdb.Item)) [0x5581f219f97e]
??:? void sync.SyncEngine.uploadDirDifferences(ref const(itemdb.Item), const(immutable(char)[])) [0x5581f219fb2a]
??:? void sync.SyncEngine.uploadDifferences(ref const(itemdb.Item)) [0x5581f219f97e]
??:? void sync.SyncEngine.uploadDirDifferences(ref const(itemdb.Item), const(immutable(char)[])) [0x5581f219fb2a]
??:? void sync.SyncEngine.uploadDifferences(ref const(itemdb.Item)) [0x5581f219f97e]
??:? void sync.SyncEngine.uploadDirDifferences(ref const(itemdb.Item), const(immutable(char)[])) [0x5581f219fb2a]
??:? void sync.SyncEngine.uploadDifferences(ref const(itemdb.Item)) [0x5581f219f97e]
??:? void sync.SyncEngine.uploadDirDifferences(ref const(itemdb.Item), const(immutable(char)[])) [0x5581f219fb2a]
??:? void sync.SyncEngine.uploadDifferences(ref const(itemdb.Item)) [0x5581f219f97e]
??:? void sync.SyncEngine.scanForDifferencesDatabaseScan(const(immutable(char)[])) [0x5581f219ecbd]
??:? void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool, long, bool, bool, bool, bool, monitor.Monitor) [0x5581f2183d44]
??:? _Dmain [0x5581f2182bb0]
std.net.curl.CurlException@std/net/curl.d(4402): A libcurl function was given a bad argument on handle null
----------------
??:? pure @safe void std.exception.bailOut!(std.net.curl.CurlException).bailOut(immutable(char)[], ulong, scope const(char)[]) [0x5581f222999a]
??:? pure @safe bool std.exception.enforce!(std.net.curl.CurlException).enforce!(bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x5581f222990b]
??:? void std.net.curl.Curl._check(int) [0x5581f21ff8af]
??:? void std.net.curl.Curl.clear(etc.c.curl.CurlOption) [0x5581f21ffc5a]
??:? void std.net.curl.HTTP.clearRequestHeaders() [0x5581f21fe98f]
??:? void onedrive.OneDriveApi.shutdown() [0x5581f2187c48]
??:? _Dmain [0x5581f21831ec]
```

**With PR:**
```
Configuration file successfully loaded
Configuring Global Azure AD Endpoints
Initializing the Synchronization Engine ...
Initializing monitor ...
OneDrive monitor interval (seconds): 300
ERROR: A database consistency issue has been caught. A --resync is needed to rebuild the database.

```

**Review by norbusan — COMMENTED** [review]
Hmmm, since all the cases of assertion check from `computePath` are the same, wouldn't it make sense to move the check itself into the `computePath` function, and `exit` there? 

I agree that having helper functions only doing asserts, but in this case the outcome will always be a log and exit.

**Comment by abraunegg** [comment]
> Hmmm, since all the cases of assertion check from `computePath` are the same, wouldn't it make sense to move the check itself into the `computePath` function, and `exit` there?
> 
> I agree that having helper functions only doing asserts, but in this case the outcome will always be a log and exit.

Yes it should be a function which is done now

**Review by norbusan — APPROVED** [review]
Thanks, that looks much better!

**Pull request merged**
