### PR TITLE
Installation of doc files, addition of man page

### PR DESCRIPTION
**Pull request by norbusan**
This pull requests changes the installation routine to install useful files into `$(PREFIX)/share/doc/onedrive`, as well as adding a man page.

### CODE REVIEW

**Comment by abraunegg** [comment]
@norbusan 
Thanks - will review over the weekend.

**Comment by abraunegg** [comment]
@norbusan 
Is there a cleaner way to perform the following:
```
onedrive.1: onedrive.1.in
	sed "s|@VERSION@|$(shell cat version)|g" onedrive.1.in > onedrive.1.ver
	sed "s|@DATE@|$(shell date +'%B %Y')|g" onedrive.1.ver > onedrive.1.date
	sed "s|@DOCDIR@|$(DOCDIR)|g" onedrive.1.date > onedrive.1
```

This would then allow the manpage to be dynamically updated with the version information / month it was built ... 

Thoughts?

**Comment by adudek** [comment]
After some small research I found nifty little templating solution for shell: https://stackoverflow.com/questions/6214743/create-new-file-from-templates-with-bash-script/30872526#30872526

Hope this helps

**Comment by norbusan** [comment]
Thanks for merging.
If you are interested I can look into autoconf-ing the Makefile, that would allow replacing the variables on the fly.
If you prefer not to use autoconf, I will look into a templating solution that does not require additional stuff as far as possible.

**Comment by abraunegg** [comment]
@adudek, @norbusan 
Not too fussed on how it is achieved - rather right now say for a major release, I am already 'manually' updating 2 files:
* gentoo contrib
* pacman

To add in the man page date / version becomes the 3rd - so it would be worth having a mechanism that updates the man page automatically, so it keeps the 'manual' changes on a version release to a minimum.

**Comment by norbusan** [comment]
Ok, I think all of them can be treated with autoconf, which would in addition provide the standard interface via `./configure --prefix=... --libdir=...` etc. I will look into it to get rid of all manual updates but a call to `reautoconf`.

**Pull request merged**
