### PR TITLE
Implement Feature: Multiple skip_dir & skip_file configuration rules

### PR DESCRIPTION
**Pull request by abraunegg**
* Implement feature: Multiple skip_dir & skip_file configuration rules

### CODE REVIEW

**Comment by abraunegg** [comment]
**Config:**
```
...
#
sync_dir = "~/OneDrivePersonal"
skip_file = "~*|.~*|*.tmp|*.swp"
monitor_interval = "30"
skip_dir = ".dropbox.cache|.Images|.Music"
# log_dir = "/var/log/onedrive/"
# drive_id = ""
...
# azure_ad_endpoint = ""
skip_dir = "second_entry"
```
**Without PR:**
```
./onedrive --confdir '~/.config/onedrive-personal/' --display-config
Configuration file successfully loaded
config file has been updated, checking if --resync needed
onedrive version                       = v2.4.5-13-g1364f36
Config path                            = /home/alex/.config/onedrive-personal/
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/alex/OneDrivePersonal
Config option 'skip_dir'               = second_entry
Config option 'skip_file'              = ~*|.~*|*.tmp|*.swp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 30
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = true
sync_list contents:
# Include all files and folders under /random_files/
random_files/
!random_files/temp*
Business Shared Folders configured     = false
```

The second entry overrides the first.

**With PR:**
```
./onedrive --confdir '~/.config/onedrive-personal/' --display-config
Configuration file successfully loaded
config file has been updated, checking if --resync needed
onedrive version                       = v2.4.5-14-gb24f491
Config path                            = /home/alex/.config/onedrive-personal/
Config file found in config path       = true
Config option 'check_nosync'           = false
Config option 'sync_dir'               = /home/alex/OneDrivePersonal
Config option 'skip_dir'               = .dropbox.cache|.Images|.Music|second_entry
Config option 'skip_file'              = ~*|.~*|*.tmp|*.swp
Config option 'skip_dotfiles'          = false
Config option 'skip_symlinks'          = false
Config option 'monitor_interval'       = 30
Config option 'min_notify_changes'     = 5
Config option 'log_dir'                = /var/log/onedrive/
Config option 'classify_as_big_delete' = 1000
Config option 'sync_root_files'        = false
Selective sync 'sync_list' configured  = true
sync_list contents:
# Include all files and folders under /random_files/
random_files/
!random_files/temp*
Business Shared Folders configured     = false

```
The second entry is merged with the first

**Review by norbusan — DISMISSED** [review]

**Comment by norbusan** [comment]
Might be interesting to make this a feature throughout the configuration settings, there are some others I guess that could profit from the same code

**Comment by abraunegg** [comment]
> Might be interesting to make this a feature throughout the configuration settings, there are some others I guess that could profit from the same code

The only one that makes sense is 'skip_file' - happy to update the PR to include that one.

**Review by norbusan — APPROVED** [review]
Great, thanks!

**Pull request merged**
