### PR TITLE
Improved Dockerfiles

### PR DESCRIPTION
**Pull request by abraunegg**
* Rework PR #1733 pulling in dockerfile changes + updating documentation
* Drop GitHub Docker actions yaml

### CODE REVIEW

**Comment by abraunegg** [comment]
@MarcelCoding 
Can you validate | check these updated Docker files and documentation?

**Comment by MarcelCoding** [comment]
Fedora armv7:
```
onedrive_1    | Aborting from core/time.d(2106) MonoTimeImpl!(ClockType.normal) failed to get the frequency of the system's monotonic clock.usermod: no changes
onedrive_1    | Base Args: --monitor
onedrive_1    | # We are performing a --resync
onedrive_1    | # Adding --resync
onedrive_1    | # Launching onedrive
onedrive_1    | Configuration file successfully loaded
onedrive_1    | Deleting the saved application sync status ...
onedrive_1    | Configuring Global Azure AD Endpoints
onedrive_1    | Initializing the Synchronization Engine ...
onedrive_1    | Initializing monitor ...
onedrive_1    | OneDrive monitor interval (seconds): 300
```

Debian armv7:
```
onedrive_1    | Base Args: --monitor
onedrive_1    | # We are performing a --resync
onedrive_1    | # Adding --resync
onedrive_1    | # Launching onedrive
onedrive_1    | Configuration file successfully loaded
onedrive_1    | Deleting the saved application sync status ...
onedrive_1    | Cannot connect to Microsoft OneDrive Service - Network Connection Issue
onedrive_1    |
onedrive_1    | ERROR: Microsoft OneDrive API returned an error with the following message:
onedrive_1    |   Error Message:    SSL peer certificate or SSH remote key was not OK on handle 17C9280
onedrive_1    |   Calling Function: testNetwork()
onedrive_1    |
onedrive_1    | Unable to reach Microsoft OneDrive API service at this point in time, re-trying network tests
```

At least it is not the time again, where the time isn't working on newer docker images on rpi.
```
pi@pi-nistkasten:~/docker $ sudo docker run --rm -it debian:bullseye date
Fri Jan 14 14:05:33 UTC 2022
pi@pi-nistkasten:~/docker $ sudo docker run --rm -it fedora:35 date
Fri Jan 14 14:05:40 UTC 2022
```

Do you have any guesses? I did not find anything on google.

(debian, fedora & alpine on amd64 and arm64 are working)

**Comment by MarcelCoding** [comment]
I just noticed that the are now two versions of rpi os: https://www.raspberrypi.com/software/operating-systems/
I am currently using the old one (buster) but the is a new one (bullseye). Maybe the bullseye version is working? Do you have an idle rpi - I currently don't (I can't wipe one that I am currently using in "production")

**Comment by abraunegg** [comment]
@MarcelCoding 
> Do you have any guesses? I did not find anything on google. - the old rpi image is working

RE: Fedora ARMv7 - most likely it is because of LDC itself, which is usually lagging as an RPM, which is why, the older Dockerfiles performs a yum install direct from the DMD repositories rather the actual repositories. Perhaps it is better to follow this approach.

RE: Debian ARMv7 - this most likely is an issue with the base system certificates being loaded on that version of Debian for ARM

> I am currently using the old one (buster) but the is a new one (bullseye). Maybe the bullseye version is working? Do you have an idle rpi - I currently don't (I can't wipe one that I am currently using in "production")

I do not have any RPI hardware. All prior RPI testing was done via QEMU to emulate 'Raspberry Pi 2 Model B' and 'Raspberry Pi 3 Model B+' on x86_64 virtual machine under VMware ESXi. You cannot use QEMU to emulate a RPI 4.

I have found 'Rasbian' to be a very fickle OS in this scenario as well - but given the layers of virtualisation and emulation I am not surprised. At least my zSeries stuff done in similar fashion has no issues.

**Comment by MarcelCoding** [comment]
I don't quite get what you mean with Fedora. It is working on amd64 and arm64 only on ARMv7 (rpi) it is not working. Do you mean I would use DMD in Fedora? DMD is only awailable for amd64 and i368. I actually have a rpi 4,but running with an amd64 varient of Ubuntu, but because it is the 8gb model where a 32 bit system can't use the full memory. (this is also the system where I tested amd64)

**Comment by abraunegg** [comment]
@MarcelCoding 

> I don't quite get what you mean with Fedora. It is working on amd64 and arm64 only on ARMv7 (rpi) it is not working. Do you mean I should use DMD in Fedora? DMD is only awailable for amd64 and i368.

The issue here is the following:
* Use the latest available DMD or LDC package for all architectures except for ARMv7 (armhf)
* For all ARMv7 / armhf architectures - LDC 1.17.0 is the *only* version that can be used - no other version (and this is the last armhf version the LDC folk put out)

I will see what I can do with the updated files to keep the above true

**Comment by MarcelCoding** [comment]
Ok now I get it, I am going to update the Fedora Dockerfile.

**Comment by MarcelCoding** [comment]
I was able to fix the ssl problem on debian: https://github.com/MarcelCoding/onedrive-docker/commit/745902fe2ed0e2df6029625842fc1e1f047488f9
I also dropped the support for armhf on fedora.
You can find all working dockerfiles here: https://github.com/MarcelCoding/onedrive-docker

**Comment by MarcelCoding** [comment]
Maybe you forgot it, but you still have to add the fix for ssl on rpi in Debian. (and somewhere in the docs you have written buster but it is bullseye)

**Comment by abraunegg** [comment]
@MarcelCoding 
If you can test these Dockerfiles out that would be greatly appreciated.

The Debian ones should all be built on Debian 11

**Comment by MarcelCoding** [comment]
I just tried bullseye instead of buster and now I am getting the same error as on fedora:
```
onedrive_1    | Aborting from core/time.d(2131) MonoTimeImpl!(ClockType.normal) failed to get the frequency of the system's monotonic clock.usermod: no changes
```
I think fedora and bullseye are using too new versions of glibc or something that the old ldc verserion that I have to use on armhf is not compatible.

**Comment by abraunegg** [comment]
@MarcelCoding 
It might be that the Debian ARM images then need to be built with Buster / Use Buster - but the others use Bullseye.

That is going to cause issues in ~8 months when Debian 10 goes EOL.

**Comment by MarcelCoding** [comment]
Then copy the Dockerfile one for armhf and one for arm64 and amd64 and change one to bullseye and the other to buster. I tested both already.

**Comment by MarcelCoding** [comment]
Do you know if the ldc team is aware of this Issue? Maybe we should tell them something, that they are prepared.

**Comment by abraunegg** [comment]
@MarcelCoding 
If possible could you help validate the updated PR + documentation for accuracy before this is merged into 'master'

**Comment by MarcelCoding** [comment]
I think you forget to mention the rpi version.

**Comment by abraunegg** [comment]
> I think you forget to mention the rpi version.

Where abouts ? Its listed in the doc .. where else is it missed?

**Comment by MarcelCoding** [comment]
Nvm, i forgot about that you have to build the rpi image yourself.

**Comment by abraunegg** [comment]
No worries - hopefully then these Dockerfiles are 100% OK .. will push this to 'master' now

**Pull request merged**
