### PR TITLE
Docker buildfiles for onedrive service

### PR DESCRIPTION
**Pull request by adudek**
As requested https://github.com/skilion/onedrive/pull/433#issuecomment-439715859

### CODE REVIEW

**Comment by abraunegg** [comment]
@adudek 
Yes - the Travis CI build & test appears broken - something inside Travis CI has changed which is breaking outbound communication to OneDrive service (#245), but it also has shown up a bug that I am in the process of fixing - as it should not crash that way.

When the Travis CI build's were working 100%, PR's like your's would fail anyway due to the use of an escaped secret inside Travis CI that only works when a build is pushed when using my github account.

**Comment by abraunegg** [comment]
Thanks for all the changes.

I plan on merging this post the 2.2.0 release which will I will be finalising in the next hour. This gives me a good chance test the docker integration against 2.2.0 and ensure everything is working as it should

**Comment by abraunegg** [comment]
@adudek 
Will run this through some testing locally - however this all looks good to me

**Comment by abraunegg** [comment]
@adudek 
Can you update your pull request based on the latest master?

**Comment by adudek** [comment]
Pushed changes to my repo... gitlab has problems refreshing pull request? Creating new pr

**Pull request closed without merging**
