### PR TITLE
autoconf based build system

### PR DESCRIPTION
**Pull request by norbusan**
Convert the build system to autoconf (without automake). By dropping the (anyway nearly superfluous) automake dependency the build errors should be gone, and the `Makefile` is much more readable and close to the current status. This is an updated and improved version of https://github.com/abraunegg/onedrive/pull/284

Release management:
- update the version number in `configure.ac`
- run `autoconf` : this will generate `configure`, `onedrive.1`, `pacman/PKGBUILD`, `spec/onedrive.spec` (these are all files in the git repo and thus need to be updated)
- tag a release

This way, new releases can be used as downloaded from the auto-generated release packages at github.

Currently supported features/items (no change concerning the previous pull request)

- D compiler is searched for automatically from `dmd` and `ldmd2` (in this order)
- `DCFLAGS` default to `-w -g -O` but can be overridden via env variables
- SQLite and Curl is searched for via `pkg-config`, libs are automatically generated
- enabling notifications can be done with  `--enable-notifications`, which  searches automatically for `libnotify` using `pkg-config`
- systemd units are installed when the systemd system/user unit dir variable is found. These are again checked with `pkg-config --variable=systemdsystemunitdir systemd` etc.
- if `pkg-config` is not available, one can use `curl_LIBS` and `sqlite_LIBS` to pass in the necessary libs, same for `notify_LIBS`
- systemd service installation can be disabled by `--with-systemdsystemunitdir=no` or `--with-systemduserunitdir=no`
- the following files are automaically generated with version numbers replaces `pacman/PKGBUILD` and `spec/onedrive.spec`, and the version number in the man page is also automatically replaced
- The `version` file is now generated from the program version if no `.git` directory is found

Features from the current Makefile not carried over:

- RedHat specific stuff, should be automatically done now via the `pkg-config` calls

Incomplete items

- conversion of the pacman and spec file to use configure instead of the makefile directly (sorry, no experience with rpm/pacman)

### CODE REVIEW

**Comment by abraunegg** [comment]
@norbusan 
Conflicts need resolving

**Comment by norbusan** [comment]
I am working on updating this branch for the current sources, I am not overly happy anyway with autoconf ;-)

**Comment by norbusan** [comment]
@abraunegg can we decide for either autoconf or meson/ninja, so that I don't have to update both? The meson/ninja would leave the current Makefile as is, and allow for two ways of building, either directly using make or using meson. The autoconf branch would drop the Makefile completely and require the `./configure ; make` incantation.

What do you prefer?

**Comment by abraunegg** [comment]
> @abraunegg can we decide for either autoconf or meson/ninja, so that I don't have to update both? The meson/ninja would leave the current Makefile as is, and allow for two ways of building, either directly using make or using meson. The autoconf branch would drop the Makefile completely and require the `./configure ; make` incantation.
> 
> What do you prefer?

Having mainly always used `./configure` myself in most of the source packages I have recompiled over the years, I probably lean more towards `./configure`. The main aim of this work was to try and overcome the situations where the dependant libraries are not present, or even detect if DMD is installed or even active.

**Comment by norbusan** [comment]
> Having mainly always used `./configure` myself in most of the source packages I have recompiled over the years, I probably lean more towards `./configure`. The main aim of this work was to try and overcome the situations where the dependant libraries are not present, or even detect if DMD is installed or even active.

Ok, I will update the PR according to the current master, lots of changes have happened ;-)

**Comment by abraunegg** [comment]
@norbusan 
Travis CI builds are failing:
```
config.status: creating systemd.units/onedrive@.service
rm -f onedrive onedrive.o version \
     systemd.units/onedrive.service systemd.units/onedrive@.service
rm -rf autom4te.cache
rm -f config.log config.status
if [ -f .git/HEAD ] ; then \
	echo v2.3.2-499-ga07debb > version ; \
else \
	echo 2.3.2 > version ; \
fi
/home/travis/build/abraunegg/onedrive/dlang-x32/linux/bin32/dmd  -w -g -O -J. -L-lcurl -L-lsqlite3  -L-ldl src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d src/progress.d -ofonedrive
make: *** No rule to make target 'systemd.units/onedrive.service', needed by 'all'.  Stop.
The command "bash -ex .travis-ci.sh" exited with 2.
Done. Your build exited with 1.
```

**Comment by norbusan** [comment]
Ahh, a consequence of my recent changes that the systemd unit files are also generated by configure. Fixed that my removing them only in the distclean target.

**Comment by abraunegg** [comment]
@norbusan 
Whilst approved, I think this should be a v2.4.0 item as the configuration aspect (make clean; make PKGCONFIG=0 NOTIFICATIONS=0;) is changed ... thoughts?

If you are OK with this being in v2.3.3 then this is good to merge

**Comment by norbusan** [comment]
Fine with me waiting for 2.4.0. Let us release 2.3.3 at some point with the current fixes, and then merge 2.4.0 in the next run.

**Comment by norbusan** [comment]
@abraunegg Do we merge this now, or do you plan some other release before 3.4?

**Comment by abraunegg** [comment]
@norbusan 
I dont see any issue in merging this into 'master' now, or maybe wait ~24hrs + then do the merge and a v2.4.0 release right away .. what are your thoughts?

**Comment by norbusan** [comment]
Fine with wating for some emergencies! Let's wait till tomorrow. Please approve now or later, when it is convenient for you (merged master)

**Comment by norbusan** [comment]
Thanks

**Pull request merged**
