### PR TITLE
Fix downloading of files from OneDrive Personal Shared Folders (Issue #635)

### PR DESCRIPTION
**Pull request by abraunegg**
* Initial work on issue #635, pulling in change analysis from #473

### CODE REVIEW

**Comment by abraunegg** [comment]
@norbusan 
This is a tricky one to trigger - shared folders that return 'extra' API data when not expected to return that sort of data.

**without patch, normal handling of shared folder**
```
[DEBUG] ------------------------------------------------------------------
Syncing OneDrive Shared Folder: shared
Applying changes of Path ID: BC7D88EC1F539DCF!1288
[DEBUG] OneDrive Path Details: {"@odata.context":"https:\/\/graph.microsoft.com\/v1.0\/$metadata#drives('bc7d88ec1f539dcf')\/items\/$entity","cTag":"adDpCQzdEODhFQzFGNTM5RENGITEyODguNjM3MDMyNTQ3ODE2MTMwMDAw","eTag":"aQkM3RDg4RUMxRjUzOURDRiExMjg4LjI","fileSystemInfo":{"createdDateTime":"2019-01-14T18:54:43.266Z","lastModifiedDateTime":"2019-04-24T03:47:22.53Z"},"folder":{"childCount":5,"view":{"sortBy":"takenOrCreatedDateTime","sortOrder":"ascending","viewType":"thumbnails"}},"id":"BC7D88EC1F539DCF!1288","name":"shared","parentReference":{"driveId":"bc7d88ec1f539dcf","driveType":"personal"},"size":30422431}
[DEBUG] Item details returned no parent reference path
[DEBUG] Sync Folder Name:        shared
[DEBUG] Sync Folder Parent Path: 
[DEBUG] Sync Folder Actual Path: 
Processing 32 changes
[DEBUG] ------------------------------------------------------------------
[DEBUG] Processing change 1 of 32
[DEBUG] OneDrive Change: {"@odata.type":"#microsoft.graph.driveItem","cTag":"adDpCQzdEODhFQzFGNTM5RENGITEyODguNjM3MDMyNTQ3ODE2MTMwMDAw","eTag":"aQkM3RDg4RUMxRjUzOURDRiExMjg4LjI","fileSystemInfo":{"createdDateTime":"2019-01-14T18:54:43.266Z","lastModifiedDateTime":"2019-04-24T03:47:22.53Z"},"folder":{"childCount":0,"view":{"sortBy":"takenOrCreatedDateTime","sortOrder":"ascending","viewType":"thumbnails"}},"id":"BC7D88EC1F539DCF!1288","name":"shared","parentReference":{"driveId":"bc7d88ec1f539dcf","driveType":"personal"},"size":30422431}
[DEBUG] Not a OneDrive deleted item change
[DEBUG] defaultRootId                                        = 66D53BE8A5056ECA!101
[DEBUG] 'search id'                                          = BC7D88EC1F539DCF!1288
[DEBUG] id == defaultRootId                                  = false
[DEBUG] isItemRoot(item)                                     = false
[DEBUG] item['name'].str == 'root'                           = false
[DEBUG] singleDirectoryScope                                 = false
[DEBUG] isRoot                                               = false
[DEBUG] !hasParentReferenceId(item)                          = true
[DEBUG] isItemDeleted(item)                                  = false
[DEBUG] Handling change as 'root item', has no parent reference or is a deleted item
[DEBUG] Handing a OneDrive 'root' change
[DEBUG] Update/Insert local database with item details
[DEBUG] item details: Item("bc7d88ec1f539dcf", "BC7D88EC1F539DCF!1288", "shared", dir, "aQkM3RDg4RUMxRjUzOURDRiExMjg4LjI", "adDpCQzdEODhFQzFGNTM5RENGITEyODguNjM3MDMyNTQ3ODE2MTMwMDAw", 2019-Apr-24 03:47:22.53Z, "", "", "", "", "", "")
[DEBUG] ------------------------------------------------------------------

```

**with patch & manually inserting the 'extra' data' that would normally cause download failure**
```
[DEBUG] ------------------------------------------------------------------
Syncing OneDrive Shared Folder: shared
Applying changes of Path ID: BC7D88EC1F539DCF!1288
[DEBUG] OneDrive Path Details: {"@odata.context":"https:\/\/graph.microsoft.com\/v1.0\/$metadata#drives('bc7d88ec1f539dcf')\/items\/$entity","cTag":"adDpCQzdEODhFQzFGNTM5RENGITEyODguNjM3MDMyNTQ3ODE2MTMwMDAw","eTag":"aQkM3RDg4RUMxRjUzOURDRiExMjg4LjI","fileSystemInfo":{"createdDateTime":"2019-01-14T18:54:43.266Z","lastModifiedDateTime":"2019-04-24T03:47:22.53Z"},"folder":{"childCount":5,"view":{"sortBy":"takenOrCreatedDateTime","sortOrder":"ascending","viewType":"thumbnails"}},"id":"BC7D88EC1F539DCF!1288","name":"shared","parentReference":{"driveId":"bc7d88ec1f539dcf","driveType":"personal"},"size":30422431}
[DEBUG] Item details returned no parent reference path
[DEBUG] Sync Folder Name:        shared
[DEBUG] Sync Folder Parent Path: 
[DEBUG] Sync Folder Actual Path: 
Processing 32 changes
[DEBUG] ------------------------------------------------------------------
[DEBUG] Processing change 1 of 32
[DEBUG] OneDrive Change: {"@odata.type":"#microsoft.graph.driveItem","cTag":"adDpCQzdEODhFQzFGNTM5RENGITEyODguNjM3MDMyNTQ3ODE2MTMwMDAw","eTag":"aQkM3RDg4RUMxRjUzOURDRiExMjg4LjI","fileSystemInfo":{"createdDateTime":"2019-01-14T18:54:43.266Z","lastModifiedDateTime":"2019-04-24T03:47:22.53Z"},"folder":{"childCount":0,"view":{"sortBy":"takenOrCreatedDateTime","sortOrder":"ascending","viewType":"thumbnails"}},"id":"BC7D88EC1F539DCF!1288","name":"shared","parentReference":{"driveId":"bc7d88ec1f539dcf","driveType":"personal"},"size":30422431}
Triggering #635 HACK
item: {"@odata.type":"#microsoft.graph.driveItem","cTag":"adDpCQzdEODhFQzFGNTM5RENGITEyODguNjM3MDMyNTQ3ODE2MTMwMDAw","eTag":"aQkM3RDg4RUMxRjUzOURDRiExMjg4LjI","fileSystemInfo":{"createdDateTime":"2019-01-14T18:54:43.266Z","lastModifiedDateTime":"2019-04-24T03:47:22.53Z"},"folder":{"childCount":0,"view":{"sortBy":"takenOrCreatedDateTime","sortOrder":"ascending","viewType":"thumbnails"}},"id":"BC7D88EC1F539DCF!1288","name":"shared","parentReference":{"driveId":"bc7d88ec1f539dcf","driveType":"personal","id":"BC7D88EC1F539DCF!99999999999","name":"invalid_parent","path":"\/drives\/bc7d88ec1f539dcf\/items\/BC7D88EC1F539DCF!99999999999:"},"size":30422431}
[DEBUG] Not a OneDrive deleted item change
[DEBUG] defaultRootId                                        = 66D53BE8A5056ECA!101
[DEBUG] 'search id'                                          = BC7D88EC1F539DCF!1288
[DEBUG] id == defaultRootId                                  = false
[DEBUG] isItemRoot(item)                                     = false
[DEBUG] item['name'].str == 'root'                           = false
[DEBUG] singleDirectoryScope                                 = false
[DEBUG] 'parentReference id'                                 = BC7D88EC1F539DCF!99999999999
[DEBUG] syncFolderName                                       = shared
[DEBUG] syncFolderPath                                       = 
[DEBUG] syncFolderChildPath                                  = 
[DEBUG] thisItemId                                           = BC7D88EC1F539DCF!1288
[DEBUG] thisItemPath                                         = /drives/bc7d88ec1f539dcf/items/BC7D88EC1F539DCF!99999999999:
[DEBUG] 'item id' matches search 'id'                        = true
[DEBUG] 'parentReference id' matches search 'id'             = false
[DEBUG] 'thisItemPath' contains 'syncFolderChildPath'        = true
[DEBUG] 'thisItemPath' contains search 'id'                  = false
[DEBUG] Change matches search criteria to apply
[DEBUG] The item we are syncing is a folder
[DEBUG] Parent not in database but appears to be a shared folder: item.driveId (bc7d88ec1f539dcf), item.parentId (BC7D88EC1F539DCF!99999999999) not in local database
[DEBUG] Update/Insert local database with item details
[DEBUG] item details: Item("bc7d88ec1f539dcf", "BC7D88EC1F539DCF!1288", "shared", dir, "aQkM3RDg4RUMxRjUzOURDRiExMjg4LjI", "adDpCQzdEODhFQzFGNTM5RENGITEyODguNjM3MDMyNTQ3ODE2MTMwMDAw", 2019-Apr-24 03:47:22.53Z, "", "", "", "", "", "")
[DEBUG] ------------------------------------------------------------------
```

I am confident that this fixes the issue, needs extensive testing however / extensive regression testing however.

**Comment by norbusan** [comment]
@abraunegg How can I try to trigger that? Do you have any idea when this extra information is included, which properties of the shared folder are necessary?

I can review the code concerning "reasonability" but testing only with my limited set of shared folders.

**Comment by abraunegg** [comment]
Will email you a patch for current master to inject bad data to shared folders that will trigger this

**Comment by abraunegg** [comment]
@norbusan 
User has confirmed that this fixes the issue - how is your local testing going?

**Pull request merged**
