### PR TITLE
Add new config option to rate limit connection to OneDrive

### PR DESCRIPTION
**Pull request by abraunegg**
* Add new config option to rate limit connection to OneDrive

### CODE REVIEW

**Comment by abraunegg** [comment]
@norbusan 
When activating this option, the upload data can be seen when using `nethogs`

**application:**
```
The file has not changed
Uploading new items of ~/OneDrivePersonal
Uploading new file ./random_files/7GLHbbPdz9UzBLQJxKHefZdyMSJmv5sO/file0.data ... 
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:05:59                                                                                                                    
done.
Remaining free space on OneDrive: 5297368689
Uploading new file ./random_files/7GLHbbPdz9UzBLQJxKHefZdyMSJmv5sO/file1.data ... 
Uploading  60% |oooooooooooooooooooooooo                |   ETA   00:01:48     
```

**nethogs:**
```
NetHogs version 0.8.5

    PID USER     PROGRAM                                                 DEV        SENT      RECEIVED       
  30568 alex     ./onedrive                                              ens192    106.821       2.508 KB/sec
```

This is limited to the default minimum of 128KB/s.

Anything lower that this value triggered 504 responses from OneDrive when uploading data fragments.

Resolves:
* https://github.com/abraunegg/onedrive/issues/885
* https://github.com/abraunegg/onedrive/issues/150
* https://github.com/skilion/onedrive/issues/174

**Comment by abraunegg** [comment]
@norbusan 
Any thoughts on this PR ?

**Comment by norbusan** [comment]
Looks fine to me, although it is not clear to me whether these `long` numbers are the *only* allowed ones, or whether I can use `345678` as upload limit, too?

**Review by norbusan — APPROVED** [review]

**Comment by abraunegg** [comment]
> Looks fine to me, although it is not clear to me whether these `long` numbers are the _only_ allowed ones, or whether I can use `345678` as upload limit, too?

Any long number can be used, so long as it is larger than 131072

**Pull request merged**
