### PR TITLE
Update skip_dotfiles handling of .folders when in monitor mode

### PR DESCRIPTION
**Pull request by abraunegg**
* Rework of objective from #846 with less change / coding impact

### CODE REVIEW

**Comment by TheOnlyTrueJonathanHeard** [comment]
I have tested it and I figured out two minor problems: 

## Use Case 1
1. Make sure skip_dotfiles is activated in the config file
2. Run onedrive in monitor mode
3. Create a directory starting with a dot
4. Rename directory to a normal name (not starting with dot)

**Expected Result** 
Dir is uploaded immediately after renaming 

**Actual result** 
The dir is not uploaded immediately but at the next sync

**Verbose Log output**
```
Monitor directory: .
[M] Skipping watching path - .folder found & --skip-dot-files enabled: ./.test
Monitor directory: ./test
[M] Item moved: ./.test -> ./test
Moving ./.test to ./test
Skipping uploading this file as it cannot be read (file permissions or file corruption): ./test
Starting a sync with OneDrive
Applying changes of Path ID: DC457103BFF8CCB6!101
Uploading differences of .
Processing root
The directory has not changed
Uploading new items of .
OneDrive Client requested to create remote path: ./test
The requested directory to create was not found on OneDrive - creating remote directory: ./test
Successfully created the remote directory ./test on OneDrive
Applying changes of Path ID: DC457103BFF8CCB6!101
Sync with OneDrive is complete
```
This also occurs in the master branch but  not in #846 

## Use Case 2
1. Make sure skip_dotfiles is activated in the config file
2. Run onedrive in monitor mode
3. Make a dummy folder and a dummy file which both don't start with a dot
4. Rename the dummy folder to a folder starting with a dot
5. Move the dummy file in the dummy folder

**Expected Result** 
The dummy file is deleted remotely immediately after step 5

**Actual Result**
The dummy file is not deleted immediately but at the next sync. Futhermore It is given a warning "Cannot move item: Can't move an item to an unsynced directory" after step 5. 

**Verbose Log output**
```
Monitor directory: .
Monitor directory: ./test
[M] Directory created: ./test
Uploading differences of ./test
Uploading new items of ./test
OneDrive Client requested to create remote path: ./test
The requested directory to create was not found on OneDrive - creating remote directory: ./test
Successfully created the remote directory ./test on OneDrive
[M] File changed: ./test.txt
Uploading differences of ./test.txt
Uploading new items of ./test.txt
Uploading new file ./test.txt ... done.
Remaining free space on OneDrive: 5368709120
[M] Item moved: ./test -> ./.test
Moving ./test to ./.test
Removing item from OneDrive due to skip_dotfiles = true
Deleting item from OneDrive: ./test
[M] Item moved: ./test.txt -> test/test.txt
Moving ./test.txt to test/test.txt
Cannot move item: Can't move an item to an unsynced directory
Starting a sync with OneDrive
Applying changes of Path ID: DC457103BFF8CCB6!101
Uploading differences of .
Processing root
The directory has not changed
Processing test.txt
The file has been deleted locally
Deleting item from OneDrive: test.txt
Uploading new items of .
Skipping item - .file or .folder: ./.test
Applying changes of Path ID: DC457103BFF8CCB6!101
Sync with OneDrive is complete

```
This doesn't occur in the master branch (but also in #846)

**Comment by abraunegg** [comment]
@TheOnlyTrueJonathanHeard 
Can you test this updated PR against your additional use cases:

**use case 1**
```
./onedrive --confdir '~/.config/onedrive-personal/' --monitor --verbose
Using Config Dir: /home/alex/.config/onedrive-personal/
Notification (dbus) server not available, disabling
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDrivePersonal
Application version: v2.4.0-9-gc41adda
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 5368709120
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Initializing monitor ...
OneDrive monitor interval (seconds): 30
Monitor directory: .
Monitor directory: ./random_files
Monitor directory: ./random_images
Monitor directory: ./random_videos
[M] Skipping watching path - .folder found & --skip-dot-files enabled: ./.test_folder
Monitor directory: ./test_folder
[M] Item moved: ./.test_folder -> ./test_folder
Uploading differences of ./test_folder
Uploading new items of ./test_folder
OneDrive Client requested to create remote path: ./test_folder
The requested directory to create was not found on OneDrive - creating remote directory: ./test_folder
Successfully created the remote directory ./test_folder on OneDrive
[M] Item deleted: ./test_folder
Deleting item from OneDrive: ./test_folder
Starting a sync with OneDrive
Applying changes of Path ID: 66D53BE8A5056ECA!101
Uploading differences of .
Processing root
The directory has not changed
Processing random_videos
The directory has not changed
Processing random_images
The directory has not changed
Processing random_files
The directory has not changed
Uploading new items of .
Applying changes of Path ID: 66D53BE8A5056ECA!101
Sync with OneDrive is complete
^CGot termination signal, shutting down db connection
```

**use case 2**
```
./onedrive --confdir '~/.config/onedrive-personal/' --monitor --verbose
Using Config Dir: /home/alex/.config/onedrive-personal/
Notification (dbus) server not available, disabling
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDrivePersonal
Application version: v2.4.0-9-gc41adda
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 5368709120
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Initializing monitor ...
OneDrive monitor interval (seconds): 30
Monitor directory: .
Monitor directory: ./random_files
Monitor directory: ./random_images
Monitor directory: ./random_videos
Monitor directory: ./test_folder
[M] Directory created: ./test_folder
Uploading differences of ./test_folder
Uploading new items of ./test_folder
OneDrive Client requested to create remote path: ./test_folder
The requested directory to create was not found on OneDrive - creating remote directory: ./test_folder
Successfully created the remote directory ./test_folder on OneDrive
[M] File changed: ./test_file.txt
Uploading differences of ./test_file.txt
Uploading new items of ./test_file.txt
Uploading new file ./test_file.txt ... done.
Remaining free space on OneDrive: 5368709103
[M] Item moved: ./test_folder -> ./.test_folder
Moving ./test_folder to ./.test_folder
Removing item from OneDrive due to skip_dotfiles = true
Deleting item from OneDrive: ./test_folder
[M] Item moved: ./test_file.txt -> .test_folder/test_file.txt
Moving ./test_file.txt to .test_folder/test_file.txt
Item has been moved to a location that is excluded from sync operations. Removing item from OneDrive
Deleting item from OneDrive: ./test_file.txt
[M] Item deleted: .test_folder/test_file.txt
Item cannot be deleted because not found in database
[M] Item deleted: ./.test_folder
Item cannot be deleted because not found in database
Starting a sync with OneDrive
Applying changes of Path ID: 66D53BE8A5056ECA!101
Uploading differences of .
Processing root
The directory has not changed
Processing random_videos
The directory has not changed
Processing random_images
The directory has not changed
Processing random_files
The directory has not changed
Uploading new items of .
Applying changes of Path ID: 66D53BE8A5056ECA!101
Sync with OneDrive is complete
^CGot termination signal, shutting down db connection

```

**Comment by TheOnlyTrueJonathanHeard** [comment]
Now all working :+1:

**Comment by abraunegg** [comment]
@norbusan 
Any chance to review this one as well ?

**Pull request merged**
