### PR TITLE
Update 'root' item identification handling (Issue #456)

### PR DESCRIPTION
**Pull request by abraunegg**
* Add additional check to ensure item root we flag as 'root' is not just name checked as 'root'

### CODE REVIEW

**Comment by abraunegg** [comment]
without patch:
```
(dmd-2.085.0)[alex@centos7full onedrive]$ ./onedrive --confdir '~/.config/onedrive-business' --synchronize --verbose --resync
Loading config ...
Using Config Dir: /home/alex/.config/onedrive-business
Deleting the saved status ...
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDriveBusiness
Initializing the Synchronization Engine ...
Account Type: business
Default Drive ID: b!xA9hqR7mT0OL6Gku8YbuzTJ8oZmRnQZJu6-yDL49Zc5MccrHbuT0R4QUwIzUvbJY
Default Root ID: 01D6JQORV6Y2GOVW7725BZO354PWSELRRZ
Remaining Free Space: 1098672456121
Fetching details for OneDrive Root
OneDrive Root does not exist in the database. We need to add it.
Added OneDrive Root to the local database
Syncing changes from OneDrive ...
Applying changes of Path ID: 01D6JQORV6Y2GOVW7725BZO354PWSELRRZ
Processing 5 changes
Downloading file Document.docx ... done.
Creating directory: blah
Uploading differences of .
Processing root
The directory has not changed
Processing Document.docx
The file has not changed
Processing blah
The directory has not changed
Uploading new items of .
Applying changes of Path ID: 01D6JQORV6Y2GOVW7725BZO354PWSELRRZ
(dmd-2.085.0)[alex@centos7full onedrive]$ 
```
with patch:
```
(dmd-2.085.0)[alex@centos7full onedrive-pr457]$ ./onedrive --confdir '~/.config/onedrive-business' --synchronize --verbose --resync
Loading config ...
Using Config Dir: /home/alex/.config/onedrive-business
Deleting the saved status ...
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDriveBusiness
Initializing the Synchronization Engine ...
Account Type: business
Default Drive ID: b!xA9hqR7mT0OL6Gku8YbuzTJ8oZmRnQZJu6-yDL49Zc5MccrHbuT0R4QUwIzUvbJY
Default Root ID: 01D6JQORV6Y2GOVW7725BZO354PWSELRRZ
Remaining Free Space: 1098672456121
Fetching details for OneDrive Root
OneDrive Root does not exist in the database. We need to add it.
Added OneDrive Root to the local database
Syncing changes from OneDrive ...
Applying changes of Path ID: 01D6JQORV6Y2GOVW7725BZO354PWSELRRZ
Processing 5 changes
Creating directory: blah/root
Creating directory: root
Uploading differences of .
Processing root
The directory has not changed
Processing Document.docx
The file has not changed
Processing blah
The directory has not changed
Processing root
The directory has not changed
Processing root
The directory has not changed
Uploading new items of .
Applying changes of Path ID: 01D6JQORV6Y2GOVW7725BZO354PWSELRRZ
(dmd-2.085.0)[alex@centos7full onedrive-pr457]$ 
```

**Comment by norbusan** [comment]
I cannot reproduce this with the current version without the patch.
```
$ onedrive --confdir ... --synchronize
...
$ mkdir ~/OnedriveTest/root
$ touch ~/OnedriveTest/root/foobar
$ onedrive --confdir ~/.config/onedrive-test/ --synchronize -v
Loading config ...
Using Config Dir: /home/norbert/.config/onedrive-test/
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/norbert/OneDriveTest
Initializing the Synchronization Engine ...
Account Type: personal
Default Drive ID: d6ebf6b564426b61
Default Root ID: D6EBF6B564426B61!101
Remaining Free Space: 5368709120
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from OneDrive ...
Applying changes of Path ID: D6EBF6B564426B61!101
Uploading differences of .
Processing root
The directory has not changed
Processing .abcde
The directory has not changed
Processing hello
The file has not changed
Processing foobar
The directory has not changed
Processing .bla
The file has not changed
Processing .HelloWorld
The file has not changed
Processing Test
The directory has not changed
Processing asdf
The directory has not changed
Processing foobar
The directory has not changed
Processing bla.txt
The file has not changed
Processing .abcde
The directory has not changed
Processing Hello
The file has not changed
Processing root
The directory has not changed
Uploading new items of .
Uploading new file ./root/foobar ... done.
Remaining free space: 5368709120
Applying changes of Path ID: D6EBF6B564426B61!101
$ 
```

What am I doing wrong?

**Comment by abraunegg** [comment]
@norbusan 
Without the patch, create a folder called 'root' via the OneDrive web interface (not on Linux)

Without the patch, the folder will not be created / downloaded

With the patche (`--resync` needed) the 'root' folder created online will be created

**Comment by abraunegg** [comment]
@norbusan 
Validated as well not to break OneDrive Personal Shared Folders which can be very 'fussy' re 'isRoot' designations

**Comment by norbusan** [comment]
Will check later today, thanks for the explanation.

**Pull request merged**
