### PR TITLE
INSTALL.md: Update link to Solus package

### PR DESCRIPTION
**Pull request by Staudey**
The old phabricator tracker (dev.getsol.us) no longer exists and just links to the base of the new GitHub packages repository

There is no emul32/i686 build for the Solus onedrive package (and Solus has no i686 edition)

### CODE REVIEW

**Comment by abraunegg** [comment]
@Staudey 
Please can you rebase this into v2.5.0 RC3.

The existing master will be replaced shortly.

**Comment by Staudey** [comment]
@abraunegg Done. I've also adjusted the alignment a bit. If you don't want that in this PR I'll change it back

**Comment by Staudey** [comment]
wait, something's wrong ^^

**Comment by Staudey** [comment]
There we go, sorry about that.

I've decided to leave the formatting change out to make the diff easier to look at again.

**Comment by abraunegg** [comment]
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

**Pull request merged**
