### PR TITLE
Fix Docker Hub autobuild

### PR DESCRIPTION
**Pull request by abraunegg**
* Relocate Dockerfile back to repository root

### CODE REVIEW

**Comment by abraunegg** [comment]
@norbusan 
It appears that Docker Hub does not like the `Dockerfile` being relocated (despite the documents indicating elsewhere is supported)

**Comment by abraunegg** [comment]
@norbusan 
And now with `Dockerfile` located in contrib - master is building again ...

**Comment by norbusan** [comment]
This is cryptic ...
anyway, I have pushed one chnage to this branch that updates the Docker.md file. Otherwise, that PR is fine if we need to do it.

**Comment by abraunegg** [comment]
I think this 'non build' may have been related to 'Build Caching' - without it turned on, it seems to build .... weird ..........

**Comment by abraunegg** [comment]
Closing this PR - not required

**Pull request closed without merging**
