### PR TITLE
Shutdown Inotify Monitor Gracefully

### PR DESCRIPTION
**Pull request by JC-comp**
This pull request adds functionality to gracefully shut down the inotify monitor when the user sends a SIGINT signal (Ctrl+C). When the monitor receives the SIGINT signal, it closes the inotify file descriptor and exits the program gracefully.

Changes
- Add interrupt mechanism to monitor worker
- Add shutdown process for Monitor
- Improve communication between monitor worker

### CODE REVIEW

**Comment by abraunegg** [comment]
@JC-comp 
This PR does not compile cleanly:
```
ldc2  -w -g -O -J. -d-debug -gc -L-lcurl -L-lsqlite3  -L-ldl src/main.d src/config.d src/log.d src/util.d src/qxor.d src/curlEngine.d src/onedrive.d src/sync.d src/itemdb.d src/sqlite.d src/clientSideFiltering.d src/monitor.d src/arsd/cgi.d -ofonedrive
onedrive.o:cgi.d:function _D7monitor23MonitorBackgroundWorker11__fieldDtorMFNeZv: error: undefined reference to '_D3std7process4Pipe11__fieldDtorMOFNeZv'
collect2: error: ld returned 1 exit status
```

**Comment by JC-comp** [comment]
@abraunegg 
I am unable to reproduce this issue on my end. Could you please test it in a new environment or provide detailed setup instructions for your environment?

```
$ git clone https://github.com/abraunegg/onedrive
$ git fetch origin pull/2628/head:pr2628
$ git switch pr2628
$ source ~/dlang/ldc-1.36.0/activate
$ ./configure
$ make
if [ -f .git/HEAD ] ; then \
        git describe --tags > version ; \
else \
        echo v2.5.0-alpha-5 > version ; \
fi
ldc2 -w -g -O -J. -L-lcurl -L-lsqlite3  -L-ldl src/main.d src/config.d src/log.d src/util.d src/qxor.d src/curlEngine.d src/onedrive.d src/sync.d src/itemdb.d src/sqlite.d src/clientSideFiltering.d src/monitor.d src/arsd/cgi.d -ofonedrive
$ 
```

**Comment by abraunegg** [comment]
@JC-comp 
This PR now has conflicts that need to be resolved

**Comment by JC-comp** [comment]
Update
- Ensure backward compatibility with ldc v1.20.1 and test the compilation
- Resolve conflicts
- Fix shutdown process

**Comment by abraunegg** [comment]
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

**Pull request merged**
