### PR TITLE
Retry session upload fragment when transient errors occur to prevent silent upload failure

### PR DESCRIPTION
**Pull request by abraunegg**
* Add debugging for session uploads of large files

### CODE REVIEW

**Comment by abraunegg** [comment]
@norbusan 
I have been working on this issue with @pcolmer where large files would 'randomly' just fail - for example, this is what would occur in the debug logs:
**Example 1:**
```
Uploading  51% |ooooooooooooooooooooo                   |   ETA   00:05:19 
                                                                                
Uploading  52% |ooooooooooooooooooooo                   |   ETA   00:05:14 
```
**Example 2:**
```
Uploading   2% |o                                       |   ETA   00:16:42 
                                                                                
Uploading   2% |oo                                      |   ETA   00:16:48 
```
In developing the PR I was able to get the following *eventually* :
```
Uploading  84% |oooooooooooooooooooooooooooooooooo      |   ETA   00:03:15 ERROR: OneDrive returned an error with the following message:                                                        
  Error Message: Failure when receiving data from the peer on handle 12E20A0
Fragment upload failed - exception response from OneDrive
Response: {"expirationDateTime":"2019-11-15T20:37:20.348Z","nextExpectedRanges":["1887436800-2219534036"]}
Error: onedrive.OneDriveException@src/onedrive.d(909): HTTP request returned status code 100 (Continue)
null
----------------
src/onedrive.d:52 void onedrive.OneDriveApi.checkHttpCode(ref const(std.json.JSONValue)) [0x60ef3e]
src/onedrive.d:375 std.json.JSONValue onedrive.OneDriveApi.uploadFragment(const(char)[], immutable(char)[], long, long, long) [0x60d11c]
src/upload.d:184 std.json.JSONValue upload.UploadSession.upload() [0x62ab99]
src/upload.d:48 std.json.JSONValue upload.UploadSession.upload(immutable(char)[], const(char)[], const(char)[], const(char)[], const(char)[]) [0x62a381]
src/sync.d:2605 void sync.SyncEngine.uploadNewFile(immutable(char)[]) [0x624c8f]
src/sync.d:2328 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x6239aa]
src/sync.d:2311 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x623812]
src/sync.d:2311 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x623812]
src/sync.d:2311 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x623812]
src/sync.d:1700 void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x621509]
src/main.d:850 void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool, long, bool, bool) [0x609e06]
src/main.d:617 _Dmain [0x6090a6]
Retrying fragment upload
Fragment: 182
Uploading  85% |ooooooooooooooooooooooooooooooooooo     |   ETA   00:03:10 Fragment: 183
```
and
```
Fragment: 369 of 369
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:38:33 Fragment upload failed - exception response from OneDrive                                                            
Error: onedrive.OneDriveException@src/onedrive.d(909): HTTP request returned status code 507 (Insufficient Storage)
{
    "error": {
        "code": "quotaLimitReached",
        "message": "Insufficient Space Available"
    }
}
----------------
src/onedrive.d:52 void onedrive.OneDriveApi.checkHttpCode(ref const(std.json.JSONValue)) [0x60f212]
src/onedrive.d:375 std.json.JSONValue onedrive.OneDriveApi.uploadFragment(const(char)[], immutable(char)[], long, long, long) [0x60d3f0]
src/upload.d:184 std.json.JSONValue upload.UploadSession.upload() [0x62ae84]
src/upload.d:48 std.json.JSONValue upload.UploadSession.upload(immutable(char)[], const(char)[], const(char)[], const(char)[], const(char)[]) [0x62a655]
src/sync.d:2605 void sync.SyncEngine.uploadNewFile(immutable(char)[]) [0x624f63]
src/sync.d:2328 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x623c7e]
src/sync.d:2311 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x623ae6]
src/sync.d:2311 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x623ae6]
src/sync.d:2311 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x623ae6]
src/sync.d:1700 void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x6217dd]
src/main.d:850 void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool, long, bool, bool) [0x60a0da]
src/main.d:617 _Dmain [0x60937a]
Retrying fragment upload
skipped.
ERROR: OneDrive returned an error with the following message:
  Error Message: HTTP request returned status code 507 (Insufficient Storage)
  Error Reason:  Insufficient Space Available
Applying changes of Path ID: 66D53BE8A5056ECA!101
Processing 201 changes
Processing 227 changes
Processing 14 changes
```

What this PR does is:

* In the event of a fragment upload exception, retries the fragment that errored
* Prints helpful message of when the fragment fails & file upload fails

Example:
```
Applying changes of Path ID: 66D53BE8A5056ECA!101
Uploading differences of .
Processing root
The directory has not changed
Processing test_files
The directory has not changed
Processing big_video
The directory has not changed
Processing Spiral - s06e11 - Episode 11.mp4
The file has not changed
Processing test_video
The directory has not changed
Processing testsrc.mp4
The file has not changed
Processing iso_files
The directory has not changed
Processing ubuntu-18.04.2-desktop-amd64.iso
The file has not changed
Processing ova_files
The directory has not changed
Uploading new items of .
Uploading new file ./test_files/ova_files/arch_minimal_20190101.ova ... 
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:38:42                                                                                                                      
Fragment upload failed - received an exception response from OneDrive
ERROR: OneDrive returned an error with the following message:
  Error Message: HTTP request returned status code 507 (Insufficient Storage)
  Error Reason:  Insufficient Space Available
Retrying fragment upload
Retry to upload fragment failed
ERROR: OneDrive returned an error with the following message:
  Error Message: HTTP request returned status code 507 (Insufficient Storage)
  Error Reason:  Insufficient Space Available
  File upload session failed - invalid response from OneDrive
Applying changes of Path ID: 66D53BE8A5056ECA!101
```

**Comment by norbusan** [comment]
PS around merging this, please also bump the version to .12-dev, thanks ;-)

**Comment by abraunegg** [comment]
> PS around merging this, please also bump the version to .12-dev, thanks ;-)

Yep .. was going to do that via another PR. Waiting on feedback on PR from user where issue is highly reproducable first before merging

**Comment by pcolmer** [comment]
Managed to get an error back from OneDrive which the client has successfully coped with:

```
Uploading  32% |oooooooooooooo                          |   ETA   00:07:58
Fragment upload failed - received an exception response from OneDrive
ERROR: OneDrive returned an error with the following message:
  Error Message: HTTP request returned status code 500 (Internal Server Error)
  Error Reason:  General Exception While Processing
Retrying fragment upload
```

This is a huge improvement so a massive thank you, @abraunegg, for finding a solution.

**Comment by abraunegg** [comment]
@pcolmer 
Glad this was finally caught. 

**Question 1:** Did the fragment retry work as expected and file continued to be uploaded correctly?

**Question 2:** If the file uploaded correctly with the fragment retry, is the file 100% correct / without error / correct checksums etc ? are you able to validate this & advise?

**Comment by pcolmer** [comment]
> Question 1: Did the fragment retry work as expected and file continued to be uploaded correctly?

Yes.

> Question 2: If the file uploaded correctly with the fragment retry, is the file 100% correct / without error / correct checksums etc ? are you able to validate this & advise?

Yes - I've run `md5sum` on the original and a copy downloaded from OneDrive and the numbers match,

Thank you again.

**Comment by abraunegg** [comment]
@pcolmer 
Awesome .. thanks for the confirmation on that .. greatly appreciated given the difficulty in reproducing this. Will merge into master shortly.

**Pull request merged**
