### PR TITLE
Update logic handling of --single-directory

### PR DESCRIPTION
**Pull request by abraunegg**
* Update logic handling of --single-directory. Without this patch, if there were the following:
  - 'asdf' & same sub-directories
  - 'asdfasdf' & same sub-directories

What would happen when ` --single-directory 'asdf'` was used, 'asdfasdf' would be flagged as an obsolete item which could lead to inadvertent local data loss.

With this patch, pattern matching of 'asdf' for --single-directory operations is now correctly using the entire child path, rather than just the child folder name

### CODE REVIEW

**Comment by norbusan** [comment]
It seems that this can happen only in `--single-directory` mode, right? At least in normal mode I couldn't get it to happen:
```
$ cd ~/OneDrive
$ mkdir -p Test/asdf/foobar
$ mkdir -p Test/asdfasdf/foobar
$ touch Test/asdf/foobar/hello.txt
$ touch Test/asdfasdf/foobar/hello.txt
$ onedrive --synchronize
...
```

OTOH, starting with the same layout as above (`Test/asdf/foobar/hello.text` and same for `asdfasdf`) and doing a sync on single directory Test/asdf somehow goes bad:
```
$ onedrive --confdir ~/.config/onedrive-test --synchronize -v --single-directory Test/asdf
Loading config ...
Using Config Dir: /home/norbert/.config/onedrive-test
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/norbert/OneDriveTest
Initializing the Synchronization Engine ...
Account Type: personal
Default Drive ID: d6ebf6b564426b61
Default Root ID: D6EBF6B564426B61!101
Remaining Free Space: 5368662337
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from this selected path: Test/asdf
Syncing changes from selected OneDrive path ...
Getting path details from OneDrive ...
Applying changes of Path ID: D6EBF6B564426B61!115
Trying to delete item Test/asdfasdf
Deleting item Test/asdfasdf
Uploading differences of Test/asdf
Processing asdf
The directory has not changed
Processing foobar
The directory has not changed
Processing hello.txt
The file has not changed
Uploading new items of Test/asdf
Getting path details from OneDrive ...
Applying changes of Path ID: D6EBF6B564426B61!115
```

After that the situation is *completely* messed up:

- checking on the web site (and reloading a few times), there are both dirs `asdf` and `asdfasdf`
- on the client there is only `asdf`
- repeating the sync does **not** bring the two into sync:
```
$ ls Test/
asdf/
$ onedrive --confdir ~/.config/onedrive-test --synchronize -v 
Loading config ...
Using Config Dir: /home/norbert/.config/onedrive-test
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/norbert/OneDriveTest
Initializing the Synchronization Engine ...
Account Type: personal
Default Drive ID: d6ebf6b564426b61
Default Root ID: D6EBF6B564426B61!101
Remaining Free Space: 5368662337
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from OneDrive ...
Applying changes of Path ID: D6EBF6B564426B61!101
Uploading differences of .
Processing root
The directory has not changed
Processing Pictures
The directory has not changed
Processing Documents
The directory has not changed
Processing ana-kmx-hnd-20181220.pdf
The file has not changed
Processing Test
The directory has not changed
Processing asdf
The directory has not changed
Processing foobar
The directory has not changed
Processing hello.txt
The file has not changed
Uploading new items of .
Applying changes of Path ID: D6EBF6B564426B61!101
```

I guess this is the problem, right?

**Comment by norbusan** [comment]
I can confirm that this PR fixes the aforementioned problem. This is a serious bug and should be released rather soon.

**Comment by abraunegg** [comment]
Correct - issue only exists with --single-directory use & same folder names

**without patch**
```
./onedrive --confdir '~/.config/onedrive-personal' --synchronize --verbose --single-directory 'qwer'
Loading config ...
Using Config Dir: /home/alex/.config/onedrive-personal
No config file found, using application defaults
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDrive
Initializing the Synchronization Engine ...
Account Type: personal
Default Drive ID: <redacted>
Default Root ID: <redacted>
Remaining Free Space: 5368587966
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from this selected path: qwer
Syncing changes from selected OneDrive path ...
Getting path details from OneDrive ...
Applying changes of Path ID: <redacted>
Trying to delete item qwerqwer                      <- ERROR - BAD DELETE
Deleting item qwerqwer                                  <- ERROR - BAD DELETE
Uploading differences of qwer
Processing qwer
The directory has not changed
Processing 1
The directory has not changed
Processing Document1.docx
The file has not changed
Processing 2
The directory has not changed
Processing Document1.docx
The file has not changed
Processing Document1.docx
The file has not changed
Processing ggggggg
The directory has not changed
Processing Document1.docx
The file has not changed
Processing Presentation.pptx
The file has not changed
Uploading new items of qwer
Getting path details from OneDrive ...
Applying changes of Path ID: <redacted>
```
Folder 'qwerqwer' removed locally, but still exists on OneDrive (for the moment ...)

**with patch**
```
./onedrive --confdir '~/.config/onedrive-personal' --synchronize --verbose --single-directory 'qwer'
Loading config ...
Using Config Dir: /home/alex/.config/onedrive-personal
No config file found, using application defaults
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDrive
Initializing the Synchronization Engine ...
Account Type: personal
Default Drive ID: <redacted>
Default Root ID: <redacted>
Remaining Free Space: 5368587966
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from this selected path: qwer
Syncing changes from selected OneDrive path ...
Getting path details from OneDrive ...
Applying changes of Path ID: <redacted>
Uploading differences of qwer
Processing qwer
The directory has not changed
Processing 1
The directory has not changed
Processing Document1.docx
The file has not changed
Processing 2
The directory has not changed
Processing Document1.docx
The file has not changed
Processing Document1.docx
The file has not changed
Processing ggggggg
The directory has not changed
Processing Document1.docx
The file has not changed
Processing Presentation.pptx
The file has not changed
Uploading new items of qwer
Getting path details from OneDrive ...
Applying changes of Path ID: <redacted>
```

Folder 'qwerqwer' untouched locally as expected

**Comment by norbusan** [comment]
Thanks, that was a good catch!!!

**Pull request merged**
