### PR TITLE
 Update release files for 2.3.4

### PR DESCRIPTION
**Pull request by abraunegg**
*  Update release files for 2.3.4

### CODE REVIEW

**Comment by abraunegg** [comment]
@norbusan 
I think this is all that needs to be changed for a new release - can you help validate / check?

**Comment by norbusan** [comment]
I also think that you didn't run `autoconf` but edited `configure` by hand. This is not good, because the version number appears in several places. The top of the `configure.ac` explains what should be done

- change version number to 2.3.4
- run `autoconf`
- commit changed configure and configure.ac
- tag release

**Comment by abraunegg** [comment]
@norbusan 
No worries - will modify my process once these 3 issues / questions are resolved & will update this PR - release on hold for now.

**Comment by abraunegg** [comment]
@norbusan - closing this one off

**Pull request closed without merging**
