### PR TITLE
 Make webhooks more resilient

### LINKED ISSUE #2501: Bug: Subscription ID already exists
### Describe the bug

Since yesterday my Onedrive Docker throws the error that the Subscription ID already exists.

### Operating System Details

```shell
unraid 6.12.4
docker: driveone/onedrive
```

### Client Installation Method

From Source

### OneDrive Account Type

Personal

### What is your OneDrive Application Version

driveone/onedrive:latest also tested driveone/onedrive:edge

### What is your OneDrive Application Configuration

```shell
log_dir = "/onedrive/conf/"
check_nomount = "true"
check_nosync = "true"
enable_logging = "true"
sync_dir_permissions = "777"
sync_file_permissions = "777"
webhook_enabled = "true"
webhook_public_url = "https://odwhc.holzers.win/webhooks/chris"
webhook_listening_port = "8888"
```

### What is your 'curl' version

```shell
docker
```

### Where is your 'sync_dir' located

Local

### What are all your system 'mount points'

```shell
docker
```

### What are all your local file system partition types

```shell
docker
```

### How do you use 'onedrive'

docker in unraid 6.12.4

### Steps to reproduce the behaviour

launch the docker

### Complete Verbose Log Output

```shell
2023-Sep-26 11:27:42.5104818	[DEBUG] Testing network to ensure network connectivity to Microsoft OneDrive Service
2023-Sep-26 11:27:42.5175589	[DEBUG] Attempting to contact online service
2023-Sep-26 11:27:42.637326	[DEBUG] Shutting down HTTP engine as successfully reached OneDrive Online Service
2023-Sep-26 11:27:42.6383093	Checking Application Version ...
2023-Sep-26 11:27:42.7523857	[DEBUG] applicationVersion:       2.4.25
2023-Sep-26 11:27:42.7529727	[DEBUG] latestVersion:            2.4.25
2023-Sep-26 11:27:42.7533218	[DEBUG] publishedDate:            2023-Jun-21 05:30:55Z
2023-Sep-26 11:27:42.7535557	[DEBUG] currentTime:              2023-Sep-26 09:27:42Z
2023-Sep-26 11:27:42.7538682	[DEBUG] releaseGracePeriod:       2023-Jul-21 05:30:55Z
2023-Sep-26 11:27:42.7540712	Initializing the OneDrive API ...
2023-Sep-26 11:27:42.754272	Configuring Global Azure AD Endpoints
2023-Sep-26 11:27:42.7545066	[DEBUG] Configured authUrl:          https://login.microsoftonline.com/common/oauth2/v2.0/authorize
2023-Sep-26 11:27:42.7546959	[DEBUG] Configured redirectUrl:      https://login.microsoftonline.com/common/oauth2/nativeclient
2023-Sep-26 11:27:42.7548835	[DEBUG] Configured tokenUrl:         https://login.microsoftonline.com/common/oauth2/v2.0/token
2023-Sep-26 11:27:42.7550958	[DEBUG] Configured driveUrl:         https://graph.microsoft.com/v1.0/me/drive
2023-Sep-26 11:27:42.7553116	[DEBUG] Configured driveByIdUrl:     https://graph.microsoft.com/v1.0/drives/
2023-Sep-26 11:27:42.7555307	[DEBUG] Configured sharedWithMeUrl:  https://graph.microsoft.com/v1.0/me/drive/sharedWithMe
2023-Sep-26 11:27:42.7557626	[DEBUG] Configured itemByIdUrl:      https://graph.microsoft.com/v1.0/me/drive/items/
2023-Sep-26 11:27:42.7559591	[DEBUG] Configured itemByPathUrl:    https://graph.microsoft.com/v1.0/me/drive/root:/
2023-Sep-26 11:27:42.7561936	[DEBUG] Configured siteSearchUrl:    https://graph.microsoft.com/v1.0/sites?search
2023-Sep-26 11:27:42.756464	[DEBUG] Configured siteDriveUrl:     https://graph.microsoft.com/v1.0/sites/
2023-Sep-26 11:27:42.7567057	Using Curl defaults for all HTTP operations
2023-Sep-26 11:27:42.7569992	[DEBUG] clientId    = d50ca740-c83f-4d1b-b616-12c519384f0c
2023-Sep-26 11:27:42.7572797	[DEBUG] companyName = abraunegg
2023-Sep-26 11:27:42.7575503	[DEBUG] appTitle    = OneDrive Client for Linux
2023-Sep-26 11:27:42.757979	Opening the item database ...
2023-Sep-26 11:27:42.7582986	[DEBUG] Using database file: /onedrive/conf/items.sqlite3
2023-Sep-26 11:27:42.7604776	[DEBUG] Configuring default new folder permissions as: 777
2023-Sep-26 11:27:42.7607703	[DEBUG] Configuring default new file permissions as: 777
2023-Sep-26 11:27:42.7610051	All operations will be performed in: /onedrive/data
2023-Sep-26 11:27:42.761434	[DEBUG] Configuring skip_dir ...
2023-Sep-26 11:27:42.7616736	[DEBUG] skip_dir: 
2023-Sep-26 11:27:42.7619268	[DEBUG] Configuring skip_dir_strict_match ...
2023-Sep-26 11:27:42.7621976	[DEBUG] skip_dir_strict_match: false
2023-Sep-26 11:27:42.7624334	[DEBUG] Configuring skip_dotfiles ...
2023-Sep-26 11:27:42.7626658	[DEBUG] skip_dotfiles: false
2023-Sep-26 11:27:42.7629174	[DEBUG] Configuring skip_file ...
2023-Sep-26 11:27:42.7631801	[DEBUG] skip_file: ~*|.~*|*.tmp
2023-Sep-26 11:27:43.2004052	[DEBUG] Setting file permissions for: /onedrive/conf/refresh_token
2023-Sep-26 11:27:43.2008548	[DEBUG] Request URL = https://graph.microsoft.com/v1.0/me/drive
2023-Sep-26 11:27:43.476277	[DEBUG] Request URL = https://graph.microsoft.com/v1.0/me/drive/root
2023-Sep-26 11:27:43.6164961	[DEBUG] OneDrive Account Details:      {"@odata.context":"https:\/\/graph.microsoft.com\/v1.0\/$metadata#drives\/$entity","driveType":"personal","id":"8a6dc48d52df7fda","owner":{"user":{"displayName":"Christian Holzer","id":"8a6dc48d52df7fda"}},"quota":{"deleted":1515180312,"remaining":1115156381696,"state":"normal","storagePlanInformation":{"upgradeAvailable":false},"total":1185410973696,"used":70254592000}}
2023-Sep-26 11:27:43.6185387	[DEBUG] OneDrive Account Root Details: {"@odata.context":"https:\/\/graph.microsoft.com\/v1.0\/$metadata#users('c.holzer%40live.at')\/drive\/root\/$entity","cTag":"adDo4QTZEQzQ4RDUyREY3RkRBITExNC42MzgzMTMxNjI3ODUzNzAwMDA","createdBy":{"user":{"displayName":"Christian Holzer","id":"8a6dc48d52df7fda"}},"createdDateTime":"2010-07-09T07:18:58.447Z","eTag":"aOEE2REM0OEQ1MkRGN0ZEQSExMTQuNzY","fileSystemInfo":{"createdDateTime":"2010-07-09T07:18:58.446Z","lastModifiedDateTime":"2023-06-11T10:54:07.38Z"},"folder":{"childCount":30,"view":{"sortBy":"name","sortOrder":"ascending","viewType":"thumbnails"}},"id":"8A6DC48D52DF7FDA!114","lastModifiedBy":{"application":{"displayName":"OneDrive website","id":"44048800"},"user":{"displayName":"Christian Holzer","id":"8a6dc48d52df7fda"}},"lastModifiedDateTime":"2023-09-26T09:11:18.537Z","name":"root","parentReference":{"driveId":"8a6dc48d52df7fda","driveType":"personal"},"root":{},"size":69400219432,"webUrl":"https:\/\/onedrive.live.com\/?cid=8a6dc48d52df7fda"}
2023-Sep-26 11:27:43.6189425	Application version: v2.4.25-11-g4a60654
2023-Sep-26 11:27:43.6192013	Account Type: personal
2023-Sep-26 11:27:43.6194876	Default Drive ID: 8a6dc48d52df7fda
2023-Sep-26 11:27:43.6196786	Default Root ID: 8A6DC48D52DF7FDA!114
2023-Sep-26 11:27:43.6199394	Remaining Free Space: 1115156381696
2023-Sep-26 11:27:43.6202135	Fetching details for OneDrive Root
2023-Sep-26 11:27:43.620424	[DEBUG] Request URL = https://graph.microsoft.com/v1.0/me/drive/root
2023-Sep-26 11:27:43.714789	OneDrive Root exists in the database
2023-Sep-26 11:27:43.7153179	Initializing the Synchronization Engine ...
2023-Sep-26 11:27:43.7159068	Initializing monitor ...
2023-Sep-26 11:27:43.7163124	OneDrive monitor interval (seconds): 300
2023-Sep-26 11:27:43.7167466	[DEBUG] Calling add() for this dirname: .
2023-Sep-26 11:27:43.7170215	[DEBUG] inotify_add_watch successfully added for: .
2023-Sep-26 11:27:43.7173778	Monitor directory: .
2023-Sep-26 11:27:43.717863	[DEBUG] Calling addRecursive() for this directory: ./Bilder
2023-Sep-26 11:27:43.7181234	[DEBUG] skip_dir evaluation for: /Bilder
2023-Sep-26 11:27:43.7183386	[DEBUG] No Strict Matching Enforced
2023-Sep-26 11:27:43.7185992	[DEBUG] Calling add() for this dirname: ./Bilder
2023-Sep-26 11:27:43.7188151	[DEBUG] inotify_add_watch successfully added for: ./Bilder
2023-Sep-26 11:27:43.7190344	Monitor directory: ./Bilder
2023-Sep-26 11:27:43.7194561	[DEBUG] Calling addRecursive() for this directory: ./Bilder/Eigene Aufnahmen
2023-Sep-26 11:27:43.7196636	[DEBUG] skip_dir evaluation for: /Bilder/Eigene Aufnahmen
2023-Sep-26 11:27:43.719893	[DEBUG] No Strict Matching Enforced
2023-Sep-26 11:27:43.7202156	[DEBUG] Calling add() for this dirname: ./Bilder/Eigene Aufnahmen
2023-Sep-26 11:27:43.7204661	[DEBUG] inotify_add_watch successfully added for: ./Bilder/Eigene Aufnahmen
2023-Sep-26 11:27:43.7206951	Monitor directory: ./Bilder/Eigene Aufnahmen

2023-Sep-26 11:27:44.5695875	Initializing subscription for updates ...
2023-Sep-26 11:27:45.4766561	ERROR: Microsoft OneDrive API returned an error with the following message:
2023-Sep-26 11:27:45.4772176	  Error Message:    HTTP request returned status code 409 (Conflict)
2023-Sep-26 11:27:45.4775438	[DEBUG] Raw Error Data: HTTP request returned status code 409 (Conflict)
{
    "error": {
        "code": "ObjectIdentifierInUse",
        "innerError": {
            "client-request-id": "615af209-467a-4ab7-8eff-27c1d1efbc2d",
            "date": "2023-09-26T09:27:45",
            "request-id": "615af209-467a-4ab7-8eff-27c1d1efbc2d"
        },
        "message": "Subscription Id c0bba80e-57a3-43a7-bac2-e6f525a76e7c already exists for the requested combination"
    }
}
2023-Sep-26 11:27:45.478451	[DEBUG] JSON Message: {"error":{"code":"ObjectIdentifierInUse","innerError":{"client-request-id":"615af209-467a-4ab7-8eff-27c1d1efbc2d","date":"2023-09-26T09:27:45","request-id":"615af209-467a-4ab7-8eff-27c1d1efbc2d"},"message":"Subscription Id c0bba80e-57a3-43a7-bac2-e6f525a76e7c already exists for the requested combination"}}
2023-Sep-26 11:27:45.4788614	  Error Reason:     Subscription Id c0bba80e-57a3-43a7-bac2-e6f525a76e7c already exists for the requested combination
2023-Sep-26 11:27:45.4791233	  Error Timestamp:  2023-09-26T09:27:45
2023-Sep-26 11:27:45.4793682	  API Request ID:   615af209-467a-4ab7-8eff-27c1d1efbc2d
2023-Sep-26 11:27:45.4796554	  Calling Function: createSubscription()

2023-Sep-26 11:27:45.4798751	ERROR: Unable to initialize subscriptions for updates. Please fix this issue.
2023-Sep-26 11:27:46.0325755	[DEBUG] Testing network to ensure network connectivity to Microsoft OneDrive Service
2023-Sep-26 11:27:46.0401462	[DEBUG] Attempting to contact online service
2023-Sep-26 11:27:46.1674872	[DEBUG] Shutting down HTTP engine as successfully reached OneDrive Online Service
```

### Screenshots

_No response_

### Other Log Information or Details

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Lyncredible**
* Do not quit on subscription API errors. Instead, wait a configurable interval before retrying.
* Shorten default webhook expiration and renewal intervals to reduce the chance of http 409 errors.
* Handle http 409 on subscription creation by taking over the existing subscription.
* Handle http 404 on subscription renewal by creating a new subscription(current behavior, listed for completeness).
* Log other known http errors include 400 (bad webhook endpoint), 401 (auth failed), and 403 (too many subscriptions).
* Log detailed messages when encoutering unknown http errors to assist with future debugging.

Fixes #2501

### CODE REVIEW

**Comment by Lyncredible** [comment]
@abraunegg It is probably easier to review this with `?w=1` appended to the URL to ignore whitespace changes. My editor does not like trailing whitespaces as usual :-P

**Comment by abraunegg** [comment]
@Lyncredible 
Thanks for your PR, however I am *not* going to add this into v2.4.

Webhooks is still missing from v2.5 branch, due to be added back in shortly, so what I will do, once those changes are added back in, circle back and either cherry pick your changes or ask you to re-work your PR to align to v2.5

**Comment by Lyncredible** [comment]
@abraunegg Sounds good. Take your time.

My local box is already running on this PR (on top of 4a60654 in `master`). It has been working well, but let me know if you want me to also test this on a different branch/commit.

**Comment by abraunegg** [comment]
@Lyncredible 

The 'alpha-2' PR (https://github.com/abraunegg/onedrive/pull/2505) is just about 'feature parity complete' - with the exception of adding back in webhooks.

I am going to start doing that tomorrow or the next day as part of 'alpha-3' - but it would be great once that lands if you can review and/or test to ensure that things are working correctly.

**Comment by abraunegg** [comment]
@Lyncredible 
Please can you review comments in #2520

**Comment by abraunegg** [comment]
@Lyncredible 
Please can you validate 'alpha-4' and if this is all OK, close this PR ?

**Comment by Lyncredible** [comment]
@abraunegg It has been working fine for the last ~12 hours. Closing this PR. Thanks for incorporating the fix!

**Comment by abraunegg** [comment]
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

**Pull request closed without merging**
