### PR TITLE
Update Sharepoint modified file handling for files > 4Mb in size

### PR DESCRIPTION
**Pull request by abraunegg**
* Update Sharepoint modified file handling for files > 4Mb in size

### CODE REVIEW

**Comment by abraunegg** [comment]
**without patch**
```
Using Config Dir: /home/alex/.config/onedrive-sharepoint
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDriveSharePoint
Initializing the Synchronization Engine ...
Application version: v2.3.7-17-gb23390c
Account Type: documentLibrary
Default Drive ID: b!QMiiVyjynUC_UIBZ4WaV8UveUfEgF9BGseBAWSULEb7n4JeIvgOVR4zlieNatYHC
Default Root ID: 017YXNCTF6Y2GOVW7725BZO354PWSELRRZ
Remaining Free Space: 27487755496712
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from OneDrive ...
Applying changes of Path ID: 017YXNCTF6Y2GOVW7725BZO354PWSELRRZ
Uploading differences of .
Processing root
The directory has not changed
Processing Intel
The directory has not changed
Processing gp
The directory has not changed
Processing Logs
The directory has not changed
Processing IntelUSB3.log
The file has not changed
Processing newfile.docx
The file has not changed
Processing test.txt
The file has not changed
Processing Multimedia Archive.xlsx
The file has not changed
Processing testfile.csv
The file has not changed
Processing largefile.docx
The file last modified time has changed
The file content has changed
Uploading modified file largefile.docx ... skipped.
Skip Reason: Microsoft Sharepoint 'enrichment' after upload issue
See: https://github.com/OneDrive/onedrive-api-docs/issues/935 for further details
Uploading new items of .
Requested file to upload exists on OneDrive - local database is out of sync for this file: ./largefile.docx
Requested file to upload is newer than existing file on OneDrive
Uploading modified file ./largefile.docx ...Retry sync count: 1: HTTP request returned status code 413 (Request Entity Too Large)
{
    "error": {
        "code": "BadRequest",
        "innerError": {
            "date": "2019-07-16T08:19:49",
            "request-id": "c54ae1a0-426c-43b8-9f11-309f71033e37"
        },
        "message": "Maximum request length exceeded."
    }
}
Syncing changes from OneDrive ...
Applying changes of Path ID: 017YXNCTF6Y2GOVW7725BZO354PWSELRRZ
Uploading differences of .
Processing root
The directory has not changed
Processing Intel
The directory has not changed
Processing gp
The directory has not changed
Processing Logs
The directory has not changed
Processing IntelUSB3.log
The file has not changed
Processing newfile.docx
The file has not changed
Processing test.txt
The file has not changed
Processing Multimedia Archive.xlsx
The file has not changed
Processing testfile.csv
The file has not changed
Uploading new items of .
Requested file to upload exists on OneDrive - local database is out of sync for this file: ./largefile.docx
Requested file to upload is newer than existing file on OneDrive
Uploading modified file ./largefile.docx ...Retry sync count: 2: HTTP request returned status code 413 (Request Entity Too Large)
{
    "error": {
        "code": "BadRequest",
        "innerError": {
            "date": "2019-07-16T08:19:50",
            "request-id": "33f50b9e-469b-4ae9-bf0f-fe7e2bd8ca07"
        },
        "message": "Maximum request length exceeded."
    }
}
Syncing changes from OneDrive ...
Applying changes of Path ID: 017YXNCTF6Y2GOVW7725BZO354PWSELRRZ
Uploading differences of .
Processing root
The directory has not changed
Processing Intel
The directory has not changed
Processing gp
The directory has not changed
Processing Logs
The directory has not changed
Processing IntelUSB3.log
The file has not changed
Processing newfile.docx
The file has not changed
Processing test.txt
The file has not changed
Processing Multimedia Archive.xlsx
The file has not changed
Processing testfile.csv
The file has not changed
Uploading new items of .
Requested file to upload exists on OneDrive - local database is out of sync for this file: ./largefile.docx
Requested file to upload is newer than existing file on OneDrive
Uploading modified file ./largefile.docx ...Giving up on sync after three attempts: HTTP request returned status code 413 (Request Entity Too Large)
{
    "error": {
        "code": "BadRequest",
        "innerError": {
            "date": "2019-07-16T08:19:51",
            "request-id": "56447ef4-ea88-4d8e-b634-1234ceba67d0"
        },
        "message": "Maximum request length exceeded."
    }
}
onedrive.OneDriveException@src/onedrive.d(813): HTTP request returned status code 413 (Request Entity Too Large)
{
    "error": {
        "code": "BadRequest",
        "innerError": {
            "date": "2019-07-16T08:19:51",
            "request-id": "56447ef4-ea88-4d8e-b634-1234ceba67d0"
        },
        "message": "Maximum request length exceeded."
    }
}
----------------
src/onedrive.d:51 void onedrive.OneDriveApi.checkHttpCode(ref const(std.json.JSONValue)) [0x5f383e]
src/onedrive.d:578 std.json.JSONValue onedrive.OneDriveApi.upload(immutable(char)[], immutable(char)[]) [0x5f2e01]
src/onedrive.d:259 std.json.JSONValue onedrive.OneDriveApi.simpleUploadReplace(immutable(char)[], immutable(char)[], immutable(char)[], const(char)[]) [0x5f15f3]
src/sync.d:2300 void sync.SyncEngine.uploadNewFile(immutable(char)[]) [0x607159]
src/sync.d:1894 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x60528e]
src/sync.d:1878 void sync.SyncEngine.uploadNewItems(immutable(char)[]) [0x6050e9]
src/sync.d:1362 void sync.SyncEngine.scanForDifferences(immutable(char)[]) [0x60315d]
src/main.d:623 void main.performSync(sync.SyncEngine, immutable(char)[], bool, bool, bool, long, bool) [0x5eef9b]
src/main.d:396 _Dmain [0x5ee351]
```

**with patch**
```
Using Config Dir: /home/alex/.config/onedrive-sharepoint
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDriveSharePoint
Initializing the Synchronization Engine ...
Application version: v2.3.7-17-gb23390c
Account Type: documentLibrary
Default Drive ID: b!QMiiVyjynUC_UIBZ4WaV8UveUfEgF9BGseBAWSULEb7n4JeIvgOVR4zlieNatYHC
Default Root ID: 017YXNCTF6Y2GOVW7725BZO354PWSELRRZ
Remaining Free Space: 27487761765456
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from OneDrive ...
Applying changes of Path ID: 017YXNCTF6Y2GOVW7725BZO354PWSELRRZ
Uploading differences of .
Processing root
The directory has not changed
Processing Intel
The directory has not changed
Processing gp
The directory has not changed
Processing Logs
The directory has not changed
Processing IntelUSB3.log
The file has not changed
Processing newfile.docx
The file has not changed
Processing test.txt
The file has not changed
Processing Multimedia Archive.xlsx
The file has not changed
Processing testfile.csv
The file has not changed
Processing largefile.docx
The file last modified time has changed
The file content has changed
Uploading modified file largefile.docx ... skipped.
Skip Reason: Microsoft Sharepoint 'enrichment' after upload issue
See: https://github.com/OneDrive/onedrive-api-docs/issues/935 for further details
Uploading new items of .
Requested file to upload exists on OneDrive - local database is out of sync for this file: ./largefile.docx
Requested file to upload is newer than existing file on OneDrive
Uploading modified file ./largefile.docx ...
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:05                                                                                                              
 done.
Due to Microsoft Sharepoint 'enrichment' of files, downloading 'enriched' file to ensure local file is in-sync
See: https://github.com/OneDrive/onedrive-api-docs/issues/935 for further details

Downloading 100% |oooooooooooooooooooooooooooooooooooooooo| DONE IN 00:00:03                                                                                                            
Remaining free space: 27487755497552
Applying changes of Path ID: 017YXNCTF6Y2GOVW7725BZO354PWSELRRZ
```

**Comment by theeggdev** [comment]
@abraunegg 

1. .csv and .txt files: modified files are uploaded successfully 
2. .xlsx files <4MB: modified files are uploaded successfully, version history are kept
3. .xlsx files >4MB: the uploaded file is broken (returns to me a file of 656KB and OneDrive is telling me the file is corrupted) 
But it looks normal in the `systemctl status --user onedrive`
```
Jul 16 18:26:15 egghkdev onedrive[15388]: Uploading modified file project management/A/automated reports/budget/Budget Tracker.xlsx ... skipped.
Jul 16 18:26:17 egghkdev onedrive[15388]: Uploading modified file ./project management/A/automated reports/budget/Budget Tracker.xlsx ... done.
```
sorry I can only work on this tomorrow (+0800). will get back to with any log that you need by then!

**Comment by theeggdev** [comment]
@abraunegg
Tested on 2 large .xlsx files (9.36MB, 4.92MB); 
Tested on 2 small .xlsx files (15.1KB, 23.7KB) 

The 2 large files were deleted and recreated, 
the 2 small files had modification uploaded, and their version history was kept. 

looks good to me 
the previous error might be due to other things perhaps... ? 

Anyway thanks!

**Comment by abraunegg** [comment]
@theeggdev 
> the uploaded file is broken (returns to me a file of 656KB and OneDrive is telling me the file is corrupted)

The session upload for some reason would have failed. It might be best to bump your logging level up by 1 (by including --verbose) so that you get a little more details as to what is going on with uploads when they fail.

Glad that further testing showed no issue.

**Pull request merged**
