### PR TITLE
Update skip_dir pattern matching when using wildcards (Issue #689)

### PR DESCRIPTION
**Pull request by abraunegg**
* Better handle skip_dir searching when wildcards are involved by passing in a better 'path' snippet from which to compare skip_dir entries against

### CODE REVIEW

**Comment by abraunegg** [comment]
**config:**
```
onedrive version                    = v2.3.10-7-g9d0a653
Config path                         = /home/alex/.config/onedrive-personal/
Config file found in config path    = true
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /home/alex/OneDrivePersonal
Config option 'skip_dir'            = Anexos de email|ComputaÃ§|Cornell/Fall 2015-2016|Cornell/2016*|Cornell/2017*|Cornell/2018*|Cornell/2019 S*|Cornell/Artigos|Cornell/Fields for minor|Cornell/Others/Alex/22 ICB/website/Freelancer/website_*|Cornell/Project/TLM/Netbeans/V05/tlmbht/docs/doxygen/html|Cornell/Project/TLM/Netbeans/V05/tlmbht/docs/doxygen/latex|Cornell/Publications/2018/Piglets 2013/code|Documentos|Documents|Doutorado|MaiaFR|Mestrado|Outros/Experimento Julho 2016|Imagens/Imagens da CÃ¢ra/HVL|Imagens/Imagens da CÃ¢ra/200*|Imagens/Imagens da CÃ¢ra/2010|Imagens/Imagens da CÃ¢ra/2011|Imagens/Imagens da CÃ¢ra/2012|Imagens/Imagens da CÃ¢ra/2013|Imagens/Imagens da CÃ¢ra/2014|Imagens/Imagens da CÃ¢ra/2015|Imagens/Imagens da CÃ¢ra/2016|Imagens/Imagens da CÃ¢ra/2017|Imagens/Imagens da CÃ¢ra/2018|Imagens/Imagens da CÃ¢ra/Outros|Imagens/Imagens da CÃ¢ra/photogrammetry|Imagens/Capturas de tela|Imagens/Imagens salvas
Config option 'skip_file'           = ~*|.~*|*.tmp|campov*
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Config option 'sync_root_files'     = false
Selective sync configured           = false
```

**without patch:**
`Cornell/2017 Spring` & `Cornell/2017 Spring` should not have been downloaded
```
Using Config Dir: /home/alex/.config/onedrive-personal/
Deleting the saved status ...
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDrivePersonal
Application version: v2.3.10-7-g9d0a653
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 5354469671
Fetching details for OneDrive Root
OneDrive Root does not exist in the database. We need to add it.
Added OneDrive Root to the local database
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Applying changes of Path ID: 66D53BE8A5056ECA!101
Processing 16 changes
Creating directory: Cornell
Creating directory: 10-Files
Creating directory: 10-Files/Cisco VDI Whitepaper
Creating directory: 10-Files/Architecture Layres
Creating directory: Cornell/2017 Spring
Creating directory: Cornell/2016 Spring
Downloading file 10-Files/Cisco VDI Whitepaper/white_paper_c11-494994.pdf ... done.
Skipping item - excluded by skip_file config: campover.pdf
Downloading file 10-Files/Architecture Layres/architecture layers v0.4 - AB.vsd ... done.
Creating directory: Cornell/2017 Spring/SMPP
Downloading file Cornell/2016 Spring/IMG_2919.JPG ... done.
Downloading file Cornell/2016 Spring/IMG_2920.JPG ... done.
Downloading file Cornell/2017 Spring/SMPP/SMPP-IF-SPEC_v3_3-24858.pdf ... done.
Downloading file Cornell/2017 Spring/SMPP/SMPP_v3_4_Issue1_2-24857.pdf ... done.
Uploading differences of .
Processing root
The directory has not changed
Processing Cornell
The directory has not changed
Processing 2017 Spring
The directory has not changed
Processing SMPP
The directory has not changed
Processing SMPP-IF-SPEC_v3_3-24858.pdf
The file has not changed
Processing SMPP_v3_4_Issue1_2-24857.pdf
The file has not changed
Processing 2016 Spring
The directory has not changed
Processing IMG_2919.JPG
The file has not changed
Processing IMG_2920.JPG
The file has not changed
Processing 10-Files
The directory has not changed
Processing Cisco VDI Whitepaper
The directory has not changed
Processing white_paper_c11-494994.pdf
The file has not changed
Processing Architecture Layres
The directory has not changed
Processing architecture layers v0.4 - AB.vsd
The file has not changed
Uploading new items of .
Skipping item - excluded by skip_dir config: ./Cornell/2017 Spring
Skipping item - excluded by skip_dir config: ./Cornell/2016 Spring
Applying changes of Path ID: 66D53BE8A5056ECA!101
```

**with patch:**
```
Using Config Dir: /home/alex/.config/onedrive-personal/
Deleting the saved status ...
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDrivePersonal
Application version: v2.3.10-7-g9d0a653
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 5354469671
Fetching details for OneDrive Root
OneDrive Root does not exist in the database. We need to add it.
Added OneDrive Root to the local database
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Applying changes of Path ID: 66D53BE8A5056ECA!101
Processing 16 changes
Creating directory: Cornell
Creating directory: 10-Files
Creating directory: 10-Files/Cisco VDI Whitepaper
Creating directory: 10-Files/Architecture Layres
Skipping item - excluded by skip_dir config match: Cornell/2017 Spring
Skipping item - excluded by skip_dir config match: Cornell/2016 Spring
Downloading file 10-Files/Cisco VDI Whitepaper/white_paper_c11-494994.pdf ... done.
Skipping item - excluded by skip_file config: campover.pdf
Downloading file 10-Files/Architecture Layres/architecture layers v0.4 - AB.vsd ... done.
Uploading differences of .
Processing root
The directory has not changed
Processing Cornell
The directory has not changed
Processing 10-Files
The directory has not changed
Processing Cisco VDI Whitepaper
The directory has not changed
Processing white_paper_c11-494994.pdf
The file has not changed
Processing Architecture Layres
The directory has not changed
Processing architecture layers v0.4 - AB.vsd
The file has not changed
Uploading new items of .
Applying changes of Path ID: 66D53BE8A5056ECA!101
```

**Comment by abraunegg** [comment]
Updated PR as matching was missing longer paths that should have also been skipped:
```
Using Config Dir: /home/alex/.config/onedrive-personal/
Deleting the saved status ...
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDrivePersonal
Application version: v2.3.10-10-g2848333
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 5346551393
Fetching details for OneDrive Root
OneDrive Root does not exist in the database. We need to add it.
Added OneDrive Root to the local database
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Applying changes of Path ID: 66D53BE8A5056ECA!101
Processing 38 changes
Creating directory: 10-Files
Creating directory: Cornell
Creating directory: 10-Files/Architecture Layres
Skipping item - excluded by skip_dir config match: Cornell/2016 Spring
Creating directory: 10-Files/Cisco VDI Whitepaper
Skipping item - excluded by skip_dir config match: Cornell/2017 Spring
Creating directory: Cornell/Others
Downloading file 10-Files/Architecture Layres/architecture layers v0.4 - AB.vsd ... done.
Downloading file 10-Files/Cisco VDI Whitepaper/white_paper_c11-494994.pdf ... done.
Downloading file 10-Files/Cisco VDI Whitepaper/campover.pdf ... done.
Creating directory: Cornell/Others/John
Creating directory: Cornell/Others/Alex
Creating directory: Cornell/Others/Alex/22 ABC
Creating directory: Cornell/Others/Alex/22 ICB
Creating directory: Cornell/Others/Alex/22 ABC/SMPP
Creating directory: Cornell/Others/Alex/22 ICB/server
Creating directory: Cornell/Others/Alex/22 ICB/website
Downloading file Cornell/Others/Alex/22 ABC/SMPP/SMPP-IF-SPEC_v3_3-24858.pdf ... done.
Downloading file Cornell/Others/Alex/22 ABC/SMPP/SMPP_v3_4_Issue1_2-24857.pdf ... done.
Creating directory: Cornell/Others/Alex/22 ICB/server/Architecture Layres
Creating directory: Cornell/Others/Alex/22 ICB/website/Contractor
Creating directory: Cornell/Others/Alex/22 ICB/website/Freelancer
Downloading file Cornell/Others/Alex/22 ICB/server/Architecture Layres/architecture layers v0.4 - AB.vsd ... done.
Creating directory: Cornell/Others/Alex/22 ICB/website/Contractor/Cisco VDI Whitepaper
Skipping item - excluded by skip_dir config match: Cornell/Others/Alex/22 ICB/website/Freelancer/website_
Creating directory: Cornell/Others/Alex/22 ICB/website/Freelancer/server_
Downloading file Cornell/Others/Alex/22 ICB/website/Contractor/Cisco VDI Whitepaper/white_paper_c11-494994.pdf ... done.
Downloading file Cornell/Others/Alex/22 ICB/website/Contractor/Cisco VDI Whitepaper/campover.pdf ... done.
Downloading file Cornell/Others/Alex/22 ICB/website/Freelancer/server_/pkg order to add.txt ... done.
Uploading differences of .
Processing root
The directory has not changed
Processing 10-Files
The directory has not changed
Processing Architecture Layres
The directory has not changed
Processing architecture layers v0.4 - AB.vsd
The file has not changed
Processing Cisco VDI Whitepaper
The directory has not changed
Processing white_paper_c11-494994.pdf
The file has not changed
Processing campover.pdf
The file has not changed
Processing Cornell
The directory has not changed
Processing Others
The directory has not changed
Processing John
The directory has not changed
Processing Alex
The directory has not changed
Processing 22 ABC
The directory has not changed
Processing SMPP
The directory has not changed
Processing SMPP-IF-SPEC_v3_3-24858.pdf
The file has not changed
Processing SMPP_v3_4_Issue1_2-24857.pdf
The file has not changed
Processing 22 ICB
The directory has not changed
Processing server
The directory has not changed
Processing Architecture Layres
The directory has not changed
Processing architecture layers v0.4 - AB.vsd
The file has not changed
Processing website
The directory has not changed
Processing Contractor
The directory has not changed
Processing Cisco VDI Whitepaper
The directory has not changed
Processing white_paper_c11-494994.pdf
The file has not changed
Processing campover.pdf
The file has not changed
Processing Freelancer
The directory has not changed
Processing server_
The directory has not changed
Processing pkg order to add.txt
The file has not changed
Uploading new items of .
Applying changes of Path ID: 66D53BE8A5056ECA!101
```

**Comment by abraunegg** [comment]
@norbusan 
Any update in reviewing this PR? Issue report has successfully tested this fix.

**Comment by norbusan** [comment]
I'll do it later today probably. Sorry forgot about it

**Pull request merged**
