### PR TITLE
Update sync.d

### PR DESCRIPTION
**Pull request by abraunegg**
* Add a check to validate if 'size' is in the JSON response

### CODE REVIEW

**Comment by abraunegg** [comment]
Fixes issue #420, using patch locally to assist with uploading 50K files

**Comment by norbusan** [comment]
Looking at the diff with whitespace removed, the only changes is protecting the code with a check whether `size` is available, correct? But do we do anything when size is not available?

**Comment by abraunegg** [comment]
No we do not - as the only reason why size would not be available, would be that an error was generated. As per the crash I was getting - I was getting a 5xx error from OneDrive, which is handled correctly, but the non data in 'response' was not - this fixes that.

If the data is not there, then we cant add the entry to the DB - which makes sense - as we have no data to add due to the 4xx or 5xx error

**Comment by norbusan** [comment]
Thanks, and sorry for the unclear question, I meant, *should* we do something in case of missing size, like warning? Or is this handled transparently on the next sync?

Anyway, it compiles and works, and I cannot trigger such an response, so fine with me.

**Pull request merged**
