### PR TITLE
Use %h instead of /home/%i in onedrive@.service file

### PR DESCRIPTION
**Pull request by norbusan**
Home directories might not be located in /home. %h expands to
the home directory of the respective user.

### CODE REVIEW

**Comment by abraunegg** [comment]
@norbusan 
I have emailed the original author of this file for comments / feedback. I see no issue here, but just want their feedback as well as %i was needed to correctly get this running for the user id.

**Comment by abraunegg** [comment]
@norbusan 
from @sbocquet
```
I’ve just tested the change but it seems that the %h is not replaced by the home dir.

Here is some logs after restarting the service

root@home-server:~# service onedrive@sbocquet status
● onedrive@sbocquet.service - OneDrive Free Client for sbocquet
   Loaded: loaded (/lib/systemd/system/onedrive@.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2019-04-24 23:42:12 CEST; 2s ago
     Docs: https://github.com/abraunegg/onedrive
  Process: 24658 ExecStart=/usr/local/bin/onedrive --monitor --enable-logging --confdir=///sbocquet/.config/onedrive (code=exited, status=1/FAILURE)
Main PID: 24658 (code=exited, status=1/FAILURE)

I have to do more research to know if this is a correct syntax…
```

**Comment by norbusan** [comment]
What version of systemd was that? The documentation here https://www.freedesktop.org/software/systemd/man/systemd.unit.html clearly states that it should work...

**Comment by abraunegg** [comment]
@sbocquet
Can you advise what version of systemd your system is running?

**Comment by norbusan** [comment]
Ok, it seems that - despite everything written - expansions in `ExecStart` are not supported, and if, only `%i`. There is no definitive answer in the man pages and docs, and several issues and bug reports.

A typical systemd case, devs don't care ...

Closing this pull request.

**Comment by norbusan** [comment]
I sent a bug report to Debian - I don't interact with upstream systemd, too many bad experiences.

**Pull request closed without merging**
