### PR TITLE
change to docopt as option parser (Issue #298)

### PR DESCRIPTION
**Pull request by norbusan**
Instead of using the auto-generated help message from getopt,
use docopt style help message and use the docopt command line
parser.

### CODE REVIEW

**Comment by abraunegg** [comment]
Interesting result:

```
./onedrive --confdir '~/.config/onedrive-personal' --display-sync-status --verbose --verbose
[DEBUG] homePath: HOME environment variable set
[DEBUG] homePath: /home/alex
[DEBUG] configDirBase: WARNING - no XDG_CONFIG_HOME environment variable set
[DEBUG] configDirBase: /home/alex/.config
[DEBUG] configDirName: CLI override to set configDirName to: ~/.config/onedrive-personal
[DEBUG] configDirName: A '~' was found in configDirName, using the calculated 'homePath' to replace '~'
Loading config ...
Using Config Dir: /home/alex/.config/onedrive-personal
No config file found, using application defaults
[DEBUG] sync_dir: Getting syncDir from config value sync_dir
[DEBUG] sync_dir: A '~' was found in configured sync_dir, automatically expanding as SHELL and USER environment variable is set
[DEBUG] syncDir: /home/alex/OneDrive
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDrive
Initializing the Synchronization Engine ...
Account Type: personal
Default Drive ID: <redacted>
Default Root ID: <redacted>
Remaining Free Space: 5368709120
Fetching details for OneDrive Root
OneDrive Root exists in the database
Attempting to delete the requested path within OneDrive
The requested directory to delete was not found on OneDrive - skipping removing the remote directory as it doesn't exist
Local directory is out of sync with OneDrive
```
same command with current master:
```
./onedrive --confdir '~/.config/onedrive-personal' --display-sync-status --verbose --verbose
[DEBUG] homePath: HOME environment variable set
[DEBUG] homePath: /home/alex
[DEBUG] configDirBase: WARNING - no XDG_CONFIG_HOME environment variable set
[DEBUG] configDirBase: /home/alex/.config
[DEBUG] configDirName: CLI override to set configDirName to: ~/.config/onedrive-personal
[DEBUG] configDirName: A '~' was found in configDirName, using the calculated 'homePath' to replace '~'
Loading config ...
Using Config Dir: /home/alex/.config/onedrive-personal
No config file found, using application defaults
[DEBUG] sync_dir: Getting syncDir from config value sync_dir
[DEBUG] sync_dir: A '~' was found in configured sync_dir, automatically expanding as SHELL and USER environment variable is set
[DEBUG] syncDir: /home/alex/OneDrive
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDrive
Initializing the Synchronization Engine ...
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 5368709120
Fetching details for OneDrive Root
OneDrive Root exists in the database
Local directory is out of sync with OneDrive
```

For some reason, one of the default 'variables' is being parsed incorrectly.  The 'log' message can only come from onedrive.deleteDirectoryNoSync(), so it would be worth checking all of the variable initialisation so that in main.d (lines 426 to 444) we are not trying to create / delete or move a directory without request.

**Comment by norbusan** [comment]
Arrggg, indeed -- null versus "" it is ...

**Comment by norbusan** [comment]
Aahh, something else. @abraunegg I forgot to add the `ARG` to `--remove-directory` and then force-pushed an update, but you did built from the previous one (check the --remove-directory doc string):

Here I get
```
./onedrive --confdir '~/.config/onedrive-test' --display-sync-status --verbose --verbose
[DEBUG] homePath: HOME environment variable set
[DEBUG] homePath: /home/norbert
[DEBUG] configDirBase: WARNING - no XDG_CONFIG_HOME environment variable set
[DEBUG] configDirBase: /home/norbert/.config
[DEBUG] configDirName: CLI override to set configDirName to: ~/.config/onedrive-test
[DEBUG] configDirName: A '~' was found in configDirName, using the calculated 'homePath' to replace '~'
Loading config ...
Using Config Dir: /home/norbert/.config/onedrive-test
[DEBUG] sync_dir: Getting syncDir from config value sync_dir
[DEBUG] syncDir: /home/norbert/OneDriveTest
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/norbert/OneDriveTest
Initializing the Synchronization Engine ...
Account Type: personal
Default Drive ID: d6ebf6b564426b61
Default Root ID: D6EBF6B564426B61!101
Remaining Free Space: 5368662305
Fetching details for OneDrive Root
OneDrive Root exists in the database
[DEBUG] createDirector =  removeDirectory = 
No pending remote changes - in sync
```

**Comment by norbusan** [comment]
But more problematic, it seems that on most architecture the dmd compiler does not really work out well :-( and gives strange regexp warning ... that is not good ...

**Comment by norbusan** [comment]
I think I will drop this docopt completely due to compiler problems. Seems not worth the pain.

I will work on a different way to print out the stuff manually.

WDYT @abraunegg

**Comment by abraunegg** [comment]
Agreed

**Comment by norbusan** [comment]
As discussed, the docopt creates compiler problems (see travis build errors), thus closing the PR

**Pull request closed without merging**
