### PR TITLE
Updated alpine to 3.14

### PR DESCRIPTION
**Pull request by MarcelCoding**
Alpine 3.13 has an outdatet go version: https://pkgs.alpinelinux.org/packages?name=go&branch=v3.13
[onedrive_outdatet_go.log](https://github.com/abraunegg/onedrive/files/7597101/onedrive_outdatet_go.log)

PS: please squash this pr

### CODE REVIEW

**Comment by abraunegg** [comment]
@MarcelCoding 
> PS: please squash this pr

What do you mean here - do not merge or merge or something else ? 

Please clarify

**Comment by MarcelCoding** [comment]
I mean don't merge or rebase but do a squash because my commit messages are not so helpful

**Comment by MarcelCoding** [comment]
The actions are probably not running because this is an fork and not an branch.

**Comment by abraunegg** [comment]
@MarcelCoding 
> The actions are probably not running because this is an fork and not an branch.

No - this is because Docker has changed their policy that only 'paid' accounts can auto build stuff / trigger auto builds.

**Comment by MarcelCoding** [comment]
I you wan't you can use my actions. I only created my repo, because you don't provide Images on DockerHub for all variants and you didn't responded in https://github.com/abraunegg/onedrive/discussions/1401.

**Comment by abraunegg** [comment]
@MarcelCoding 
What I need to do is update to use actions here, so that then these can be published / pushed to Docker.

Happy to setup a conference | meeting to go through this when convenient (I am a little busy with work atm)

**Comment by MarcelCoding** [comment]
Sure we can schedule as meeting, just mail me at mail (at) m4rc3l (dot) de

**Comment by nrandon** [comment]
@abraunegg can you not do this: https://www.docker.com/community/open-source/application

**Pull request merged**
