### PR TITLE
Fix unhandled error exceptions that cause application to exit / crash when uploading files (Issue #624)

### PR DESCRIPTION
**Pull request by abraunegg**
* remove 'else throw e' which causes the application to exit / crash and replace with what the actual error message is from OneDrive

### CODE REVIEW

**Comment by abraunegg** [comment]
@norbusan 
Without this patch, when uploading to OneDrive with a personal account sometimes OneDrive returns a 401 error which does not get handled. Finally able to reproduce this when testing this PR:
```
Uploading new file ./random_files_2/random_files_dir_set_1/7BeaLQ0WlcxJFtZ6hWER1InpEs4nME7A/file904.data ... done.
Remaining free space: 4690224151
Uploading new file ./random_files_2/random_files_dir_set_1/7BeaLQ0WlcxJFtZ6hWER1InpEs4nME7A/file955.data ...ERROR: OneDrive returned a 'HTTP 401 - Unauthorized' - gracefully handling error
Uploading new file ./random_files_2/random_files_dir_set_1/7BeaLQ0WlcxJFtZ6hWER1InpEs4nME7A/file812.data ... done.
Remaining free space: 4690210807
Uploading new file ./random_files_2/random_files_dir_set_1/7BeaLQ0WlcxJFtZ6hWER1InpEs4nME7A/file203.data ... done.
Remaining free space: 4690180224
```

**Comment by abraunegg** [comment]
Fix this sort of issue as well:
```
Remaining free space: 4648337423
Uploading new file ./random_files_2/random_files_dir_set_1/VZfhaIwH60BG0ik4kRw4ZX5rc4DIXuub/file280.data ...OneDrive returned a 'HTTP 503 Service Unavailable Error' - gracefully handling error
 done.
ERROR: An error was returned from OneDrive and the resulting response is not a valid JSON object
ERROR: Increase logging verbosity to assist determining why.
Remaining free space: 4648333814
Uploading new file ./random_files_2/random_files_dir_set_1/VZfhaIwH60BG0ik4kRw4ZX5rc4DIXuub/file986.data ... done.
```
The 503 should be handled, upload should be listed as skipped and logging output should not be jammed up together

**Comment by abraunegg** [comment]
Logging example with latest commit:
```
Uploading new file ./random_files_2/random_files_dir_set_3/6VEzVEgmf3nJAiNllq4tZpLd2v50HQHe/file399.data ... done.
Uploading new file ./random_files_2/random_files_dir_set_3/6VEzVEgmf3nJAiNllq4tZpLd2v50HQHe/file372.data ... skipped.

ERROR: OneDrive returned an error with the following message:
  Error Message: HTTP request returned status code 500 (Internal Server Error)
  Error Reason:  An error occurred in the data store.
Uploading new file ./random_files_2/random_files_dir_set_3/6VEzVEgmf3nJAiNllq4tZpLd2v50HQHe/file667.data ... done.
Uploading new file ./random_files_2/random_files_dir_set_3/6VEzVEgmf3nJAiNllq4tZpLd2v50HQHe/file947.data ... done.
Uploading new file ./random_files_2/random_files_dir_set_3/6VEzVEgmf3nJAiNllq4tZpLd2v50HQHe/file872.data ... done.
```

**Comment by norbusan** [comment]
@abraunegg I tried to restart the analysis, didn't work either. Something is strange wioth codacy atm.

**Pull request merged**
