### PR TITLE
Implement Blocking Logger Mechanism

### PR DESCRIPTION
**Pull request by JC-comp**
This PR introduces a blocking logger mechanism to replace the existing polling mechanism for enhanced efficiency and resource utilization. The new blocking logger ensures that log messages are processed synchronously, eliminating the need for continuous polling.

Changes
- Implementation of a blocking logger mechanism
- Remove redundent sleep for final ouput
- Adjust cleanup process

### CODE REVIEW

**Comment by abraunegg** [comment]
@JC-comp 
Unable to compile this PR:
```
clientSideFiltering.d src/monitor.d src/arsd/cgi.d -ofonedrive
src/log.d(95): Error: non-shared method core.sync.condition.Condition.notify is not callable using a shared object
src/log.d(95):        Consider adding shared to core.sync.condition.Condition.notify
```

Is there some sort of 'ordering' to your PR for sequencing .. as there is some 'shared' change in #2608

Please fix, so that this PR (and all your others) self compile correctly, so that when I am testing these PR's they can be tested before being implemented.

**Comment by JC-comp** [comment]
@abraunegg 
Please update the ldc compiler to at least version 1.23.0 as the shared feature has been introduced in this release.
Thank you.

**Comment by abraunegg** [comment]
@JC-comp 
Unfortunately using a more modern LDC compiler is not going to be possible ... why?

The issue stems from Debian and Ubuntu LTS versions - such as Ubuntu 20.04. It's [ldc package](https://packages.ubuntu.com/focal/ldc) is only v1.20.1 , thus, this is the minimum version that all compilation needs to be tested against. Why?

Because the distribution version of 'ldc' is used to compile the packages presented at the [OpenSuSE Build Service ](https://build.opensuse.org/package/show/home:npreining:debian-ubuntu-onedrive/onedrive)

This means, the minimum version of LDC that can be tested against against all of these, which right now is Ubuntu 20.04 which is LDC v1.20.1.

Currently I test against an even lower version (v1.18.0) because of even older architectures for [Raspberry Pi](https://www.raspberrypi.com/) operating systems.

So in your testing and building, you *must* test each PR separately, by itself, compiling against the minimum LDC version, using a script similar to the following (assuming you already know how to install 'ldc' manually, and can install v1.20.1):

```
#!/bin/bash
  
PR=2627

rm -rf ./onedrive-pr${PR}
git clone https://github.com/abraunegg/onedrive.git onedrive-pr${PR}
cd onedrive-pr${PR}
git fetch origin pull/${PR}/head:pr${PR}
git checkout pr${PR}

# MIN LDC Version to compile
# MIN Version for ARM / Compiling with LDC
#source ~/dlang/ldc-1.18.0/activate
source ~/dlang/ldc-1.20.1/activate


./configure --enable-debug --enable-notifications; make clean; make;
deactivate
./onedrive --version
```

When using this script, against your PR, it generates the following error:
```
src/log.d(95): Error: non-shared method core.sync.condition.Condition.notify is not callable using a shared object
src/log.d(95):        Consider adding shared to core.sync.condition.Condition.notify
```


You must make your code compatible with LDC v1.20.1 at a minimum.

**Comment by JC-comp** [comment]
Update
- Ensure backward compatibility with ldc v1.20.1 and test the compilation.

**Comment by abraunegg** [comment]
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

**Pull request merged**
