### PR TITLE
Implement 'skip_dir' config option (Issue #123)

### PR DESCRIPTION
**Pull request by abraunegg**
* Initial work on skip_dir implementation

### CODE REVIEW

**Comment by abraunegg** [comment]
Potentially code complete

Needs exhaustive testing

**Comment by norbusan** [comment]
First comment: I think this changes the semantics of the sync process compared to the current state. Now, `skip_file` also works for directories, so I exclude several directories using it. I *believe* (not tested though) that with this change directories will not be ignored anymore via `skip_file`.

Is this correct? And do we want to make this semantical change?

**Comment by abraunegg** [comment]
> First comment: I think this changes the semantics of the sync process compared to the current state. Now, `skip_file` also works for directories, so I exclude several directories using it. I _believe_ (not tested though) that with this change directories will not be ignored anymore via `skip_file`.
> 
> Is this correct? And do we want to make this semantical change?

Correct. The current 'skip_file' skips both files and directories (technically all directories are files) and yes, this does split this out so that 'file' and 'directories' - so it is a semantic change to how the client operates.

This commit is key: https://github.com/abraunegg/onedrive/pull/388/commits/91e2ca408706c441d2a843b3e0c5793f97a04468

If we want to 'retain' the existing functionality, what we would do is remove the `if (isFile(path)) {` check, which would then essentially leave a potential solution where an exclusion for a directory is handled in 'skip_dir' and 'skip_file'

Happy to also skip including this in the 2.2.6 release and push to 2.3.0 given functionality change

**Comment by norbusan** [comment]
Hi

with the semantic change, I guess it is also necessary that everyone using `skip_file` for directories will probably need to run `--resync`, just for safety, right?

Considering all this, ...

> Happy to also skip including this in the 2.2.6 release and push to 2.3.0 given functionality change

this is probably a **very** good idea.

That said, I am fine with this change since I think it is a good one ;-)

**Pull request merged**
