### PR TITLE
config options for command line switches

### PR DESCRIPTION
**Pull request by norbusan**

### CODE REVIEW

**Comment by abraunegg** [comment]
@norbusan 
Same issue:

* Fails to interpret --confdir parameter:
```
[alex@centos7full onedrive-pr449]$ ./onedrive --confdir '~/.config/onedrive-personal' --synchronize --verbose
Using Config Dir: ~/.config/onedrive-personal
No config file found, using application defaults
Initializing the OneDrive API ...
Authorize this app visiting:

https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=22c49a0d-d21c-4792-aed1-8f163c982546&scope=files.readwrite%20files.readwrite.all%20offline_access&response_type=code&redirect_uri=https://login.microsoftonline.com/common/oauth2/nativeclient

Enter the response uri: ^C
[alex@centos7full onedrive-pr449]$ 
```
current master:
```
[alex@centos7full onedrive]$ ./onedrive --confdir '~/.config/onedrive-personal' --synchronize --verbose
Loading config ...
Using Config Dir: /home/alex/.config/onedrive-personal
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDrivePersonal
Initializing the Synchronization Engine ...
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 4498481239
Fetching details for OneDrive Root
OneDrive Root exists in the database
Syncing changes from OneDrive ...
Applying changes of Path ID: 66D53BE8A5056ECA!101
Processing 64 changes
Uploading differences of .
Processing root
The directory has not changed
Processing random_files
The directory has not changed
Processing random_files_dir_set_3
The directory has not changed
Processing ZhzJyNjAGAVsWhApA70Bhy7VX4nurWTi
The directory has not changed
Processing file104.data
The file has not changed
Processing file809.data
The file has not changed
.........
```

**Comment by norbusan** [comment]
HI @abraunegg 

that is an interesting case ...stemming from ` ./onedrive --confdir '~/.config/onedrive-personal'  `
So you expect onedrive to expand the `~` by itself, and not rely on the shell it seems.

And indeed ` ./onedrive --confdir ~/.config/onedrive-personal ` will probably work for you.

I will look into it.

**Comment by abraunegg** [comment]
One of the original 'skilion' bugs was '~' handling for configuration / sync directory etc - it would work only is certain situations. Current master has this fixed and working correctly - so this patch / config option update has to at least work in the same manner

**Comment by norbusan** [comment]
Fixed.

**Comment by abraunegg** [comment]
@norbusan 
Confirmed

Will run through all my test scripts later today / tonight & provide feedback

**Comment by abraunegg** [comment]
@norbusan 
Does the readme need a complete overhaul for this PR as well?

What about the default config file matching the now 'default' application config?

**Comment by norbusan** [comment]
Good point, I will work on it.

**Comment by norbusan** [comment]
@abraunegg BTW, I would like to have a way to see whether a command line option was passed in or not. It seems to be impossible with getopt :-( There is always a default value and no way to distinguish between default values, values set on the command line but agreeing with the default values, other values.

The reason is, I would like to report all settings, and whether they are at the default values, set in a config file, or set via the command line.

If you have a good idea, please let me know. The best I have seen would be using a different getopt library (there are a few). But maybe this is material for later, different PR.

**Comment by norbusan** [comment]
@abraunegg The last batch of commits did again a few code changes and lots of documentation:

* formerly only available via configuration options are now also available via command line options
* `config` file now contains all options with the default values, but commented
* `README.md` and man page is updated (but please read over it!)

**Pull request merged**
