### PR TITLE
Update Fedora install instructions

### PR DESCRIPTION
**Pull request by mcmtroffaes**
Use dnf instead of yum, point to ldc rpm package for 64 bit systems.

### CODE REVIEW

**Comment by abraunegg** [comment]
Can you update your PR with the following:

* Leave the Fedora / CentOS / RHEL details as is (before change) but denote that it is for Fedora < version 18 / CentOS 6.x / RHEL 6.x

* Add your changes in but denote it for Fedora > version 18 / CentOS 7.x / RHEL 7.x

**Comment by mcmtroffaes** [comment]
Well, dnf has been default on fedora for a few years now (see https://fedoraproject.org/wiki/Changes/ReplaceYumWithDNF), so dnf should only not work for people who are running a version of Fedora which is no longer maintained. If they do so, then they are probably aware that yum has been replaced by dnf, since all instructions for Fedora have been pointing to dnf for a few years now.

Since I'm not familiar with CentOS, and since yum still works on recent Fedora as a symlink to dnf via the dnf-yum package, I've updated the patch to point to just the ldc package on Fedora, and leave yum for now as it is.

**Comment by abraunegg** [comment]
Not exactly what I was meaning - I wanted to add in the specific dnf parts, but have a new section.

**Comment by abraunegg** [comment]
If you can check the edits I have made manually to the readme vs what you wanted to change that would be greatly appreciated.

**Comment by mcmtroffaes** [comment]
Looks good, thanks for incorporating!

**Pull request closed without merging**
