### PR TITLE
Update error response handling for catching HTTP 429 responses - activityLimitReached (Issue #815)

### PR DESCRIPTION
**Pull request by abraunegg**
* Add debugging data for catching 429 - activityLimitReached

### CODE REVIEW

**Comment by abraunegg** [comment]
**with PR:**
```
[DEBUG] Fragment: 1 of 1
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo|   ETA   --:--:--:* Found bundle for host mynasau3-my.sharepoint.com: 0x1ac30e0
* Re-using existing connection! (#3) with host mynasau3-my.sharepoint.com
* Connected to mynasau3-my.sharepoint.com (40.108.249.53) port 443 (#3)
> PUT /personal/alex_braunegg_mynasau3_onmicrosoft_com/_api/v2.0/drives/b!bO8V7s9SSk6r7mWHpIjURotN33W1W2tEv3OXV_oFIdQimEdOHR-1So7CqeT1MfHA/items/01WIXGO5TM56VNA63OT5E262AAA2SG3ZH6/uploadSession?guid='2d83d4a3-ce4a-4d1f-9679-5ffcb62b007b'&path='~tmp57_file0.data'&overwrite=True&rename=False&dc=0&tempauth=eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvbXluYXNhdTMtbXkuc2hhcmVwb2ludC5jb21AMWQ1MzMwYWYtYTg3NS00NWNmLTllNTYtNDM0MzMzMTU3ZGVmIiwiaXNzIjoiMDAwMDAwMDMtMDAwMC0wZmYxLWNlMDAtMDAwMDAwMDAwMDAwIiwibmJmIjoiMTU4MzYyNTEyNiIsImV4cCI6IjE1ODM3MTE1MjYiLCJlbmRwb2ludHVybCI6IkRWbm0xTTNBeU5kd1ZnV283RXJjTFg4d040M3hyR1kwWnMzNFlOUytaSzg9IiwiZW5kcG9pbnR1cmxMZW5ndGgiOiIzMjMiLCJpc2xvb3BiYWNrIjoiVHJ1ZSIsImNpZCI6Ik1HSXpOVFUxWlRJdFpEQXdOaTAwTlRNekxXRmxOek10TmpnM01qQmlPREkyWW1KbSIsInZlciI6Imhhc2hlZHByb29mdG9rZW4iLCJzaXRlaWQiOiJaV1V4TldWbU5tTXROVEpqWmkwMFpUUmhMV0ZpWldVdE5qVTROMkUwT0Roa05EUTIiLCJhcHBfZGlzcGxheW5hbWUiOiJPbmVEcml2ZSBGcmVlIENsaWVudCIsImdpdmVuX25hbWUiOiJBbGV4IiwiZmFtaWx5X25hbWUiOiJCcmF1bmVnZyIsImFwcGlkIjoiMjJjNDlhMGQtZDIxYy00NzkyLWFlZDEtOGYxNjNjOTgyNTQ2IiwidGlkIjoiMWQ1MzMwYWYtYTg3NS00NWNmLTllNTYtNDM0MzMzMTU3ZGVmIiwidXBuIjoiYWxleC5icmF1bmVnZ0BteW5hc2F1My5vbm1pY3Jvc29mdC5jb20iLCJwdWlkIjoiMTAwMzIwMDA5MTUwQ0MyNiIsImNhY2hla2V5IjoiMGguZnxtZW1iZXJzaGlwfDEwMDMyMDAwOTE1MGNjMjZAbGl2ZS5jb20iLCJzY3AiOiJteWZpbGVzLndyaXRlIGFsbGZpbGVzLndyaXRlIGFsbHNpdGVzLndyaXRlIiwidHQiOiIyIiwidXNlUGVyc2lzdGVudENvb2tpZSI6bnVsbH0.cUkxZ1FBa2IxRUxLbTRsV2FacnpVNlR0ZzZRMU9SSjEvajRmTXpLa0dXMD0 HTTP/1.1
User-Agent: OneDrive Client for Linux v2.3.13-27-ge73116a
Host: mynasau3-my.sharepoint.com
Accept: */*
Content-Range: bytes 0-1420415/1420416
Content-Length: 1420416
Expect: 100-continue

< HTTP/1.1 429 Too Many Requests
< Content-Type: application/json; charset=utf-8
< Retry-After: 120
< Server: Microsoft-IIS/10.0
< SPRequestGuid: 69993c9f-10c1-0000-4611-35c073429891
< request-id: 69993c9f-10c1-0000-4611-35c073429891
< MS-CV: nzyZacEQAABGETXAc0KYkQ.0
< Strict-Transport-Security: max-age=31536000
< SPRequestDuration: 24
< SPIisLatency: 1
< X-Powered-By: ASP.NET
< MicrosoftSharePointTeamServices: 16.0.0.19819
< X-Content-Type-Options: nosniff
< X-MS-InvokeApp: 1; RequireReadOnly
< P3P: CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
< Date: Sat, 07 Mar 2020 23:52:06 GMT
< Content-Length: 149
* HTTP error before end of send, stop sending
< 
[DEBUG] onedrive.perform() => OneDrive HTTP Server Response: 429
* Closing connection 3
[DEBUG] onedrive.perform() => HTTP Response Headers: ["strict-transport-security":"max-age=31536000", "microsoftsharepointteamservices":"16.0.0.19819", "p3p":"CP=\"ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI\"", "sprequestguid":"69993c9f-10c1-0000-4611-35c073429891", "retry-after":"120", "date":"Sat, 07 Mar 2020 23:52:06 GMT", "sprequestduration":"24", "server":"Microsoft-IIS/10.0", "spiislatency":"1", "x-content-type-options":"nosniff", "request-id":"69993c9f-10c1-0000-4611-35c073429891", "content-length":"149", "x-ms-invokeapp":"1; RequireReadOnly", "ms-cv":"nzyZacEQAABGETXAc0KYkQ.0", "x-powered-by":"ASP.NET", "content-type":"application/json; charset=utf-8"]
[DEBUG] onedrive.perform() => Received HTTP 429 Retry-After Header Response: 120
[DEBUG] onedrive.perform() => Setting retryAfterValue to: 120
[DEBUG] 
Fragment upload failed - received throttle request response from OneDrive
[DEBUG] Using Retry-After Value = 120
Thread sleeping due to 'HTTP request returned status code 429' - The request has been throttled
Sleeping for 120 seconds
Retrying fragment upload
* About to connect() to mynasau3-my.sharepoint.com port 443 (#4)
*   Trying 40.108.249.53...
* Connected to mynasau3-my.sharepoint.com (40.108.249.53) port 443 (#4)
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate:
*       subject: CN=*.sharepoint.com,OU=Microsoft Corporation,O=Microsoft Corporation,L=Redmond,ST=WA,C=US
*       start date: Aug 07 22:36:15 2019 GMT
*       expire date: Aug 07 22:36:15 2021 GMT
*       common name: *.sharepoint.com
*       issuer: CN=Microsoft IT TLS CA 2,OU=Microsoft IT,O=Microsoft Corporation,L=Redmond,ST=Washington,C=US
> PUT /personal/alex_braunegg_mynasau3_onmicrosoft_com/_api/v2.0/drives/b!bO8V7s9SSk6r7mWHpIjURotN33W1W2tEv3OXV_oFIdQimEdOHR-1So7CqeT1MfHA/items/01WIXGO5TM56VNA63OT5E262AAA2SG3ZH6/uploadSession?guid='2d83d4a3-ce4a-4d1f-9679-5ffcb62b007b'&path='~tmp57_file0.data'&overwrite=True&rename=False&dc=0&tempauth=eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvbXluYXNhdTMtbXkuc2hhcmVwb2ludC5jb21AMWQ1MzMwYWYtYTg3NS00NWNmLTllNTYtNDM0MzMzMTU3ZGVmIiwiaXNzIjoiMDAwMDAwMDMtMDAwMC0wZmYxLWNlMDAtMDAwMDAwMDAwMDAwIiwibmJmIjoiMTU4MzYyNTEyNiIsImV4cCI6IjE1ODM3MTE1MjYiLCJlbmRwb2ludHVybCI6IkRWbm0xTTNBeU5kd1ZnV283RXJjTFg4d040M3hyR1kwWnMzNFlOUytaSzg9IiwiZW5kcG9pbnR1cmxMZW5ndGgiOiIzMjMiLCJpc2xvb3BiYWNrIjoiVHJ1ZSIsImNpZCI6Ik1HSXpOVFUxWlRJdFpEQXdOaTAwTlRNekxXRmxOek10TmpnM01qQmlPREkyWW1KbSIsInZlciI6Imhhc2hlZHByb29mdG9rZW4iLCJzaXRlaWQiOiJaV1V4TldWbU5tTXROVEpqWmkwMFpUUmhMV0ZpWldVdE5qVTROMkUwT0Roa05EUTIiLCJhcHBfZGlzcGxheW5hbWUiOiJPbmVEcml2ZSBGcmVlIENsaWVudCIsImdpdmVuX25hbWUiOiJBbGV4IiwiZmFtaWx5X25hbWUiOiJCcmF1bmVnZyIsImFwcGlkIjoiMjJjNDlhMGQtZDIxYy00NzkyLWFlZDEtOGYxNjNjOTgyNTQ2IiwidGlkIjoiMWQ1MzMwYWYtYTg3NS00NWNmLTllNTYtNDM0MzMzMTU3ZGVmIiwidXBuIjoiYWxleC5icmF1bmVnZ0BteW5hc2F1My5vbm1pY3Jvc29mdC5jb20iLCJwdWlkIjoiMTAwMzIwMDA5MTUwQ0MyNiIsImNhY2hla2V5IjoiMGguZnxtZW1iZXJzaGlwfDEwMDMyMDAwOTE1MGNjMjZAbGl2ZS5jb20iLCJzY3AiOiJteWZpbGVzLndyaXRlIGFsbGZpbGVzLndyaXRlIGFsbHNpdGVzLndyaXRlIiwidHQiOiIyIiwidXNlUGVyc2lzdGVudENvb2tpZSI6bnVsbH0.cUkxZ1FBa2IxRUxLbTRsV2FacnpVNlR0ZzZRMU9SSjEvajRmTXpLa0dXMD0 HTTP/1.1
User-Agent: OneDrive Client for Linux v2.3.13-27-ge73116a
Host: mynasau3-my.sharepoint.com
Accept: */*
Content-Range: bytes 0-1420415/1420416
Content-Length: 1420416
Expect: 100-continue
```

**Comment by abraunegg** [comment]
To reproduce:
1. Upload ~40 random files
2. Run the application constantly: 
```
for i in {1..1000}; do ./onedrive --confdir '~/.config/onedrive-business/' --synchronize --verbose --verbose --debug-https >> ~/debug_output.log 2>&1; done;
```
3. In another terminal, `tail -f ~/debug_output.log`
4. In another terminal, flood with ~100 random files whilst application is running as per above
5. Keep repeating until 429 error is triggered - see delay and handle

**Comment by abraunegg** [comment]
@norbusan 
After extensively testing this locally - should be good for review now

**Comment by abraunegg** [comment]
**Sample Output with PR:**
```
Remaining free space on OneDrive: 1095248298963
Uploading new file ./random_files/PNhaI5wrzUK5SEaKUlp8VH4yDW9R7Scr/file7.data ... 
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo|   ETA   --:--:--:     
done.
Remaining free space on OneDrive: 1095247147475
Uploading new file ./random_files/PNhaI5wrzUK5SEaKUlp8VH4yDW9R7Scr/file8.data ... 
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo|   ETA   --:--:--:     
done.
Remaining free space on OneDrive: 1095245912275
Uploading new file ./random_files/PNhaI5wrzUK5SEaKUlp8VH4yDW9R7Scr/file9.data ... 
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo|   ETA   --:--:--:     
Thread sleeping due to 'HTTP request returned status code 429' - The request has been throttled
Sleeping for 120 seconds
Retrying fragment upload
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo|   ETA   --:--:--:     
done.
Remaining free space on OneDrive: 1095245139347
Uploading new file ./random_files/PNhaI5wrzUK5SEaKUlp8VH4yDW9R7Scr/file10.data ... 
Uploading 100% |oooooooooooooooooooooooooooooooooooooooo|   ETA   --:--:--:     
done.
```

**Comment by norbusan** [comment]
I'm off in to the mountains for 5 days, so don't expect any review for a week.

**Comment by abraunegg** [comment]
@norbusan 
No problem :)

**Pull request merged**
