### PR TITLE
autoconf/automake conversion

### PR DESCRIPTION
**Pull request by norbusan**
Convert the build system to automake/autoconf. Currently supported features/items:

- D compiler is searched for automatically from `dmd` and `ldmd2` (in this order)
- `DCFLAGS` default to `-w -g -O` but can be overridden via env variables
- SQLite and Curl is searched for via `pkg-config`, libs are automatically generated
- enabling notifications can be done with  `--enable-notifications`, which  searches automatically for `libnotify` using `pkg-configa`
- systemd units are installed when the systemd system/user unit dir variable is found. These are again checked with `pkg-config --variable=systemdsystemunitdir systemd` etc.
- if `pkg-config` is not available, one can use `CURL_LIBS` and `SQLITE_LIBS` to pass in the necessary libs, same for `NOTIFY_LIBS`
- systemd service installation can be disabled by `--with-systemdsystemunitdir=no` or `--with-systemduserunitdir=no`
- the following files are automaically generated with version numbers replaces `pacman/PKGBUILD` and `spec/onedrive.spec`, and the version number in the man page is also automatically replaced
- The `version` file is now generated from the program version if no `.git` directory is found

Features from the current Makefile not carried over:

- RedHat specific stuff, should be automatically done now via the `pkg-config` calls

Incomplete items

- conversion of the pacman and spec file to use configure instead of the makefile directly (sorry, no experience with rpm/pacman)

### CODE REVIEW

**Comment by abraunegg** [comment]
Will review overnight. 

Re the spec file - thats a left over from when I was building the 1.x skilion branch for MyNAS, and I kept that in my fork incase it was useful for others. Potentially could be depricated for the spec file on fedora koji - will check

**Comment by adudek** [comment]
You probably want to update README.md also

**Comment by norbusan** [comment]
> You probably want to update README.md also

Done, thanks

**Comment by abraunegg** [comment]
Will test this throughout today locally.

I probably wont push this into the current 'master' however until after another 'release' is done, as we have ~7 changes now since the last release which warrants a new minor version bump.

This patch, would warrant a 2.3.0 release IMHO, just so that we don't upset the apple cart for features / versions / changes etc

Thoughts?

**Comment by norbusan** [comment]
Sure enough. My primary aim was to get wider testing and feedback on missing features. Esp testing of systemd installation on different systems would be nice - sorry I don't have any RPM related system around.

Thanks and all the best

**Comment by abraunegg** [comment]
Found an issue:
```
source ~/dlang/dmd-2.083.0/activate
make clean;
./configure
make
deactivate
```
generates:
```
make: *** No rule to make target `clean'.  Stop.
checking for a BSD-compatible install... /usr/bin/install -c
checking for a sed that does not truncate output... /usr/bin/sed
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for dmd... /home/alex/dlang/dmd-2.083.0/linux/bin64/dmd
checking for CURL... yes
checking for SQLITE... yes
checking for NOTIFY... yes
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating pacman/PKGBUILD
config.status: creating spec/onedrive.spec
config.status: creating onedrive.1.in
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /home/alex/code/onedrive/missing aclocal-1.16 
/home/alex/code/onedrive/missing: line 81: aclocal-1.16: command not found
WARNING: 'aclocal-1.16' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <https://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <https://www.gnu.org/software/autoconf>
         <https://www.gnu.org/software/m4/>
         <https://www.perl.org/>
make: *** [aclocal.m4] Error 127
```

**Comment by norbusan** [comment]
One more thing: I have also started on a meson/ninja based build chain, which could be used instead or in addition to the autoconf stuff.

If there are any preferences, please let me know.

@abraunegg please touch aclocal.m4, this should be enough (I hope)

**Comment by norbusan** [comment]
See the pull request https://github.com/abraunegg/onedrive/pull/286 
We could drop this one, keep a normal `Makefile` as of now, and supply a meson/ninja based build system for those who need more configuration/adjustments.

**Comment by abraunegg** [comment]
@norbusan 
Still no go:
```
[alex@centos7full onedrive]$ touch aclocal.m4 
[alex@centos7full onedrive]$ make
 cd . && /bin/sh /home/alex/code/onedrive/missing automake-1.16 --foreign
/home/alex/code/onedrive/missing: line 81: automake-1.16: command not found
WARNING: 'automake-1.16' is missing on your system.
         You should only need it if you modified 'Makefile.am' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'automake' program is part of the GNU Automake package:
         <https://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <https://www.gnu.org/software/autoconf>
         <https://www.gnu.org/software/m4/>
         <https://www.perl.org/>
make: *** [Makefile.in] Error 1
```

I use a script to clean / refresh each time I test as well:

```
#!/bin/bash

PR=284

rm -rf ./onedrive/
git clone https://github.com/abraunegg/onedrive.git
cd onedrive
git fetch origin pull/${PR}/head:pr${PR}
git checkout pr${PR}


# Configure & Build
source ~/dlang/dmd-2.083.0/activate
./configure
make
deactivate
```

Need to also put back into the makefile `make clean`  : 
```
[alex@centos7full onedrive]$ make clean                         
 cd . && /bin/sh /home/alex/code/onedrive/missing automake-1.16 --foreign
/home/alex/code/onedrive/missing: line 81: automake-1.16: command not found
WARNING: 'automake-1.16' is missing on your system.
         You should only need it if you modified 'Makefile.am' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'automake' program is part of the GNU Automake package:
         <https://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <https://www.gnu.org/software/autoconf>
         <https://www.gnu.org/software/m4/>
         <https://www.perl.org/>
make: *** [Makefile.in] Error 1
```

Both are barfing on this line:
```
/home/alex/code/onedrive/missing: line 81: automake-1.16: command not found
```
```
[alex@centos7full onedrive]$ which automake                     
/usr/bin/automake
[alex@centos7full onedrive]$ 
```

**Comment by norbusan** [comment]
Ok, I have now removed, autoreconf -i, and re-added the files. In my tests here according to your script the `missing aclocal-1.16` is **not** called:
```
$ git clone https://github.com/abraunegg/onedrive.git
Cloning into 'onedrive'...
remote: Enumerating objects: 108, done.
remote: Counting objects: 100% (108/108), done.
remote: Compressing objects: 100% (75/75), done.
remote: Total 1965 (delta 46), reused 86 (delta 29), pack-reused 1857
Receiving objects: 100% (1965/1965), 1.24 MiB | 1.07 MiB/s, done.
Resolving deltas: 100% (1292/1292), done.
$ cd onedrive
$ git fetch origin pull/${PR}/head:pr${PR}
From https://github.com/abraunegg/onedrive
 * [new ref]         refs/pull/284/head -> pr284
$  git checkout pr${PR}
Switched to branch 'pr284'
$ ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking for a sed that does not truncate output... /bin/sed
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for dmd... /usr/bin/dmd
checking for CURL... yes
checking for SQLITE... yes
checking for NOTIFY... yes
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating pacman/PKGBUILD
config.status: creating spec/onedrive.spec
config.status: creating onedrive.1.in
$ make clean
test -z "onedrive" || rm -f onedrive
test -z "onedrive onedrive.o systemd.units/onedrive.service systemd.units/onedrive@.service onedrive.1 version" || rm -f onedrive onedrive.o systemd.units/onedrive.service systemd.units/onedrive@.service onedrive.1 version
rm -f *.
$ 
```

Hope that fixes it for you, too

**Comment by abraunegg** [comment]
No such luck:
```
 ./clone_automake.sh  
+ PR=284
+ rm -rf ./onedrive/
+ git clone https://github.com/abraunegg/onedrive.git
Cloning into 'onedrive'...
remote: Enumerating objects: 108, done.
remote: Counting objects: 100% (108/108), done.
remote: Compressing objects: 100% (75/75), done.
remote: Total 1965 (delta 46), reused 86 (delta 29), pack-reused 1857
Receiving objects: 100% (1965/1965), 1.24 MiB | 296.00 KiB/s, done.
Resolving deltas: 100% (1292/1292), done.
+ cd onedrive
+ git fetch origin pull/284/head:pr284
From https://github.com/abraunegg/onedrive
 * [new ref]         refs/pull/284/head -> pr284
+ git checkout pr284
Switched to branch 'pr284'
+ source /home/alex/dlang/dmd-2.083.0/activate
++ _OLD_D_PATH=/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/alex/.local/bin:/home/alex/bin
++ _OLD_D_LIBRARY_PATH=
++ _OLD_D_LD_LIBRARY_PATH=
++ _OLD_D_PS1=
++ export PATH=/home/alex/dlang/dmd-2.083.0/linux/bin64:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/alex/.local/bin:/home/alex/bin
++ PATH=/home/alex/dlang/dmd-2.083.0/linux/bin64:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/alex/.local/bin:/home/alex/bin
++ export LIBRARY_PATH=/home/alex/dlang/dmd-2.083.0/linux/lib64
++ LIBRARY_PATH=/home/alex/dlang/dmd-2.083.0/linux/lib64
++ export LD_LIBRARY_PATH=/home/alex/dlang/dmd-2.083.0/linux/lib64
++ LD_LIBRARY_PATH=/home/alex/dlang/dmd-2.083.0/linux/lib64
++ export DMD=dmd
++ DMD=dmd
++ export DC=dmd
++ DC=dmd
++ export 'PS1=(dmd-2.083.0)'
++ PS1='(dmd-2.083.0)'
+ ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking for a sed that does not truncate output... /usr/bin/sed
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for dmd... /home/alex/dlang/dmd-2.083.0/linux/bin64/dmd
checking for CURL... yes
checking for SQLITE... yes
checking for NOTIFY... yes
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating pacman/PKGBUILD
config.status: creating spec/onedrive.spec
config.status: creating onedrive.1.in
+ make
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /home/alex/code/onedrive/missing aclocal-1.16 
/home/alex/code/onedrive/missing: line 81: aclocal-1.16: command not found
WARNING: 'aclocal-1.16' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <https://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <https://www.gnu.org/software/autoconf>
         <https://www.gnu.org/software/m4/>
         <https://www.perl.org/>
make: *** [aclocal.m4] Error 127
+ deactivate
+ export PATH=/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/alex/.local/bin:/home/alex/bin
+ PATH=/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/alex/.local/bin:/home/alex/bin
+ export LIBRARY_PATH=
+ LIBRARY_PATH=
+ export LD_LIBRARY_PATH=
+ LD_LIBRARY_PATH=
+ export PS1=
+ PS1=
+ unset _OLD_D_PATH
+ unset _OLD_D_LIBRARY_PATH
+ unset _OLD_D_LD_LIBRARY_PATH
+ unset _OLD_D_PS1
+ unset DMD
+ unset DC
+ unset -f deactivate
```

**Comment by norbusan** [comment]
Actually one addition: releasing files would consist of editing the version in `configure.ac` and then running `autoreconf -i`, which means that the developers machines would need autotools installed anyway.

And I am not sure that if you tag the release afterwards, the github generated .tar.gz will work automatically (I cannot test it and it is not documented anywhere).

OTOH, with meson no intermediate generation is necessary. Simply edit the `meson.build` version and that's it. Github generated archives will surely work.

auto* are more common, I agree, but the current situation wrt git is unsatisfactory.

**Comment by abraunegg** [comment]
What about this:
https://stackoverflow.com/questions/934051/how-do-i-prevent-autotools-from-re-generating-configure-script-automatically

Add:
```
AM_MAINTAINER_MODE
```

to the configure.ac

**Comment by norbusan** [comment]
I have create a new pull request based only on autoconf and without automake which fixes the problems you have seen. Furthermore, release management is easy. Please see further explanations at https://github.com/abraunegg/onedrive/pull/287

**Pull request closed without merging**
