### PR TITLE
Update entrypoint.sh

### PR DESCRIPTION
**Pull request by cauan**
Accept command line arguments

### CODE REVIEW

**Comment by abraunegg** [comment]
Looks OK to me.

@adudek, @norbusan 
Your thoughts?

**Comment by norbusan** [comment]
From only looking at it looks fine

**Comment by adudek** [comment]
most popular way of setting application containers is smple oneliner

plaease consider storing args in array, code is much simpler like that
also when you exepect number as output do not quote it ($# vs "$#", in most cases it will be better reflected in error messages and easier for reader to understand purpose of variable

current industry standard would look like this:
```
[$# -gt 0] && args=("$@") || args=(a b c)
onedrive "${args[@]}"
```

other than linting and potentially misleading error messages this if functionally ok

**Comment by abraunegg** [comment]
@cauan 
Can you review the comments from @adudek

**Comment by cauan** [comment]
Hi @adudek, thank you for your feedback.

I've update most of it. Regarding to transform it into an one liner it's more coding style, IMHO. As the rest of the code have no inline if, I left it as it is.

But it is up to you guys make it one liner or not. I'm fine with both.

@abraunegg and all contributor, thank you guys for maintaining this project.

**Comment by norbusan** [comment]
@adudek 

> current industry standard would look like this:
> 
> ```
> [$# -gt 0] && args=("$@") || args=(a b c)
> onedrive "${args[@]}"
> ```

I kind of disagree here. The one-liner is far less readable, prone to errors when edited. I wouldn't call this *industry standard*, at least in my company I would get beaten when I write code like this.

Otherwise, fine with me

**Pull request merged**
