### PR TITLE
Reduce change scan impact of fix for #658 (Issue #690)

### PR DESCRIPTION
**Pull request by abraunegg**
If there are delta changes (meaning something changed on OneDrive) process the changes that have been presented.

What this PR does:
* always get the 'delta' change list
* if there are OneDrive delta changes (something was changed on OneDrive) & our 'changes' query (delta or full) are > 0 we have some change to process

What this fixes is always having to do a full scan every sync when using 'sync_list' and there is no change on OneDrive ... no need to process all existing files if nothing changed.

### CODE REVIEW

**Comment by abraunegg** [comment]
**config:**
```
onedrive version                    = v2.3.10-7-g9d0a653
Config path                         = /home/alex/.config/onedrive-personal/
Config file found in config path    = true
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /home/alex/OneDrivePersonal
Config option 'skip_dir'            = dirinskipdir
Config option 'skip_file'           = ~*|.~*|*.tmp|fileinskipfile
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Config option 'sync_root_files'     = false
Selective sync configured           = true
sync_list contents:
syncthis
```

**Make change on OneDrive outside sync scope:**
```
Using Config Dir: /home/alex/.config/onedrive-personal/
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDrivePersonal
Application version: v2.3.10-7-g9d0a653
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 5341004301
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Applying changes of Path ID: 66D53BE8A5056ECA!101
Processing 37 OneDrive items to ensure consistent state due to sync_list being used
Skipping item - excluded by skip_dir config: dirinskipdir
Skipping item - excluded by sync_list config: shouldbeskippedtoo
Skipping item - excluded by sync_list config: asdfasdfasdfasdf
Uploading differences of .
Processing root
The directory has not changed
Processing syncthis
The directory has not changed
Processing file.txt
The file has not changed
Processing asdf
The directory has not changed
Processing zfs module updates.txt
The file has not changed
Uploading new items of .
Skipping item - excluded by skip_file config: ./fileinskipfile
Skipping item - excluded by skip_dir config: ./dirinskipdir
Skipping item - excluded by sync_list config: ./skipthis
Applying changes of Path ID: 66D53BE8A5056ECA!101
```
**subsequent scan after 'delta' has been processed:**
```
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDrivePersonal
Application version: v2.3.10-7-g9d0a653
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 5341004301
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Applying changes of Path ID: 66D53BE8A5056ECA!101
Uploading differences of .
Processing root
The directory has not changed
Processing syncthis
The directory has not changed
Processing file.txt
The file has not changed
Processing asdf
The directory has not changed
Processing zfs module updates.txt
The file has not changed
Uploading new items of .
Skipping item - excluded by skip_file config: ./fileinskipfile
Skipping item - excluded by skip_dir config: ./dirinskipdir
Skipping item - excluded by sync_list config: ./skipthis
```

**move folder into sync scope:**
```
Using Config Dir: /home/alex/.config/onedrive-personal/
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDrivePersonal
Application version: v2.3.10-7-g9d0a653
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 5341004301
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Applying changes of Path ID: 66D53BE8A5056ECA!101
Processing 37 OneDrive items to ensure consistent state due to sync_list being used
Skipping item - excluded by skip_dir config: dirinskipdir
Skipping item - excluded by sync_list config: shouldbeskippedtoo
Creating directory: syncthis/asdfasdfasdfasdf
Creating directory: syncthis/asdfasdfasdfasdf/10-Files
Creating directory: syncthis/asdfasdfasdfasdf/10-Files/Architecture Layres
Creating directory: syncthis/asdfasdfasdfasdf/10-Files/Cisco VDI Whitepaper
Creating directory: syncthis/asdfasdfasdfasdf/10-Files/SMPP
Creating directory: syncthis/asdfasdfasdfasdf/10-Files/Images
Downloading file syncthis/asdfasdfasdfasdf/10-Files/Cisco VDI Whitepaper/white_paper_c11-494994.pdf ... done.
Downloading file syncthis/asdfasdfasdfasdf/10-Files/SMPP/SMPP_v3_4_Issue1_2-24857.pdf ... done.
Downloading file syncthis/asdfasdfasdfasdf/10-Files/Architecture Layres/architecture layers v0.4 - AB.vsd ... done.
Downloading file syncthis/asdfasdfasdfasdf/10-Files/Cisco VDI Whitepaper/campover.pdf ... done.
Downloading file syncthis/asdfasdfasdfasdf/10-Files/SMPP/SMPP-IF-SPEC_v3_3-24858.pdf ... done.
Creating directory: syncthis/asdfasdfasdfasdf/10-Files/Images/JPG
Creating directory: syncthis/asdfasdfasdfasdf/10-Files/Images/PNG
Downloading file syncthis/asdfasdfasdfasdf/10-Files/Images/JPG/IMG_2920.JPG ... done.
Downloading file syncthis/asdfasdfasdfasdf/10-Files/Images/JPG/IMG_2919.JPG ... done.
Downloading file syncthis/asdfasdfasdfasdf/10-Files/Images/JPG/IMG_2921.JPG ... done.
Downloading file syncthis/asdfasdfasdfasdf/10-Files/Images/JPG/IMG_2922.JPG ... done.
Downloading file syncthis/asdfasdfasdfasdf/10-Files/Images/JPG/IMG_2924.JPG ... done.
Downloading file syncthis/asdfasdfasdfasdf/10-Files/Images/JPG/IMG_2923.JPG ... done.
Downloading file syncthis/asdfasdfasdfasdf/10-Files/Images/JPG/IMG_2925.JPG ... done.
Downloading file syncthis/asdfasdfasdfasdf/10-Files/Images/PNG/MyNAS Test Install for Documentation-2014-08-24-18-12-09.png ... done.
Downloading file syncthis/asdfasdfasdfasdf/10-Files/Images/PNG/MyNAS Test Install for Documentation-2014-09-11-15-20-06.png ... done.
Downloading file syncthis/asdfasdfasdfasdf/10-Files/Images/PNG/MyNAS Test Install for Documentation-2014-09-11-15-31-43.png ... done.
Downloading file syncthis/asdfasdfasdfasdf/10-Files/Images/PNG/MyNAS Test Install for Documentation-2014-09-11-15-32-50.png ... done.
Downloading file syncthis/asdfasdfasdfasdf/10-Files/Images/PNG/MyNAS Test Install for Documentation-2014-09-11-15-07-12.png ... done.
Downloading file syncthis/asdfasdfasdfasdf/10-Files/Images/PNG/MyNAS Test Install for Documentation-2014-09-11-15-08-19.png ... done.
Downloading file syncthis/asdfasdfasdfasdf/10-Files/Images/PNG/CentOS - iSCSI & NFS Mount Example System-2014-10-24-11-48-10.png ... done.
Downloading file syncthis/asdfasdfasdfasdf/10-Files/Images/JPG/IMG_2926.JPG ... done.
Downloading file syncthis/asdfasdfasdfasdf/10-Files/Images/PNG/MyNAS Test Install for Documentation-2014-08-24-18-09-36.png ... done.
Uploading differences of .
Processing root
The directory has not changed
Processing syncthis
The directory has not changed
Processing file.txt
The file has not changed
Processing asdf
The directory has not changed
Processing zfs module updates.txt
The file has not changed
Processing asdfasdfasdfasdf
The directory has not changed
Processing 10-Files
The directory has not changed
Processing Architecture Layres
The directory has not changed
Processing architecture layers v0.4 - AB.vsd
The file has not changed
Processing Cisco VDI Whitepaper
The directory has not changed
Processing white_paper_c11-494994.pdf
The file has not changed
Processing campover.pdf
The file has not changed
Processing SMPP
The directory has not changed
Processing SMPP_v3_4_Issue1_2-24857.pdf
The file has not changed
Processing SMPP-IF-SPEC_v3_3-24858.pdf
The file has not changed
Processing Images
The directory has not changed
Processing JPG
The directory has not changed
Processing IMG_2920.JPG
The file has not changed
Processing IMG_2919.JPG
The file has not changed
Processing IMG_2921.JPG
The file has not changed
Processing IMG_2922.JPG
The file has not changed
Processing IMG_2924.JPG
The file has not changed
Processing IMG_2923.JPG
The file has not changed
Processing IMG_2925.JPG
The file has not changed
Processing IMG_2926.JPG
The file has not changed
Processing PNG
The directory has not changed
Processing MyNAS Test Install for Documentation-2014-08-24-18-12-09.png
The file has not changed
Processing MyNAS Test Install for Documentation-2014-09-11-15-20-06.png
The file has not changed
Processing MyNAS Test Install for Documentation-2014-09-11-15-31-43.png
The file has not changed
Processing MyNAS Test Install for Documentation-2014-09-11-15-32-50.png
The file has not changed
Processing MyNAS Test Install for Documentation-2014-09-11-15-07-12.png
The file has not changed
Processing MyNAS Test Install for Documentation-2014-09-11-15-08-19.png
The file has not changed
Processing CentOS - iSCSI & NFS Mount Example System-2014-10-24-11-48-10.png
The file has not changed
Processing MyNAS Test Install for Documentation-2014-08-24-18-09-36.png
The file has not changed
Uploading new items of .
Skipping item - excluded by skip_file config: ./fileinskipfile
Skipping item - excluded by skip_dir config: ./dirinskipdir
Skipping item - excluded by sync_list config: ./skipthis
Applying changes of Path ID: 66D53BE8A5056ECA!101
```

**subsequent scan after 'delta' has been processed & no further OneDrive change:**
```
Using Config Dir: /home/alex/.config/onedrive-personal/
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDrivePersonal
Application version: v2.3.10-7-g9d0a653
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 5341004301
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Applying changes of Path ID: 66D53BE8A5056ECA!101
Uploading differences of .
Processing root
The directory has not changed
Processing syncthis
The directory has not changed
Processing file.txt
The file has not changed
Processing asdf
The directory has not changed
Processing zfs module updates.txt
The file has not changed
Processing asdfasdfasdfasdf
The directory has not changed
Processing 10-Files
The directory has not changed
Processing Architecture Layres
The directory has not changed
Processing architecture layers v0.4 - AB.vsd
The file has not changed
Processing Cisco VDI Whitepaper
The directory has not changed
Processing white_paper_c11-494994.pdf
The file has not changed
Processing campover.pdf
The file has not changed
Processing SMPP
The directory has not changed
Processing SMPP_v3_4_Issue1_2-24857.pdf
The file has not changed
Processing SMPP-IF-SPEC_v3_3-24858.pdf
The file has not changed
Processing Images
The directory has not changed
Processing JPG
The directory has not changed
Processing IMG_2920.JPG
The file has not changed
Processing IMG_2919.JPG
The file has not changed
Processing IMG_2921.JPG
The file has not changed
Processing IMG_2922.JPG
The file has not changed
Processing IMG_2924.JPG
The file has not changed
Processing IMG_2923.JPG
The file has not changed
Processing IMG_2925.JPG
The file has not changed
Processing IMG_2926.JPG
The file has not changed
Processing PNG
The directory has not changed
Processing MyNAS Test Install for Documentation-2014-08-24-18-12-09.png
The file has not changed
Processing MyNAS Test Install for Documentation-2014-09-11-15-20-06.png
The file has not changed
Processing MyNAS Test Install for Documentation-2014-09-11-15-31-43.png
The file has not changed
Processing MyNAS Test Install for Documentation-2014-09-11-15-32-50.png
The file has not changed
Processing MyNAS Test Install for Documentation-2014-09-11-15-07-12.png
The file has not changed
Processing MyNAS Test Install for Documentation-2014-09-11-15-08-19.png
The file has not changed
Processing CentOS - iSCSI & NFS Mount Example System-2014-10-24-11-48-10.png
The file has not changed
Processing MyNAS Test Install for Documentation-2014-08-24-18-09-36.png
The file has not changed
Uploading new items of .
Skipping item - excluded by skip_file config: ./fileinskipfile
Skipping item - excluded by skip_dir config: ./dirinskipdir
Skipping item - excluded by sync_list config: ./skipthis
Applying changes of Path ID: 66D53BE8A5056ECA!101
```

**Comment by norbusan** [comment]
Syncing the first time with this change, I see *loads* of messages
```
Delta link expired, re-syncing...
```
(with `-v`). Adding `-v -v`
```
[DEBUG] OneDrive threw an error when querying for these changes:
[DEBUG] driveId: <XXXX>
[DEBUG] idToQuery: <XXXX>!101
[DEBUG] deltaLink: 
Delta link expired, re-syncing...
```
and it somehow takes ages ...

Doing the same with current released version this does not happen, and the sync operation is much faster.

Is this to be expected? I don't see how th

**Comment by abraunegg** [comment]
> Syncing the first time with this change, I see _loads_ of messages
> 
> ```
> Delta link expired, re-syncing...
> ```
> 
> (with `-v`). Adding `-v -v`
> 
> ```
> [DEBUG] OneDrive threw an error when querying for these changes:
> [DEBUG] driveId: <XXXX>
> [DEBUG] idToQuery: <XXXX>!101
> [DEBUG] deltaLink: 
> Delta link expired, re-syncing...
> ```
> 
> and it somehow takes ages ...
> 
> Doing the same with current released version this does not happen, and the sync operation is much faster.
> 
> Is this to be expected? I don't see how th

Hrmmm..... no this is not the desired result.

What is your config (`--display-config`) showing ??? I only tested this when using a valid `sync_list`

**Comment by norbusan** [comment]
```
onedrive version                    = v2.3.7-24-g4d49b3a
Config path                         = /home/norbert/.config/onedrive-test/
Config file found in config path    = true
Config option 'check_nosync'        = false
Config option 'sync_dir'            = /home/norbert/OneDriveTest
Config option 'skip_dir'            = Ignore|Test/RecIgnore
Config option 'skip_file'           = ~*|.~*|*.tmp
Config option 'skip_dotfiles'       = false
Config option 'skip_symlinks'       = false
Config option 'monitor_interval'    = 45
Config option 'min_notify_changes'  = 5
Config option 'log_dir'             = /var/log/onedrive/
Config option 'sync_root_files'     = false
Selective sync configured           = false
```

**Comment by abraunegg** [comment]
OK .. so testing without a valid sync_list .. will look into that

**Comment by abraunegg** [comment]
@norbusan 
Can you confirm when your building the PR - this is your version:
```
[alex@centos7full onedrive-pr691]$ ./onedrive --confdir '~/.config/onedrive-personal/' --display-config
onedrive version                    = v2.3.10-8-g9e2ecdc
Config path                         = /home/alex/.config/onedrive-personal/
```

Appears to be different from what your running ... unsure why ...

**Comment by abraunegg** [comment]
@norbusan 
> > Syncing the first time with this change, I see _loads_ of messages
> > ```
> > Delta link expired, re-syncing...
> > ```
> > 
> > 
> > (with `-v`). Adding `-v -v`
> > ```
> > [DEBUG] OneDrive threw an error when querying for these changes:
> > [DEBUG] driveId: <XXXX>
> > [DEBUG] idToQuery: <XXXX>!101
> > [DEBUG] deltaLink: 
> > Delta link expired, re-syncing...
> > ```
> > 
> > 
> > and it somehow takes ages ...
> > Doing the same with current released version this does not happen, and the sync operation is much faster.
> > Is this to be expected? I don't see how th
> 
> Hrmmm..... no this is not the desired result.
> 
> What is your config (`--display-config`) showing ??? I only tested this when using a valid `sync_list`


not seeing this issue ... 


```
[alex@centos7full onedrive-pr691]$ ./onedrive --confdir '~/.config/onedrive-personal/' --synchronize --verbose 
Using Config Dir: /home/alex/.config/onedrive-personal/
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDrivePersonal
Application version: v2.3.10-8-g9e2ecdc
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 5343902702
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Applying changes of Path ID: 66D53BE8A5056ECA!101
Uploading differences of .
Processing root
The directory has not changed
Processing 10-Files
The directory has not changed
Processing Architecture Layres
The directory has not changed
Processing architecture layers v0.4 - AB.vsd
The file has not changed
Processing Cisco VDI Whitepaper
The directory has not changed
Processing white_paper_c11-494994.pdf
The file has not changed
Processing campover.pdf
The file has not changed
Processing Cornell
The directory has not changed
Processing Others
The directory has not changed
Processing John
The directory has not changed
Processing Alex
The directory has not changed
Processing 22 ICB
The directory has not changed
Processing server
The directory has not changed
Processing Architecture Layres
The directory has not changed
Processing architecture layers v0.4 - AB.vsd
The file has not changed
Processing website
The directory has not changed
Processing Contractor
The directory has not changed
Processing Cisco VDI Whitepaper
The directory has not changed
Processing white_paper_c11-494994.pdf
The file has not changed
Processing campover.pdf
The file has not changed
Processing Freelancer
The directory has not changed
Processing server_
The directory has not changed
Processing pkg order to add.txt
The file has not changed
Processing 22 ABC
The directory has not changed
Processing SMPP
The directory has not changed
Processing SMPP-IF-SPEC_v3_3-24858.pdf
The file has not changed
Processing SMPP_v3_4_Issue1_2-24857.pdf
The file has not changed
Uploading new items of .
Applying changes of Path ID: 66D53BE8A5056ECA!101
[alex@centos7full onedrive-pr691]$ 
```

**Comment by abraunegg** [comment]
@norbusan 
Looking at your version string:
```
v2.3.7-24-g4d49b3a
```
vs
```
v2.3.10-8-g9e2ecdc
```

Might explain the issue your seeing ?

**Comment by norbusan** [comment]
Hmm, very strange. I was checking out the branch and compiling it ... maybe I missed something, or didn' pull.
Need to check later on, as I am off for a bit of hiking with the family.

**Comment by abraunegg** [comment]
@norbusan 
No problem.

I use this script to test the PR's:
```
#!/bin/bash

PR=691

rm -rf ./onedrive-pr${PR}
git clone https://github.com/abraunegg/onedrive.git onedrive-pr${PR}
cd onedrive-pr${PR}
git fetch origin pull/${PR}/head:pr${PR}
git checkout pr${PR}
source ~/dlang/dmd-2.085.0/activate
./configure; make clean; make;
deactivate
```

**Comment by norbusan** [comment]
Still not clear what has happened, but with a make distclean ; ./configure ; make it now works. So sorry for the noise - but I still am I bit suspicious, because I **did** compile it before my tests. It might only be that an old `version` file was hanging around.

Anyway, since I have no way to reproduce it, let us forget it for the moment.

**Pull request merged**
