### PR TITLE
catch exception if dbus server has problems

### PR DESCRIPTION
**Pull request by norbusan**
@abraunegg please test in your surroundings, on my docker centos7 image I had no problems running it

### CODE REVIEW

**Comment by abraunegg** [comment]
@norbusan 
Output below:
```
[alex@centos7full onedrive-pr367]$ ./onedrive --confdir '~/.config/onedrive-personal' --monitor --verbose --verbose
trying to get info from server!
trying to get info from server!
[DEBUG] homePath: HOME environment variable set
[DEBUG] homePath: /home/alex
[DEBUG] configDirBase: WARNING - no XDG_CONFIG_HOME environment variable set
[DEBUG] configDirBase: /home/alex/.config
[DEBUG] configDirName: CLI override to set configDirName to: ~/.config/onedrive-personal
[DEBUG] configDirName: A '~' was found in configDirName, using the calculated 'homePath' to replace '~'
Loading config ...
Using Config Dir: /home/alex/.config/onedrive-personal
[DEBUG] sync_dir: Getting syncDir from config value sync_dir
[DEBUG] sync_dir: A '~' was found in configured sync_dir, automatically expanding as SHELL and USER environment variable is set
[DEBUG] syncDir: /home/alex/OneDrivePersonal
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDrivePersonal
Got exception from showing notification: dnotify.NotificationError@src/notifications/dnotify.d(51): Cannot autolaunch D-Bus without X11 $DISPLAY
----------------
src/notifications/dnotify.d:190 void dnotify.Notification.show() [0x5e8308]
src/log.d:119 void log.notify!(immutable(char)[]).notify(immutable(char)[]) [0x5ab6a6]
src/log.d:58 void log.logAndNotify!(immutable(char)[]).logAndNotify(immutable(char)[]) [0x5ab5c7]
src/main.d:395 _Dmain [0x5b1187]
Initializing the Synchronization Engine ...
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 5368709120
Fetching details for OneDrive Root
OneDrive Root exists in the database
Trying to restore the upload session ...
The file does not exist anymore
Got exception from showing notification: dnotify.NotificationError@src/notifications/dnotify.d(51): Cannot autolaunch D-Bus without X11 $DISPLAY
----------------
src/notifications/dnotify.d:190 void dnotify.Notification.show() [0x5e8308]
src/log.d:119 void log.notify!(immutable(char)[]).notify(immutable(char)[]) [0x5ab6a6]
src/log.d:58 void log.logAndNotify!(immutable(char)[]).logAndNotify(immutable(char)[]) [0x5ab5c7]
src/main.d:488 _Dmain [0x5b1732]
Initializing monitor ...
OneDrive monitor interval (seconds): 120
Monitor directory: .
Monitor directory: ./10-Files
Monitor directory: ./10-Files/Architecture Layres
Monitor directory: ./10-Files/Cisco VDI Whitepaper
Monitor directory: ./10-Files/SMPP
Monitor directory: ./10-Files/Images
Monitor directory: ./10-Files/Images/JPG
Monitor directory: ./10-Files/Images/PNG
^CGot termination signal, shutting down db connection
```

**Comment by norbusan** [comment]
Hi @abraunegg 

thanks, that are bad news ...

> ```
> [alex@centos7full onedrive-pr367]$ ./onedrive --confdir '~/.config/onedrive-personal' --monitor --verbose --verbose
> trying to get info from server!
> trying to get info from server!
> ```

Aahhh, that helps ... (stupid me - copy and paste the same line twice!!) it shows that the call to `notify_get_server_info` returned false, which is good. Thanks

I pushed new changes to this PR, which now should test for the server and disable notifications if that doesn't work. Thanks for testing

**Comment by abraunegg** [comment]
@norbusan 
Looks good now - no error:
```
./onedrive --confdir '~/.config/onedrive-personal' --monitor --verbose 
Loading config ...
Using Config Dir: /home/alex/.config/onedrive-personal
notification (dbus) server not available, disabling
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDrivePersonal
Initializing the Synchronization Engine ...
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 5368709120
Fetching details for OneDrive Root
OneDrive Root exists in the database
Trying to restore the upload session ...
The file does not exist anymore
Initializing monitor ...
OneDrive monitor interval (seconds): 30
Monitor directory: .
Syncing changes from OneDrive ...
Applying changes of Path ID: 66D53BE8A5056ECA!101
Uploading differences of .
Processing root
The directory has not changed
Uploading new items of .
Applying changes of Path ID: 66D53BE8A5056ECA!101
Syncing changes from OneDrive ...
Applying changes of Path ID: 66D53BE8A5056ECA!101
Uploading differences of .
Processing root
The directory has not changed
Uploading new items of .
Applying changes of Path ID: 66D53BE8A5056ECA!101
```

**Comment by norbusan** [comment]
@abraunegg thanks for testing. If you don't need a wording change, please review, code wise it is ready. Thanks a lot.

**Pull request merged**
