### PR TITLE
Update Docker.md

### PR DESCRIPTION
**Pull request by TheFlyingBadger**
Add environment variables section

### CODE REVIEW

**Comment by abraunegg** [comment]
@TheFlyingBadger 
Can this PR be merged with #638 - given that this really is the doco update for that PR ?

**Comment by TheFlyingBadger** [comment]
Correct. Is that something that I need to do?

**Comment by abraunegg** [comment]
@TheFlyingBadger 
Yep - close this PR, and add the change to #638

**Comment by TheFlyingBadger** [comment]
OK. All done. I'm still working through making sense of git, 25 years of
PVCS/SCCS/SourceSafe/TFS isn't helping me!

**Pull request closed without merging**
