### PR TITLE
Fix crash when resume_upload file is not a valid JSON

### PR DESCRIPTION
**Pull request by abraunegg**
* Validate that there is JSON data in the string before the string is read via parseJSON()

### CODE REVIEW

**Comment by abraunegg** [comment]
@norbusan 
The only way to trigger this is the following:
* Use a Business Account
* During a large file (4-10Mb), cancel the upload via ctrl-c
* Edit the `resume_upload` file by deleting all the contents
* Restart the application

**without patch:**
```
Using Config Dir: /home/alex/.config/onedrive-business/
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDriveBusiness
Application version: v2.3.9-11-g2abc05a
Account Type: business
Default Drive ID: b!Q22DuXRDLUChhFdENvkg16JXx-SRWqJLraLRvJMRnLKSb-uRulbNSaPWBn1zlHju
Default Root ID: 01UWAQAHV6Y2GOVW7725BZO354PWSELRRZ
Remaining Free Space: 1099442844591
Fetching details for OneDrive Root
OneDrive Root exists in the database
Trying to restore the upload session ...
std.json.JSONException@std/json.d(306): JSONValue is not an object
----------------
/home/alex/dlang/dmd-2.085.0/linux/bin64/../../src/phobos/std/exception.d:515 pure @safe void std.exception.bailOut!(std.json.JSONException).bailOut(immutable(char)[], ulong, scope const(char)[]) [0x5ee817]
/home/alex/dlang/dmd-2.085.0/linux/bin64/../../src/phobos/std/exception.d:436 pure @safe bool std.exception.enforce!(std.json.JSONException).enforce!(bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x5ee791]
??:? inout pure @property @trusted inout(std.json.JSONValue[immutable(char)[]]) std.json.JSONValue.objectNoRef() [0x649bbd]
/home/alex/dlang/dmd-2.085.0/linux/bin64/../../src/phobos/std/json.d:645 const pure @safe const(std.json.JSONValue)* std.json.JSONValue.opBinaryRight!("in").opBinaryRight(immutable(char)[]) [0x60b113]
src/upload.d:77 bool upload.UploadSession.restore() [0x6259d1]
src/sync.d:363 void sync.SyncEngine.init() [0x617b9f]
src/main.d:755 bool main.initSyncEngine(sync.SyncEngine) [0x605f2c]
src/main.d:522 _Dmain [0x604c7e]
```

**with patch:**
```
Using Config Dir: /home/alex/.config/onedrive-business/
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDriveBusiness
Application version: v2.3.9-11-g2abc05a
Account Type: business
Default Drive ID: b!Q22DuXRDLUChhFdENvkg16JXx-SRWqJLraLRvJMRnLKSb-uRulbNSaPWBn1zlHju
Default Root ID: 01UWAQAHV6Y2GOVW7725BZO354PWSELRRZ
Remaining Free Space: 1099442844591
Fetching details for OneDrive Root
OneDrive Root exists in the database
Trying to restore the upload session ...
Upload session resume data is invalid            <- new entry as resume_upload data was invalid
Initializing the Synchronization Engine ...
Syncing changes from OneDrive ...
Applying changes of Path ID: 01UWAQAHV6Y2GOVW7725BZO354PWSELRRZ
Uploading differences of .
Processing root
The directory has not changed
Processing random_files
The directory has not changed
Processing ILg9AFI0BLiE1TwT3fK4j0atyyKyZNd3
The directory has not changed
Uploading new items of .
.......
```

**Comment by norbusan** [comment]
Hi @abraunegg 
I don't have business accounts anymore, the test period has ended and all the business accounts are shut down :-(
Code looks fine to me, build and runs.

**Comment by abraunegg** [comment]
@norbusan 
No problem - will wait till the user confirms a fix for this.

Based on logic, the same issue 'should' occur with Personal accounts, you just have to ensure your file set is > 5Mb to test with

**Comment by abraunegg** [comment]
* Fix additional file system exception when attempting to set the time of the files on the file system

**Pull request merged**
