### PR TITLE
Handle deletion events when inotify events are missing

### PR DESCRIPTION
**Pull request by abraunegg**
* Handle the missing inotify events for deleted items as a deletion event when running in --monitor

### CODE REVIEW

**Comment by abraunegg** [comment]
**Without PR:**
```
./onedrive --confdir '~/.config/onedrive-personal/' --monitor --verbose
Using 'user' Config Dir: /home/alex/.config/onedrive-personal/
Using 'system' Config Dir: 
Configuration file successfully loaded
Notification (dbus) server not available, disabling
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Opening the item database ...
All operations will be performed in: /home/alex/OneDrivePersonal
Application version: v2.4.5-19-g38e9cc1
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 5368709120
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Initializing monitor ...
OneDrive monitor interval (seconds): 30
Monitor directory: .
Starting a sync with OneDrive
Applying changes of Path ID: 66D53BE8A5056ECA!101
Updated Remaining Free Space: 5368709120
Uploading differences of ~/OneDrivePersonal
Processing .
The directory has not changed
Uploading new items of ~/OneDrivePersonal
Applying changes of Path ID: 66D53BE8A5056ECA!101
Updated Remaining Free Space: 5368709120
Processing 1 OneDrive items to ensure consistent local state due to a full scan being requested
Sync with OneDrive is complete
[M] File changed: ./test.txt
Uploading differences of ./test.txt
Uploading new items of ./test.txt
Uploading new file ./test.txt ... done.
Remaining free space on OneDrive: 5368709095
^CGot termination signal, shutting down db connection
(dmd-2.092.0)[alex@centos7full onedrive]$ ./onedrive --confdir '~/.config/onedrive-personal/' --monitor --verbose
Using 'user' Config Dir: /home/alex/.config/onedrive-personal/
Using 'system' Config Dir: 
Configuration file successfully loaded
Notification (dbus) server not available, disabling
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Opening the item database ...
All operations will be performed in: /home/alex/OneDrivePersonal
Application version: v2.4.5-19-g38e9cc1
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 5368709095
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Initializing monitor ...
OneDrive monitor interval (seconds): 30
Monitor directory: .
Starting a sync with OneDrive
Applying changes of Path ID: 66D53BE8A5056ECA!101
Updated Remaining Free Space: 5368709095
Number of items from OneDrive to process: 2
Uploading differences of ~/OneDrivePersonal
Processing .
The directory has not changed
Processing test.txt
The file appears to have been deleted locally .. but we are running in --monitor mode. This may have been 'moved' rather than 'deleted'
Uploading new items of ~/OneDrivePersonal
Applying changes of Path ID: 66D53BE8A5056ECA!101
Updated Remaining Free Space: 5368709095
Processing 1 OneDrive items to ensure consistent local state due to a full scan being requested
Sync with OneDrive is complete
Starting a sync with OneDrive
Applying changes of Path ID: 66D53BE8A5056ECA!101
Updated Remaining Free Space: 5368709095
Uploading differences of ~/OneDrivePersonal
Processing .
The directory has not changed
Processing test.txt
The file appears to have been deleted locally .. but we are running in --monitor mode. This may have been 'moved' rather than 'deleted'
Uploading new items of ~/OneDrivePersonal
Applying changes of Path ID: 66D53BE8A5056ECA!101
Updated Remaining Free Space: 5368709095
Sync with OneDrive is complete
^CGot termination signal, shutting down db connection
```

No deletion action to remove file from OneDrive.

**With PR:**
```
./onedrive --confdir '~/.config/onedrive-personal/' --monitor --verbose
Using 'user' Config Dir: /home/alex/.config/onedrive-personal/
Using 'system' Config Dir: 
Configuration file successfully loaded
Notification (dbus) server not available, disabling
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Opening the item database ...
All operations will be performed in: /home/alex/OneDrivePersonal
Application version: v2.4.5-20-g4a5818b
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 5368709120
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Initializing monitor ...
OneDrive monitor interval (seconds): 30
Monitor directory: .
Starting a sync with OneDrive
Applying changes of Path ID: 66D53BE8A5056ECA!101
Updated Remaining Free Space: 5368709120
Uploading differences of ~/OneDrivePersonal
Processing .
The directory has not changed
Uploading new items of ~/OneDrivePersonal
Applying changes of Path ID: 66D53BE8A5056ECA!101
Updated Remaining Free Space: 5368709120
Processing 1 OneDrive items to ensure consistent local state due to a full scan being requested
Sync with OneDrive is complete
[M] File changed: ./test.txt
Uploading differences of ./test.txt
Uploading new items of ./test.txt
Uploading new file ./test.txt ... done.
Remaining free space on OneDrive: 5368709095
^CGot termination signal, shutting down db connection
(dmd-2.092.0)[alex@centos7full onedrive-pr1073]$ ./onedrive --confdir '~/.config/onedrive-personal/' --monitor --verbose
Using 'user' Config Dir: /home/alex/.config/onedrive-personal/
Using 'system' Config Dir: 
Configuration file successfully loaded
Notification (dbus) server not available, disabling
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Opening the item database ...
All operations will be performed in: /home/alex/OneDrivePersonal
Application version: v2.4.5-20-g4a5818b
Account Type: personal
Default Drive ID: 66d53be8a5056eca
Default Root ID: 66D53BE8A5056ECA!101
Remaining Free Space: 5368709095
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Initializing monitor ...
OneDrive monitor interval (seconds): 30
Monitor directory: .
Starting a sync with OneDrive
Applying changes of Path ID: 66D53BE8A5056ECA!101
Updated Remaining Free Space: 5368709095
Number of items from OneDrive to process: 2
Uploading differences of ~/OneDrivePersonal
Processing .
The directory has not changed
Processing test.txt
The file appears to have been deleted locally .. but we are running in --monitor mode. This may have been 'moved' on the local filesystem rather than being 'deleted'
Deleting item from OneDrive: test.txt
Uploading new items of ~/OneDrivePersonal
Applying changes of Path ID: 66D53BE8A5056ECA!101
Updated Remaining Free Space: 5368709120
Processing 2 OneDrive items to ensure consistent local state due to a full scan being requested
Processing 1 OneDrive items to ensure consistent local state due to a full scan being requested
Sync with OneDrive is complete
^CGot termination signal, shutting down db connection
```

Deletion event now occurs correctly.

**Comment by abraunegg** [comment]
Regression introduced here: https://github.com/abraunegg/onedrive/commit/e321c373fd207779fc7891ce87f4573839904cbc#diff-a601932e4174e1bb743e6ea51f804d01

**Comment by abraunegg** [comment]
User confirmed as fixed with PR, restoring prior functionality lost due to #948 oversight.

**Review by norbusan — APPROVED** [review]
Indeed

**Pull request merged**
