### PR TITLE
systemd: disable non-working remaining sandboxing options

### PR DESCRIPTION
**Pull request by bluca**
ProtectSystem= and other sandboxing options require a user namespace in order to work as user units (the user manager does not run as root and thus without a user namespace it is unable to perform mounts).

We are looking to enable this implicitly. Very few user units use these options, so want to make sure it is intentional and won't cause regressions. The alternative is to remove ProtectSystem=.

### CODE REVIEW

**Comment by abraunegg** [comment]
@bluca 
What version of systemd is required for these options to be effective?

When will *all* distributions utilise this systemd version?

**Comment by bluca** [comment]
> @bluca What version of systemd is required for these options to be effective?
> 
> When will _all_ distributions utilise this systemd version?

This combination as configured here pretty much always worked. It works in the current Debian Stable with v247, for example.

**Comment by abraunegg** [comment]
@bluca 
> This combination as configured here pretty much always worked. It works in the current Debian Stable with v247, for example.

Thats my point .. not everyone runs Debian or Ubuntu .....

**Comment by bluca** [comment]
> @bluca
> 
> > This combination as configured here pretty much always worked. It works in the current Debian Stable with v247, for example.
> 
> Thats my point .. not everyone runs Debian or Ubuntu .....

Sure, but again there's no difference in that case, it is skipped.

If you prefer, I can instead remove `ProtectSystem` as well? There's no point in adding it then, it will not work without PrivateUsers.

**Comment by bluca** [comment]
> > @bluca
> > > This combination as configured here pretty much always worked. It works in the current Debian Stable with v247, for example.
> > 
> > 
> > Thats my point .. not everyone runs Debian or Ubuntu .....
> 
> Sure, but again there's no difference in that case, it is skipped.
> 
> If you prefer, I can instead remove `ProtectSystem` as well? There's no point in adding it then, it will not work without PrivateUsers.

done that just now in the latest push

**Comment by abraunegg** [comment]
This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

**Pull request merged**
