### PR TITLE
Catch a curl timeout exception

### PR DESCRIPTION
**Pull request by abraunegg**
* Catch a curl timeout exception

### CODE REVIEW

**Comment by abraunegg** [comment]
**trying to catch this:**
```
std.net.curl.CurlTimeoutException@std/net/curl.d(4363): Timeout was reached on handle 556D7967C330
----------------
??:? pure @safe void std.exception.bailOut!(std.net.curl.CurlTimeoutException).bailOut(immutable(char)[], ulong, scope const(char)[]) [0x77903fde]
??:? pure @safe bool std.exception.enforce!(std.net.curl.CurlTimeoutException).enforce!(bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) [0x77903f51]
??:? void std.net.curl.Curl._check(int) [0x778dd7e4]
??:? int std.net.curl.Curl.perform(std.typecons.Flag!("throwOnError").Flag) [0x778ddc3b]
??:? int std.net.curl.HTTP.perform(std.typecons.Flag!("throwOnError").Flag) [0x778dc710]
src/onedrive.d:588 std.json.JSONValue onedrive.OneDriveApi.perform() [0x7788501e]
src/onedrive.d:570 std.json.JSONValue onedrive.OneDriveApi.perform(const(void)[]) [0x77884da9]
src/onedrive.d:516 std.json.JSONValue onedrive.OneDriveApi.post!(char).post(const(char)[], const(char)[]) [0x778857c5]
src/onedrive.d:386 void onedrive.OneDriveApi.acquireToken(const(char)[]) [0x7788437e]
src/onedrive.d:371 void onedrive.OneDriveApi.redeemToken(const(char)[]) [0x7788426a]
src/onedrive.d:169 bool onedrive.OneDriveApi.authorize() [0x77882e4e]
src/onedrive.d:149 bool onedrive.OneDriveApi.init() [0x77882c8b]
```

**Comment by abraunegg** [comment]
Potentially ... also the crash may be caused by the throw e .... should we be throwing and exception which will exit the app?

**Comment by norbusan** [comment]
But reading the comments above I faintly remember that the exceptions are caught and the connection to onedrive server should be reinitialized. This is for dealing with offline stuff and temporary hickups

**Comment by abraunegg** [comment]
Yep .. but its crashing out somehow ...

**Comment by norbusan** [comment]
Does it crash in monitor mode or in single shot mode?

**Comment by norbusan** [comment]
AFAIR I only checked for that in monitor mode ...

**Comment by abraunegg** [comment]
Unsure ... sent you the email with the details

**Comment by norbusan** [comment]
DIdn't get an email by now...

**Comment by abraunegg** [comment]
> DIdn't get an email by now...

can you check your mail folders:
```
May 12, 2019 8:57:59 AM | Scanner ID: | mail.mynas.com.au
-- | -- | --
May 12, 2019 8:57:59 AM | Connecting from: | 172.19.19.13
May 12, 2019 8:57:59 AM | Sender: | alex.braunegg@mynas.com.au
May 12, 2019 8:57:59 AM | Recipient: | norbert@preining.info
May 12, 2019 8:57:59 AM | Subject: | FW: Can't sync onedrive account
May 12, 2019 8:57:59 AM | Size: | 13 K
May 12, 2019 8:57:59 AM | Attachments: |  
May 12, 2019 8:57:59 AM | Message ID: | 13B4181E3DA2B04F991B25278B557DFF4A1D@<redacted>
May 12, 2019 8:58:01 AM | Internal Message ID: | 2F5745B4-88A4-9D05-BD96-5A9B103C76BB
May 12, 2019 8:58:01 AM | Rule Name: |  
May 12, 2019 8:58:01 AM | Scan Action: | Passed IMSVA scan and deliver
May 12, 2019 8:58:08 AM | Delivery IP: | preining.info[142.4.209.99]:25
May 12, 2019 8:58:08 AM | Delivery Feedback: | 250 2.0.0 Ok: queued as 9B067FF21A


```

**Comment by norbusan** [comment]
Please resent, I must have deleted it. I see it in my mail log, but not the email :-(

**Comment by abraunegg** [comment]
resent

**Comment by norbusan** [comment]
Ok, as I thought. This is not the right place: https://dlang.org/library/std/net/curl/curl_timeout_exception.html shows that the code above already takes care, but rethrows, and thus the fine error is not caught somewhere in the path shown above. The original start is in `main.d` with
```
        if (!oneDrive.init()) {
                log.error("Could not initialize the OneDrive API");
                // workaround for segfault in std.net.curl.Curl.shutdown() on exit
                oneDrive.http.shutdown();
                return EXIT_FAILURE;
        }
```
The `onedrive.init` throws the exception via `init` -> `authorize` -> ...

Not sure at which level we should fix that. At least what is sure is that the code in this PR is a NOOP, as the catch above it already catches and rethrows it.

**Comment by norbusan** [comment]
@abraunegg what do you say to this proposal I just pushed to this branch?

**Comment by abraunegg** [comment]
@norbusan 
looks good to me

**Pull request merged**
