### PR TITLE
Implement recursive deletion when Retention Policy is enabled

### PR DESCRIPTION
**Pull request by chponte**
Hi. First time contributing to this project. I didn't find any instructions for contributors so I tried my best to preserve the same coding style as the rest of the file.
These changes should fix the warnings when removing a folder with content on drives with Retention Policy enabled (#338), as it is my case with my university. Although the code works fine, the last changes on monitor.d introduced an error where removing any empty folder may or may not result in a segmentation fault. I did rebase the changes onto the 2.4.2 tag and everything works fine there.
Cheers,
Christian

### CODE REVIEW

**Comment by abraunegg** [comment]
@chponte 
Many thanks for your contribution - it is greatly appreciated. I have reviewed, one minor change needed which I will do.

>  Although the code works fine, the last changes on monitor.d introduced an error where removing any empty folder may or may not result in a segmentation fault.

Is this as a result of this change or another change? Do you have any debug log or other details? If so, please open an issue tracker so that this can be investigated and worked on.

The last changes on 'monitor.d' were only to add debug logging output ..

**Comment by chponte** [comment]
Just one minor comment on your change, you replaced `1 + count(children)` with `1 + count(children)`, which may result in counting one less item than the ones you are about to delete, since the actual item requested to be deleted is not included in the children list. It should not impact the program behavior in any meaningful way anyways.

**Comment by abraunegg** [comment]
> since the actual item requested to be deleted is not included in the children list.

That's correct. The intention of 'classify_as_big_delete' is to prevent the accidental deletion of X number of children in a given folder, not to count the parent in the actual deletion count, as - well - it is already been counted  as being deleted elsewhere if it is a subdir of some other dir.

Another issue I have also noticed is this:
* For the new `foreach_reverse` block - making the call to the API to delete - OK, but what is missing is also removing the DB entry for the children that are being deleted.

**Comment by abraunegg** [comment]
@chponte 
If you can test this updated PR (given that you have the retention issue) and validate that all the DB entries for children are now being correctly removed when the parent it being removed & this issue being triggered.

**Comment by chponte** [comment]
Line https://github.com/abraunegg/onedrive/blob/aa8515021fac07c8fd6414d30626cebe0ce7fcc3/src/sync.d#L4019 already does that, doesn't it? When deleting the folder in the db, the children are also deleted, right? Otherwise, removing a folder for a normal OneDrive user will leave the children hanging in the db if I'm not mistaken.

**Comment by abraunegg** [comment]
> Line
> 
> https://github.com/abraunegg/onedrive/blob/aa8515021fac07c8fd6414d30626cebe0ce7fcc3/src/sync.d#L4019
> 
> already does that, doesn't it? When deleting the folder in the db, the children are also deleted, right? Otherwise, removing a folder for a normal OneDrive user will leave the children hanging in the db if I'm not mistaken.

Strictly speaking no. That statement calls this, which only has 2 inputs:
```
deleteItemByIdStmt = "DELETE FROM item WHERE driveId = ? AND id = ?";
```

In the scenario you are talking about, each individual path / folder is passed in for deletion, so if the parent has children, the local filesystem remove is done, the OneDrive API handles the children removal, however the cache DB IMHO is not being correctly handled (and should be).

**Comment by chponte** [comment]
I can't test anything since any operation that involves a folder removal ends with a segmentation fault. Debug logs (attached) end abruptly after the folder is removed (the folder is correctly removed from OneDrive, I checked via web). Entry is also removed from the local database. What I did was:
1. Create a folder under (OneDrive root)/test named c.
2. Remove the folder.
I can rebase the changes onto the latest tagged version of the program to test this PR, but there is an issue with the latest changes... I did not open an issue yet since I'm not sure its unrelated to the changes introduced here.

[debug_output.log](https://github.com/abraunegg/onedrive/files/4782954/debug_output.log)

**Comment by abraunegg** [comment]
@chponte 
Can you run 'master', without debug log, in a console - as the debug log does not show any crash.

**Comment by abraunegg** [comment]
@chponte 
My tests with 'master'
```
[alex@centos7full ~]$ cd OneDriveBusiness/
[alex@centos7full OneDriveBusiness]$ mkdir -p test/c
[alex@centos7full OneDriveBusiness]$ rmdir test/c/
[alex@centos7full OneDriveBusiness]$ 
```
application output:
```
./onedrive --confdir '~/.config/onedrive-business/' --monitor --verbose
Using 'user' Config Dir: /home/alex/.config/onedrive-business/
Using 'system' Config Dir: 
Configuration file successfully loaded
Notification (dbus) server not available, disabling
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDriveBusiness
Application version: v2.4.2-11-g42bc0bf
Account Type: business
Default Drive ID: b!bO8V7s9SSk6r7mWHpIjURotN33W1W2tEv3OXV_oFIdQimEdOHR-1So7CqeT1MfHA
Default Root ID: 01WIXGO5V6Y2GOVW7725BZO354PWSELRRZ
Remaining Free Space: 1098475177437
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Initializing monitor ...
OneDrive monitor interval (seconds): 120
Monitor directory: .
Monitor directory: ./random_files
Monitor directory: ./random_images
Monitor directory: ./random_videos
Starting a sync with OneDrive
Applying changes of Path ID: 01WIXGO5V6Y2GOVW7725BZO354PWSELRRZ
Uploading differences of .
Processing root
The directory has not changed
Processing random_files
The directory has not changed
Processing random_images
The directory has not changed
Processing random_videos
The directory has not changed
Processing newfile.txt
The file has not changed
Uploading new items of .
Applying changes of Path ID: 01WIXGO5V6Y2GOVW7725BZO354PWSELRRZ
Sync with OneDrive is complete
Monitor directory: ./test
Monitor directory: ./test/c
[M] Directory created: ./test
Uploading differences of ./test
Uploading new items of ./test
OneDrive Client requested to create remote path: ./test
The requested directory to create was not found on OneDrive - creating remote directory: ./test
Successfully created the remote directory ./test on OneDrive
OneDrive Client requested to create remote path: ./test/c
The requested directory to create was not found on OneDrive - creating remote directory: ./test/c
Successfully created the remote directory ./test/c on OneDrive
[M] Item deleted: test/c
Deleting item from OneDrive: test/c
Starting a sync with OneDrive
Applying changes of Path ID: 01WIXGO5V6Y2GOVW7725BZO354PWSELRRZ
Number of items from OneDrive to process: 3
Uploading differences of .
Processing root
The directory has not changed
Processing random_files
The directory has not changed
Processing random_images
The directory has not changed
Processing random_videos
The directory has not changed
Processing newfile.txt
The file has not changed
Processing test
The directory has not changed
Uploading new items of .
Applying changes of Path ID: 01WIXGO5V6Y2GOVW7725BZO354PWSELRRZ
Sync with OneDrive is complete

```

**Comment by abraunegg** [comment]
same test, but with this PR:
```
./onedrive --confdir '~/.config/onedrive-business/' --monitor --verbose
Using 'user' Config Dir: /home/alex/.config/onedrive-business/
Using 'system' Config Dir: 
Configuration file successfully loaded
Notification (dbus) server not available, disabling
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDriveBusiness
Application version: v2.4.2-15-gaa85150
Account Type: business
Default Drive ID: b!bO8V7s9SSk6r7mWHpIjURotN33W1W2tEv3OXV_oFIdQimEdOHR-1So7CqeT1MfHA
Default Root ID: 01WIXGO5V6Y2GOVW7725BZO354PWSELRRZ
Remaining Free Space: 1098475177133
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Initializing monitor ...
OneDrive monitor interval (seconds): 120
Monitor directory: .
Monitor directory: ./random_files
Monitor directory: ./random_images
Monitor directory: ./random_videos
Starting a sync with OneDrive
Applying changes of Path ID: 01WIXGO5V6Y2GOVW7725BZO354PWSELRRZ
Uploading differences of .
Processing root
The directory has not changed
Processing random_files
The directory has not changed
Processing random_images
The directory has not changed
Processing random_videos
The directory has not changed
Processing newfile.txt
The file has not changed
Uploading new items of .
Applying changes of Path ID: 01WIXGO5V6Y2GOVW7725BZO354PWSELRRZ
Sync with OneDrive is complete
Monitor directory: ./test
Monitor directory: ./test/c
[M] Directory created: ./test
Uploading differences of ./test
Uploading new items of ./test
OneDrive Client requested to create remote path: ./test
The requested directory to create was not found on OneDrive - creating remote directory: ./test
Successfully created the remote directory ./test on OneDrive
OneDrive Client requested to create remote path: ./test/c
The requested directory to create was not found on OneDrive - creating remote directory: ./test/c
Successfully created the remote directory ./test/c on OneDrive
[M] Item deleted: test/c
Deleting item from OneDrive: test/c
Starting a sync with OneDrive
Applying changes of Path ID: 01WIXGO5V6Y2GOVW7725BZO354PWSELRRZ
Number of items from OneDrive to process: 3
Uploading differences of .
Processing root
The directory has not changed
Processing random_files
The directory has not changed
Processing random_images
The directory has not changed
Processing random_videos
The directory has not changed
Processing newfile.txt
The file has not changed
Processing test
The directory has not changed
Uploading new items of .
Applying changes of Path ID: 01WIXGO5V6Y2GOVW7725BZO354PWSELRRZ
Sync with OneDrive is complete

```

no crash ..

**Comment by chponte** [comment]
With master:
```
➜  onedrive git:(fix-delete-with-retention) ✗ git checkout master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
➜  onedrive git:(master) ✗ ./configure 
checking for a BSD-compatible install... /usr/bin/install -c
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for dmd... dmd
checking version of D compiler... 2.092.0
checking for curl... yes
checking for sqlite... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating contrib/pacman/PKGBUILD
config.status: creating contrib/spec/onedrive.spec
config.status: creating onedrive.1
config.status: creating contrib/systemd/onedrive.service
config.status: creating contrib/systemd/onedrive@.service
➜  onedrive git:(master) ✗ make clean && make
rm -f onedrive onedrive.o version
rm -rf autom4te.cache
rm -f config.log config.status
if [ -f .git/HEAD ] ; then \
        git describe --tags > version ; \
else \
        echo v2.4.3-dev > version ; \
fi
dmd -w -g -O -J. -L-lcurl -L-lsqlite3  -L-ldl src/config.d src/itemdb.d src/log.d src/main.d src/monitor.d src/onedrive.d src/qxor.d src/selective.d src/sqlite.d src/sync.d src/upload.d src/util.d src/progress.d -ofonedrive
➜  onedrive git:(master) ✗ ./onedrive --monitor --verbose
Using 'user' Config Dir: /home/christian/.config/onedrive
Using 'system' Config Dir: /etc/onedrive
Configuration file successfully loaded
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/christian/OneDrive
Application version: v2.4.2-10-g7275b2f
Account Type: business
Default Drive ID: b!1py2ge9mCEyTIx43mUQUi58Hjd_pvK1IiOetkGXIYPCFkSzTMvcqS5UXREnu2X0Z
Default Root ID: 0132NKA4V6Y2GOVW7725BZO354PWSELRRZ
Remaining Free Space: 5493120442869
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Initializing monitor ...
OneDrive monitor interval (seconds): 30
Monitor directory: .
Monitor directory: ./test
Starting a sync with OneDrive
Applying changes of Path ID: 0132NKA4V6Y2GOVW7725BZO354PWSELRRZ
Number of items from OneDrive to process: 2
Uploading differences of .
Processing root
The directory has not changed
Processing test
The directory has not changed
Processing a.txt
The file has not changed
Processing b.txt
The file has not changed
Uploading new items of .
Applying changes of Path ID: 0132NKA4V6Y2GOVW7725BZO354PWSELRRZ
Processing 207 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by sync_list config: Papers
Skipping item - excluded by sync_list config: Comparison_work
Processing 207 OneDrive items to ensure consistent local state due to sync_list being used
Skipping item - excluded by sync_list config: Documentos
Skipping item - excluded by sync_list config: Comparison_work
Skipping item - excluded by sync_list config: Apuntes
Skipping item - excluded by sync_list config: Docencia
Skipping item - excluded by sync_list config: Papers
Skipping item - excluded by sync_list config: Tesis
Processing 155 OneDrive items to ensure consistent local state due to sync_list being used
The Microsoft OneNote Notebook './Christian @ Universidade da Coruña' is not supported by this client
Skipping item - excluded by sync_list config: Tesis
Skipping item - excluded by sync_list config: email_antonio
Skipping item - excluded by sync_list config: Microsoft Teams Chat Files
Skipping item - excluded by sync_list config: fiuncho_dev.xlsx
Skipping item - excluded by sync_list config: referencias.txt
Skipping item - excluded by sync_list config: Comparison_work
Skipping item - excluded by sync_list config: Docencia
Sync with OneDrive is complete
Monitor directory: test/c
[M] Directory created: test/c
Uploading differences of test/c
Uploading new items of test/c
OneDrive Client requested to create remote path: test/c
The requested directory to create was not found on OneDrive - creating remote directory: test/c
Successfully created the remote directory test/c on OneDrive
[M] Item deleted: test/c
Deleting item from OneDrive: test/c
Monitored directory removed: test/c/
[1]    121894 segmentation fault (core dumped)  ./onedrive --monitor --verbose
```

**Comment by chponte** [comment]
gdb indicated the following:
```
Thread 1 "onedrive" received signal SIGSEGV, Segmentation fault.
0x000055555586dc74 in _D3std8typecons__T10RefCountedTSQBe3net4curl4HTTP4ImplVEQCcQCb24RefCountedAutoInitializei1ZQCv15RefCountedStore13isInitializedMxFNaNbNdNiNfZb ()
(gdb) where
#0  0x000055555586dc74 in _D3std8typecons__T10RefCountedTSQBe3net4curl4HTTP4ImplVEQCcQCb24RefCountedAutoInitializei1ZQCv15RefCountedStore13isInitializedMxFNaNbNdNiNfZb ()
#1  0x000055555586dcc5 in _D3std8typecons__T10RefCountedTSQBe3net4curl4HTTP4ImplVEQCcQCb24RefCountedAutoInitializei1ZQCv15RefCountedStore17ensureInitializedMFNaNbNiZv ()
#2  0x000055555586de75 in _D3std8typecons__T10RefCountedTSQBe3net4curl4HTTP4ImplVEQCcQCb24RefCountedAutoInitializei1ZQCv17refCountedPayloadMFNaNbNcNdNiNjZQDt ()
#3  0x0000555555831bd3 in std.net.curl.HTTP.clearRequestHeaders() ()
#4  0x00005555557cda19 in onedrive.OneDriveApi.shutdown() (this=0x0) at src/onedrive.d:154
#5  0x00005555557cadf4 in D main (args=...) at src/main.d:55
```

**Comment by abraunegg** [comment]
> gdb indicated the following:
> 
> ```
> Thread 1 "onedrive" received signal SIGSEGV, Segmentation fault.
> 0x000055555586dc74 in _D3std8typecons__T10RefCountedTSQBe3net4curl4HTTP4ImplVEQCcQCb24RefCountedAutoInitializei1ZQCv15RefCountedStore13isInitializedMxFNaNbNdNiNfZb ()
> (gdb) where
> #0  0x000055555586dc74 in _D3std8typecons__T10RefCountedTSQBe3net4curl4HTTP4ImplVEQCcQCb24RefCountedAutoInitializei1ZQCv15RefCountedStore13isInitializedMxFNaNbNdNiNfZb ()
> #1  0x000055555586dcc5 in _D3std8typecons__T10RefCountedTSQBe3net4curl4HTTP4ImplVEQCcQCb24RefCountedAutoInitializei1ZQCv15RefCountedStore17ensureInitializedMFNaNbNiZv ()
> #2  0x000055555586de75 in _D3std8typecons__T10RefCountedTSQBe3net4curl4HTTP4ImplVEQCcQCb24RefCountedAutoInitializei1ZQCv17refCountedPayloadMFNaNbNcNdNiNjZQDt ()
> #3  0x0000555555831bd3 in std.net.curl.HTTP.clearRequestHeaders() ()
> #4  0x00005555557cda19 in onedrive.OneDriveApi.shutdown() (this=0x0) at src/onedrive.d:154
> #5  0x00005555557cadf4 in D main (args=...) at src/main.d:55
> ```

That is VERY weird.

Please open up a new issue for this, as this is separate to your PR.

Please ensure you detail what OS, filesystem, curl version etc you are using.

**Comment by abraunegg** [comment]
@chponte 
Unable to even get this to break under gdb:
```
(dmd-2.092.0)[alex@centos7full onedrive]$ gdb
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-119.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
(gdb) file ./onedrive 
Reading symbols from /home/alex/code/onedrive/onedrive...done.
(gdb) show args
Argument list to give program being debugged when it is started is "".
(gdb) set args --confdir '~/.config/onedrive-business/' --monitor --verbose 
(gdb) show args
Argument list to give program being debugged when it is started is "--confdir '~/.config/onedrive-business/' --monitor --verbose".
(gdb) r
Starting program: /home/alex/code/onedrive/./onedrive --confdir '~/.config/onedrive-business/' --monitor --verbose
warning: the debug information found in "/usr/lib/debug//lib64/libcurl.so.4.3.0.debug" does not match "/lib64/libcurl.so.4" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug/usr/lib64/libcurl.so.4.3.0.debug" does not match "/lib64/libcurl.so.4" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug//usr/lib64/libcurl.so.4.3.0.debug" does not match "/lib64/libcurl.so.4" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug/usr/lib64//libcurl.so.4.3.0.debug" does not match "/lib64/libcurl.so.4" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug//lib64/libsqlite3.so.0.8.6.debug" does not match "/lib64/libsqlite3.so.0" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug/usr/lib64/libsqlite3.so.0.8.6.debug" does not match "/lib64/libsqlite3.so.0" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug//usr/lib64/libsqlite3.so.0.8.6.debug" does not match "/lib64/libsqlite3.so.0" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug/usr/lib64//libsqlite3.so.0.8.6.debug" does not match "/lib64/libsqlite3.so.0" (CRC mismatch).

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Using 'user' Config Dir: /home/alex/.config/onedrive-business/
Using 'system' Config Dir: 
Configuration file successfully loaded
[New Thread 0x7ffff0f67700 (LWP 10464)]
Notification (dbus) server not available, disabling
[New Thread 0x7fffebfff700 (LWP 10465)]
[Thread 0x7fffebfff700 (LWP 10465) exited]
Initializing the OneDrive API ...
Opening the item database ...
All operations will be performed in: /home/alex/OneDriveBusiness
[New Thread 0x7fffebfff700 (LWP 10466)]
[Thread 0x7fffebfff700 (LWP 10466) exited]
[New Thread 0x7fffebfff700 (LWP 10467)]
[Thread 0x7fffebfff700 (LWP 10467) exited]
Application version: v2.4.2-11-g42bc0bf
Account Type: business
Default Drive ID: b!bO8V7s9SSk6r7mWHpIjURotN33W1W2tEv3OXV_oFIdQimEdOHR-1So7CqeT1MfHA
Default Root ID: 01WIXGO5V6Y2GOVW7725BZO354PWSELRRZ
Remaining Free Space: 1098475176829
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Initializing monitor ...
OneDrive monitor interval (seconds): 120
Monitor directory: .
Monitor directory: ./random_files
Monitor directory: ./random_images
Monitor directory: ./random_videos
Monitor directory: ./test
Starting a sync with OneDrive
Applying changes of Path ID: 01WIXGO5V6Y2GOVW7725BZO354PWSELRRZ
Uploading differences of .
Processing root
The directory has not changed
Processing random_files
The directory has not changed
Processing random_images
The directory has not changed
Processing random_videos
The directory has not changed
Processing newfile.txt
The file has not changed
Processing test
The directory has not changed
Uploading new items of .
Applying changes of Path ID: 01WIXGO5V6Y2GOVW7725BZO354PWSELRRZ
Sync with OneDrive is complete
[New Thread 0x7ffff7fe9700 (LWP 10468)]
Monitor directory: test/c
[M] Directory created: test/c
Uploading differences of test/c
Uploading new items of test/c
OneDrive Client requested to create remote path: test/c
The requested directory to create was not found on OneDrive - creating remote directory: test/c
Successfully created the remote directory test/c on OneDrive
[M] Item deleted: test/c
Deleting item from OneDrive: test/c
[M] Item deleted: ./test
Deleting item from OneDrive: ./test

```

No crash ... please open an issue ticket with all the required details as soon as possible.

**Comment by chponte** [comment]
> @chponte
> If you can test this updated PR (given that you have the retention issue) and validate that all the DB entries for children are now being correctly removed when the parent it being removed & this issue being triggered.

After incorporating the fix from https://github.com/abraunegg/onedrive/pull/957, I verified that the program works as intended and all the children are removed from the database.

**Pull request merged**
